### PR TITLE
fixes medihover eyes out of sync

### PR DESCRIPTION
**Pull request by utahclock**
dont know why the final version eyes didnt merge with git....

### CODE REVIEW

**Comment by Notamaniac** [comment]
Are you sure you've committed the right file? This one doesn't have the eye sprite or the mediborg sprite

**Comment by utahclock** [comment]
had wrong repo pushed fixed now with correct repo file.

**Comment by Notamaniac** [comment]
Coolio

**Comment by Greatbigben** [comment]
When merged will close

**Pull request merged**
