### PR TITLE
Chef's meat locker now confers immunity to nukes (feature request #163)

### PR DESCRIPTION
**Pull request by toneo-**
(see issue #163)

Minor change, 4 lines in one file.

The chef's meat locker is the only lead-lined freezer as he is a militant vegan. If you hide in the other freezers you will find only death and bacon.
This shouldn't affect antag greentext - nukeops wins regardless of deaths, as does malfai, etc, etc.

### CODE REVIEW

**Comment by ghost** [comment]
Seems good.

**Comment by AsV9** [comment]
[https://www.youtube.com/watch?v=lbrzQMbTYZM](https://www.youtube.com/watch?v=lbrzQMbTYZM)

**Comment by Super3222** [comment]
Perfect.

Now we can all cram together inside of the freezer when the newcops make off with the disk.

**Comment by oisin100** [comment]
Inb4 nuke ops nuke the station and hide in the fridge

**Pull request merged**
