### PR TITLE
Readds the arrivals announcement system to telecomns control room and remaps it

### PR DESCRIPTION
**Pull request by Notamaniac**
I have no idea why this was removed, but I've readded it to tcomms rather than where it used to be (RD's office) because it's a piece of telecoms machinery, not the RD's personal agenda machine.

Reference:
newcomns

### CODE REVIEW

**Comment by oisin100** [comment]
:+1:  x :100: 

But now Tcomms isn't symmetrical...

It was never removed in the first place. The AI used to do it and when /TG/ added the AAS we never gave it a home.

**Comment by Notamaniac** [comment]
There wasn't really a way of adding it back in without removing the tables and all the stuff on it, or pushing all of the server room to the right by one, which would've been a lot more effort.

Also it used to be on the map in the RD's office, I just don't know who removed it from the map or why.

**Comment by Satile1** [comment]
Might I make a hastily edited suggestion? 
yqvolob

**Comment by Notamaniac** [comment]
I didn't do that because I wanted to preserve the route that lets you smash directly into the server room  to get into there, without having to decon any of the machines or smash through another set of windows. It's a bit minor but yeah.

**Comment by Notamaniac** [comment]
You know what I just realised was missing? The damn camera.

**Comment by Alek2ander** [comment]
You can just put it in the actual server room. Because this ruins the symmetry, muh OCD.

**Comment by Notamaniac** [comment]
Going into the server room requires a hardsuit and the AAS doesn't need cooling compared to the other  telecomns machines. And besides if I placed in the server room I'd ruin the symmetry there too 

If symmetry REALLY mattered I could expand the cooling room by two tiles but come on guys that's literally the definition of OCD

**Comment by oisin100** [comment]
OCD or not. Satellite will look ugly if one side is longer than the other.

**Comment by Notamaniac** [comment]
tcommsagain

_Insert grumble about players only having a seven tile view range_

**Comment by DavidEdwards** [comment]
Great! I don't really care about the symmetry of the satellite honestly, but if the people with OCD could check it matches their OCD preferences, that would be great ;-P

**Comment by Satile1** [comment]
Almost doubling the size of two rooms, just so people don't have to break one extra window to bust into the server room? Place is supposed to be secure, let 'em put a bit more work in. 

Personally, I find all the extra blank space this adds is ugly. 

And as an aside.. the main server room could actually benefit from a remap. The layout of the machines is pretty and all, but it's painful to actually work on, since the vents shove you backwards from the central corridors.

**Comment by Notamaniac** [comment]
I'll see what others say about this, I personally don't like completely cramming a room, and leaving some space for any future additions seems like a good idea.

I also don't see an easy way of remapping the server room, those vents are always going to be an issue, and I see no remap that's going to let you brace yourself against other machines to work on them, without causing others to fall to the same issue

**Comment by ToGWtF** [comment]
To be honest, the R&D server room in science has a perfect spot for this machine, and would allow the RD to get his grubby mitts on it to change its displace message/repair/replace it

**Comment by Notamaniac** [comment]
Well I wanted to place it in tcomms because it's something relating to tcomms, not science, but it doesn't seem like this PR is going to go through, so I'll close it at the end of today in case anyone else wants to voice their opinion on this

**Comment by oisin100** [comment]
> but it doesn't seem like this PR is going to go through

Give it time. Feedback is pretty positive so it will probably get merged.

As long as the satellite is still symmetrical im happy.

**Comment by AsV9** [comment]
Wasn't there a window in the north room before?

**Comment by oisin100** [comment]
> Wasn't there a window in the north room before?

There was... Can you re-add it  @Notamaniac please?

**Comment by DavidEdwards** [comment]
Don't close it. I'm just waiting for feedback from people with OCD before it goes through.

**Comment by Notamaniac** [comment]
Well I'll readd the window, then I'll pretty much leave this PR alone

**Comment by ShadowDeath6** [comment]
I like just adding it to the control room, since it lets CE fuck with tcomms even more than before, which is (usually) a good thing.

**Comment by ghost** [comment]
For FUCK'S SAKE

Nobody even GOES to telecomms

Who CARES if it's symmetrical? Get over your OCD.

It's an important feature that has 20 replies and has been delayed endlessly because 'muh symmetry'

It doesn't matter where it's located. It could be located in the clown's asshole because I guarantee you there will be absolutely zero shits given if one side of tcomms is one tile larger than the other so merge this already.

**Pull request merged**
