### PR TITLE
Spooky Goasts

### PR DESCRIPTION
**Pull request by TehFlaminTaco**
Adds an extra option to ghost preferences for donators, "Corpse", which looks like whatever body the player had when they ghosted.

### CODE REVIEW

**Comment by TehFlaminTaco** [comment]
Note, for some reason I have a groxic PR on here. No idea why, but I do.

**Comment by X-TheDark** [comment]
Cool. Those PR are probably because you haven't updated your repo (dev) and are using master as your base which is no longer used for merging PRs.

**Comment by DavidEdwards** [comment]
1. Please make a changelog
2. ~~See if you can remove unnecessary commits from your PR~~ Can ignore this part.
3. For future PRs please make your changes on the dev branch

Looking forward to merging this. Looks like a good addition.

**Comment by DavidEdwards** [comment]
Taco, please make a changelog for this PR.

**Comment by TehFlaminTaco** [comment]
Gonna make two Changelogs in one separate pull to save time.

**Comment by DavidEdwards** [comment]
Ok - cheers!

**Pull request merged**
