### PR TITLE
Mindslave Metanerf Option #2

### PR DESCRIPTION
**Pull request by oisin100**
When someone is implanted it will grab a random observer with BE_TRAITOR enabled.

Mindslave implant cost dropped to 10TC
#284

### CODE REVIEW

**Comment by oisin100** [comment]
Theres a extra newline there whats not supposed to be there... Ill remove it once someone asks for something in this option...

**Comment by Time-Green** [comment]
Thats a really good idea, it prevents metagaming.

I'm not sure if theres a timer, but then the player could be placed back? Or not.

Gud idea, you got my support

**Comment by oisin100** [comment]
It will check all the observing players if any of them have traitor enabled it will add them to a list and then select a random one of them

If it doesent find a player however then the implantee gets to keep his body...

**Comment by ShadowDeath6** [comment]
This really doesn't sound like a good idea. 
There's going to be way too many cases where you mindslave a person you know is good and have them turn useless because people are bad. 
Literally nobody will buy this if you do it for fear of wasting TC.

**Comment by FluffySurvivor** [comment]
Is an antag token included for the 90% chance of getting killed by your own slave? I bet it's not. 
Fuck these nerfs man. Github turned into QQ threads. "i got robusted please nerf"

**Comment by Time-Green** [comment]
Lets just fucking keep it as it is.

I still dont fucking understand why they are changing it. Feels like total bull.

Robust player team? Well, thats your problem. And its easier to catch metagamers.

**Comment by ghost** [comment]
Yeah, leave it as is. Against.

**Comment by DavidEdwards** [comment]
This isn't a bad idea. Pulling from the pool of traitors is a smart move. It does however wreck the game for someone else.

**Comment by Stealthkibbler** [comment]
Biggest issue with this is if you do it on your target it immediately removes them from the game, no chance of cloning at all. I Still think it should be turned into the revs recruitment item.

**Comment by oisin100** [comment]
What do you mean @Stealthkibbler ?
Closing this.

**Pull request closed without merging**
