### PR TITLE
Adds an RCD and an upgraded industrial welder to CE's locker

### PR DESCRIPTION
**Pull request by FluffySurvivor**
### Intent of your Pull Request

Currently, the CE has no specialized or useful gear. This PR will bring the CE in line with other heads and help him achieve the CHIEF engineer identity he lacks, assuring he has a much-needed RCD in case greedy engineers get all 3. Another benefit is that antags will actually feel good when looting his locker, because atm you can't get anything powerful/interesting from it.

### CODE REVIEW

**Comment by oisin100** [comment]
Fluffy Coding?

**Comment by FluffySurvivor** [comment]
THE MIRACLE

**Comment by X-TheDark** [comment]
Oh yeah, what about the AMAZING DAMN NON-SLIP MAGBOOTS WITHOUT ANY SPEED PENALTY?

Really, do you even know how good those are?

**Comment by FluffySurvivor** [comment]
i am well aware dark, but those are only good in very specific cases, where RD's armor, hypo, HoP's all access/armor/egun, HoS' shitton of gear come easily on top in ANY situation

**Comment by ShadowDeath6** [comment]
Tbh the noslip magboots and the hardsuit are still super robust but it's nice that CE doesn't need to loot engi vendors for shit

**Comment by ghost** [comment]
I'd say give the CE an RPD/RCD combo, so he can multitask, rather than just an RCD.

As in, an RCD and RPD in one.

Make it a traitor steal obj too.

**Comment by Cruix** [comment]
CE already has twice as many steal objectives as any other head except the captain. I do like the idea of the RPD/RCD combo though.

**Comment by Super3222** [comment]
Nice one Fluffy :+1:

and like Cruix & Adam said a back-to-back RCD/RPD combo would **DEFINITELY** be a pretty handy tool for the CE ...and pretty cool.

**Comment by Time-Green** [comment]
I don't think fluffy is doing that, so I will make the RCD/RPD combo
Shouldn't be that hard

**Comment by Cruix** [comment]
I was working on this earlier today while I was bored, but you can have it. There are a couple ways to do this, and I chose to make a new object that holds an RCD and RPD in it, and sends proc calls to whichever is selected. Here's my code (it won't compile just yet):

[ss13.txt](https://github.com/yogstation13/yogstation/files/200353/ss13.txt)

If you want to use it, you'll also have to split up some of the procs in RCD and RPD code to handle dodging adjacency checks and the like.

Whatever you do, try to avoid large amounts of copypasta.

**Comment by Time-Green** [comment]
Thanks cruix.
I already got the RED. I just need to debug it a shitton

**Comment by DavidEdwards** [comment]
Closing this because we are looking at a better version for CE.

**Pull request closed without merging**
