### PR TITLE
Adds rule 0.0.1

### PR DESCRIPTION
**Pull request by Groudonmaster**
-Adds rule 0.0.1 no unnecessary restart votes.

Fuck this has been a problem lately and we need to fix it.

### CODE REVIEW

**Comment by B1gb3ast** [comment]
yes.

**Comment by Super3222** [comment]
sounds good :+1:

**Comment by ghost** [comment]
speedmerge go go go go go go

**Comment by Alek2ander** [comment]
So this is the second most important rule of the server. O---kay then.

**Comment by Groudonmaster** [comment]
No it was just the most relevant place to stick it and it's a child of 0.0

**Comment by Wardog390** [comment]
so uh when are we going to merge this?

**Comment by george99g** [comment]
Why did you include the pull request commit from your own fork into this pull request?
Also, could you possibly fix the line endings?
In reality you've done 14 additions but GitHub says you've done 84 additions and 70 deletions because you've changed the line endings on a lot of lines.

**Comment by Groudonmaster** [comment]
I don't know how to pick and choose commits George. And I didn't even touch the other lines I don't know how they changed. I'll look into it after work cause I don't like doing changes from my phone

**Comment by AsV9** [comment]
This doesn't actually do anything to the rules on the main server. This file is quite outdated. To edit the rules you have to edit a page on the forums. Closing this, but discussion is still welcome.

EDIT: In addition, might I add, additions and changes to existing rules should always pass in the council.

**Pull request closed without merging**
