### PR TITLE
Mediborg Buff 1 : Defibrillator

### PR DESCRIPTION
**Pull request by X-TheDark**
Mediborgs now have defibrillators that can be used. Costs 2000 energy. Emagged mediborgs can use it offensively (harm intent).

Cannot be used below 2500 energy (2000+500 safety net).

### CODE REVIEW

**Comment by DavidEdwards** [comment]
A lot of changes here. Things look alright. Have you thoroughly tested it?

**Comment by X-TheDark** [comment]
Damn, one moment. Let me actually test the regular defibrillator (the cyborg part has been tested with dead/living humans while emagged/not emagged).

**Comment by X-TheDark** [comment]
Yup, all good to go. Regular defib works emagged/not emagged on help (revive), help (heart attack), disarm and hurt settings.

Mediborg defibs also work on harm settings, if the borg is emagged.

**Comment by ShadowDeath6** [comment]
How would the disarm-type setting work on borg, since it only has help and harm?

**Comment by X-TheDark** [comment]
It doesn't work on mediborgs, nor did this addition intend for it to work.

**Comment by ShadowDeath6** [comment]
Well, if it's emagged, the disarm setting would work as a good stun.

**Pull request merged**
