### PR TITLE
Ghetto icon updates.

### PR DESCRIPTION
**Pull request by oisin100**
Updates ghetto weaponry icons(Just the swords) Ill post the Pngs in a second.

### CODE REVIEW

**Comment by oisin100** [comment]
If theres any nerfs you would like please tell me now.

**Comment by ShadowDeath6** [comment]
> I'll post the pngs in a second

**Comment by oisin100** [comment]
http://imgur.com/a/PZMcb

**Comment by DavidEdwards** [comment]
Changelog. Honk.

**Comment by oisin100** [comment]
> Changelog. Honk.

Done.

**Pull request merged**
