### PR TITLE
Blub Balance PR 2

### PR DESCRIPTION
**Pull request by ghost**
### Intent of your Pull Request

Borrows /tg/'s system of decreased blob expansion at farther ranges.
#### Changelog

:cl:
rscadd: Blob automatic expansion chance decreases as the blob gets farther away from its core.
/:cl:

### CODE REVIEW

**Comment by FluffySurvivor** [comment]
make the biohazard announcement appear in the place of the "classified" announcement so admins cant yell meta. 

helps so people can get fighting faster too

**Comment by ghost** [comment]
I don't know about that, Fluffy.

**Comment by ShadowDeath6** [comment]
It's not meta, and even if it is you can wait like 3 minutes for it anyway

**Comment by ShadowDeath6** [comment]
It's not meta, and even if it is you can wait like 3 minutes for it anyway

**Comment by ghost** [comment]
nobody gives a fuck if you yell BLBO because of classified

but yeah sure make it show in place of the classified

ALSO

it's worth mentioning that past a certain point, blob really can't be stopped anyway

making it weaker to fire, welders, lasers, or something might be nice

or maybe just making killing a node disable blob point regen temporarily since it usually has a metric fuckton of them

**Comment by FluffySurvivor** [comment]
i really don't want people to suffer because of some metahitler admin

**Comment by ShadowDeath6** [comment]
Some blob types actually die in one laser shot anyway

**Comment by ghost** [comment]
it'd be good to make ALL blob types die in one laser shot so that lasers aren't completely useless versus a big blob

buff fire maybe too to kill normal blob tiles and nodes much faster

**Comment by oisin100** [comment]
> Blob automatic expansion chance decreases at rangers farther from the core.

Blob automatic expansion chance decreases as the blob gets farther away from the core.

**Pull request merged**
