### PR TITLE
Adds Catalade

### PR DESCRIPTION
**Pull request by Cruix**
Committed for Groxic because his Git isn't working.
Adds the reagent Catalade.
While catalade is in your system, all other drugs will metabolize 2x faster than normal, your nutrition will be drained, you will run fast, and you will take minor toxin damage. While overdosing, all effects are increased significantly.

Recipe is: 2 oxygen, 2 potassium, 2 ephedrine, 2 epinephrine, 1 flourine, 1 iodine, 2 strange_reagent, 2 methamphetamine, 2 lipolicide.

### CODE REVIEW

**Comment by ghost** [comment]
Also, overdose is included at 15u.

**Comment by ShadowDeath6** [comment]
I can only see this being used for a speed increase or in the meme patches that chemists make that fully heal them in 2.3 seconds from crit.

also that recipe makes it so that nobody will ever want it unless they use an odysseus to replicate it

**Comment by ghost** [comment]
2 second deaths?

**Comment by ShadowDeath6** [comment]
You can do that with regular chemicals without needing to bother botany or the chaplain for strange reagent.

**Comment by ghost** [comment]
How do you do it? Also, I need to fix the code for recipe, so do NOT merge.

**Comment by ShadowDeath6** [comment]
Just make Last Whisper, it's that custom chem mix that kills in like 3 seconds because it's got like 8 different toxins in it.

**Comment by ghost** [comment]
so basically calomel + meth

**Comment by ghost** [comment]
It is similar to calomel, but instead of purging chemicals, it speeds up metabolism.

**Pull request merged**
