### PR TITLE
Renames tgstation.dme to yogstation.dme and fixes Travis.yml

### PR DESCRIPTION
**Pull request by AsV9**
Renames tgstation.dme to yogstation.dme. Github tracks the file just fine, this shouldn't result in conflicts.

Possibly the most important commit of the century.

### CODE REVIEW

**Comment by george99g** [comment]
:smiley_cat:

**Comment by george99g** [comment]
:+1: \* :1234:

**Comment by george99g** [comment]
:dog2:

**Comment by george99g** [comment]
This is a quality comment.
I totally did not just discover emojis.
:smirk_cat:

**Comment by AsV9** [comment]
Meanwhile @George99g has unlocked the true power of GitHub :ok_hand:

**Comment by george99g** [comment]
# Yay!

**Comment by Alek2ander** [comment]
:eggplant:

**Comment by AdamElTablawy** [comment]
👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌there👌👌👌 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit

**Comment by george99g** [comment]
Yes I can, @AdamElTablawy

**Comment by AsV9** [comment]
fuck it

**Pull request merged**
