### PR TITLE
Puts a button in chemistry to open medbay doors.

### PR DESCRIPTION
**Pull request by AsV9**
I can't fucking believe nobody has done this yet.

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
Why is this needed, though?

**Comment by AsV9** [comment]
Because it's useful as fuck.

**Comment by ghost** [comment]
yes yes yes.

chemistry standing and watching as you bang on the medbay doors is infuriating as FUCK

**Comment by Time-Green** [comment]
Finnaly.
Its not fun when you or someone else is slowly dying and the chemist is just staring at you bleeding to death.

**Pull request merged**
