### PR TITLE
Fixes 'Toggle Antag Icons' Not showing gang members correctly.

### LINKED ISSUE #450: Admin antag HUD doesn't work with gangs
### Expected Behaviour

Admin antag HUD shows different colored icons for different gangs, and can distinguish bosses and normal gangsters
### Actual Behaviour

All gangsters show the same [?] unknown antag icon

### PR DESCRIPTION
**Pull request by oisin100**
Just makes life simple on the Admins.

Fixes #450

### CODE REVIEW

**Comment by Alek2ander** [comment]
This will give the same icon to all gangs, different gangs should really have different icons.

**Comment by oisin100** [comment]
> This will give the same icon to all gangs, different gangs should really have different icons.

This will require some Spriter support. Does someone want to make the sprites?

**Comment by Time-Green** [comment]
Wait, if you don't give every gang a special color. Then this was pointless

**Comment by oisin100** [comment]
> Wait, if you don't give every gang a special color. Then this was pointless

It shows if they are part of a gang and if they are a gang boss. Where as before it would display them as a unknown antag. Ill see what i can do to distinguish between gangs.

**Comment by oisin100** [comment]
I came up with a much better way to do this.

**Pull request closed without merging**
