### PR TITLE
Portalgun Price reduction.

### PR DESCRIPTION
**Pull request by oisin100**
Simple. Portal guns research price reduced to level 5 Combat instead of level 6. Meaning you dont need combat shotguns anymore.

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
K E K
E 
K

**Comment by Super3222** [comment]
I'm not sure if this is necessary. I believe it was meant to be hard to get so people don't generally get it.

Don't forget that combat level 5 is easy to get within the first 5-6 minutes of the round if you know what you are doing, and this is coming from experience.

Discussion should be made before we let any scientist jump into anywhere they wanna go with portal guns.

**Comment by ShadowDeath6** [comment]
It's not like combat 6 is hard to get, it's mainly materials that are the problem, since miners LITERALLY NEVER DO ANYTHING EVER WITHOUT DRONES

**Comment by ghost** [comment]
TOO STRONG.

**Comment by ShadowDeath6** [comment]
Alternate way to do this is to make the experimentor less awful

**Comment by DavidEdwards** [comment]
I don't think this is necessary - but open to thoughts.

**Comment by Wardog390** [comment]
10/10 never see portal guns ever made plz nerf.

**Comment by ShadowDeath6** [comment]
> be R&D
> Get full research levels
> Get combat 6 with bullshit experimentor
> Never get materials
> Never get portalgun
> Suffer eternally

**Comment by oisin100** [comment]
I always see Scientists finishing R&D but not having Combat 6 because either no one authorizes it for them, it gets stolen or sec bumrushes them for ordering it. And even once they get to Combat 6 they might not even have miners to get the materials required to make it.

Ok, If on the rare occasion all that happens now they need a firing pin from security if they want the gun to actually work somewhere other than testing range.
You cant even use the gun to break into areas as the gun doesent shoot through walls or windows. Sure you could space people with it hard to actually hit a moving target unless its chasing you.

**Comment by ghost** [comment]
Nope.

Alright, let's go into this.

With the advent of miner drones, scientists are getting minerals a lot more. A LOT more.

As in, not minerals every round, but minerals at least every two or three rounds.

Let's consider how absurdly powerful the portal gun is.

firstly, Oisin, it CAN shoot through windows. Not walls, but windows.  Anywhere with a window, you can enter easily, and at range.

Secondly, in case you forget, it has no delay to the portalling and portals can be set where you want. Firing one portal into space and another into escape and spraying some lube is a very easy way to space up to ten people.

It takes a little finagling, but the portal gun is easily one of the most powerful and lethal weapons in the game.

It does not need a firing pin to fire and has infinite ammunition. Setting up a portal into somewhere far away from you, or into space, and opening another one in the path of a pursuer means that that person is more fucked than a prostitute on mardi gras. They're in space or halfway across the station, GG.

Not to mention, since it can pass through windows, you can warp right into the AI upload, into the bridge, the armory... Anywhere a person can see through, they can shoot into and warp into.

You can easily depopulate an entire department with the portal gun with a little planning and forethought. 

There is a REASON guns this powerful are gated behind combat 6. Accessibility is not a good thing. It is NOT a good thing.

There is a reason powerful weapons and gear are gated behind high levels and almost never seen-science getting xrays every round would fucking SUCK, and holding a teleporter beacon inhand while using the teleporter gun and a hand tele means it's just like old telescience with a little coordination, except you can specifically choose where you want to hand tele to, warp the little rest of the distance, and give tsci unlimited access there.

So no.

Keep this combat 6 locked. There is a reason powerful weapons and guns are not seen every round and making the portal gun easily accessible for the bare minimum of work-combat 5, which can be gotten in MINUTES-is absolutely imbecilic.

**Comment by oisin100** [comment]
Ehh, What adam has just said has changed my mind. Fuck lowering the price.

**Pull request closed without merging**
