### PR TITLE
Shadowpeople excluded from mutation toxin blacklist

### PR DESCRIPTION
**Pull request by Super3222**
#343

Simple really, it gives a chance for mutation toxin to turn you into a shadowperson.

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
I love you :')

**Comment by ghost** [comment]
Readd to blacklist.

Mutation toxin giving people species that kill them is a bad thing and was removed for a reason.

DNM.

**Comment by ShadowDeath6** [comment]
Shadowperson behaves the exact same way in light as plant people do in dark. Xenobio needs more fun shit.

**Comment by X-TheDark** [comment]
Funny thing is that plasmamen is still something you can actually get, despite it supposedly being blacklisted.

**Pull request merged**
