### PR TITLE
Shadowling targeting changes

### PR DESCRIPTION
**Pull request by MacHac**
For realsies this time
### Intent of Pull Request

Shadowlings will no longer attempt to target simple animals or allies with spells that cannot be targeted by simple animals or allies.

### CODE REVIEW

**Comment by MacHac** [comment]
I can't deal with this right now.

**Comment by Time-Green** [comment]
Thank god. So many times I want to glare someone, and I get a a list of 10 people

**Comment by MacHac** [comment]
This won't actually fix that.  If you have 10 people within range, you will still get a list of 10 people.  This fixes you having to choose if you want to glare at the mouse in a tense ambush scenario.

**Comment by ShadowDeath6** [comment]
> go to xenobio
> try to glare the xenobio
> entire screen fills with slimes
> xenobio bails out

thanks for fixing this shit :')

**Comment by DavidEdwards** [comment]
Not familiar with Shadowlings. Can someone else familiar with Shadowlings check this over?

**Comment by oisin100** [comment]
Thank god. ive lost enough sling rounds to this.

**Comment by DavidEdwards** [comment]
No responses to this. I am assuming it is fine.

**Pull request merged**
