### PR TITLE
RE: Tool tip port

### PR DESCRIPTION
**Pull request by Super3222**
#201 RE pull request for testing.

### CODE REVIEW

**Comment by DavidEdwards** [comment]
Cheers

**Comment by DavidEdwards** [comment]
Do you need to activate anything to get the tooltips to work? Did a couple of minutes of testing just now. Found no tooltips.

**Comment by Super3222** [comment]
You need to hover your mouse over an alert.
Alerts are indicators of changes towards your mob and it's environment. Like if you have no oxygen, too much oxygen, if you are blind or not, breathing in plasma, or if you are in a weightless environment.

**Comment by Super3222** [comment]
@DavidEdwards, are you still having problems getting the tooltip up?

**Comment by DavidEdwards** [comment]
Ahh I see. I was attempting to get a tooltip over the "normal" icons. I had
no alerts. I'll test again ASAP.

**Pull request merged**
