### PR TITLE
Radiation Crossbow (Radbow)

### PR DESCRIPTION
**Pull request by ShadowDeath6**
Refer to issue #835 .
### Intent of your Pull Request

The tweak that nobody asked for.

Ports https://github.com/tgstation/-tg-station/pull/15213 by @xxalpha, which makes energy crossbows and kinetic accelerators automatically recharge.

Changes damage on ebows, causing it to actually do a good amount of damage as an actual weapon. 

However, it loses its 5 tick weaken in replacement for a 1 tick stun, which is effectively a disarm. 
Combo cafe is officially kill.

Hopefully this isn't wildly overpowered due to its rad damage, but people actually start collapsing from it at around 4 hits, which seems balanced enough. 

Also renames "mini energy crossbow" to "mini radiation crossbow" and fixes description accordingly.

### CODE REVIEW

**Comment by ParagonPrime** [comment]
If nothing else, KE autorecharge is a well-needed blessing.

**Comment by ParagonPrime** [comment]
If nothing else, KA autorecharge is a well-needed blessing.

**Comment by TheSadFox** [comment]
> > Propose it
> > The tweak that nobody asked for.
> > I'm nobody
> > ;_;

Looks good. If it turns out too weak, can always play around with irradiation level. 

Big :+1:  on porting the autocharge PR.

I am way too lazy to check this myself, how does the damage from radiation look like? Is it actually noticeable after 2~ shots?

**Comment by ShadowDeath6** [comment]
It doesn't actually start showing up that much till the fourth shot because of the way radiation works.

**Comment by ghost** [comment]
Since it's mostly silent this would be good for firing in dark spaces without getting noticed, or in a crowd if you're fast. Rad + disarm = p gud.

**Comment by TheSadFox** [comment]
Breaks lights, hunt people with thermals and radbow.

**Comment by ShadowDeath6** [comment]
After I run some more tests on its effectiveness it'll be ready to merge. 

Stunlocking with radbow, yes or no? It makes it a lot more lethal but might still allow for esword bullshitting.

**Comment by ShadowDeath6** [comment]
After some testing, yes, radbow can stunlock if you immediately shoot upon recharge.

**Comment by TheSadFox** [comment]
Maybe revert back to weaken=1 but add a confusion ala flash to it? It would still result in people being fucked, but at least give them some small, tiny chance to fight back?

**Comment by ShadowDeath6** [comment]
Merge ready, it seems pretty balanced.

**Pull request merged**
