### PR TITLE
adds newbrig

### PR DESCRIPTION
**Pull request by utahclock**
adds new brig layout

### CODE REVIEW

**Comment by Super3222** [comment]
@utahclock 
Screenshots?

**Comment by oisin100** [comment]
Looks pretty good!

**Comment by ToGWtF** [comment]
:+1:

**Comment by matskuman5** [comment]
Morgue is too big, the hallway in the middle after the cells is a bit strange (maybe add something there) otherwise it's perfect, I love the amount of new cells, eastern part of it looks great.

**Comment by DavidEdwards** [comment]
Mimicing oisin, this looks pretty good! We definitely need comments from the more robust community.

Since this is an overhaul of a critical area of the ship, does it look to be conducive to good round play?

Do traitors have any kind of possibilities for !FUN!. Etc.

**Comment by Keekenox** [comment]
It seems so big

**Comment by Keekenox** [comment]
Also now you can't seem to get into perma via cutting through the RWall from labour dock, which is a great tator strat

**Comment by FluffySurvivor** [comment]
looting the equipment lockers room is extremely easy now from maint, not even rwalled

**Comment by Time-Green** [comment]
I really love it.
Buuut' I agree with fluffy

**Pull request closed without merging**
