### PR TITLE
RE: Ports /tg/'s elite hardsuits.

### PR DESCRIPTION
**Pull request by Super3222**
Refer to issue #1011.
### Intent of your Pull Request

Adds the elite hardsuits.
Replaces them for the other ones (so this will cost 8 TC). Information at the issue to refer to.

@TheNightingale - Created this.
[Intial PR](https://github.com/tgstation/-tg-station/pull/13024)
#### Changelog

:cl:Super3222
rscadd: The Syndicate has developed a newer, more elite version of their blood-red hardsuit which is ultimately designed to not only bring fear to Nanotrasen but to crush them in every will to stop the operative behind the armor.
rscadd: The elite syndicate hardsuit has been ported from /tg/, credits to TheNightingale. 
rscadd: The Elite Syndicate hardsuit is also available to nuclear operatives for 8 TC.
rscdel: You can no longer buy more blood-red hardsuits with your uplink during nuclear operatives mode.
/:cl:

elitenukeop

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
Also does this replace tator nukeop hardsuit as well

**Comment by Super3222** [comment]
No, this'll replace the blood-red hardsuit in the nukeop uplink.

**Comment by oisin100** [comment]
Unless anyone has any more additional feedback ill merge this tomorrow.

**Comment by ghost** [comment]
Remember it's fireproof too - you can combine it with flamethrowers for a cheap and effective area denial weapon (unless you set fire to the rest of your team). Alternatively, throw in adrenals and an energy shield and be the team's juggernaut. Operatives in elite hardsuits are quite resistant to all types of damage - they can take four more fire axe hits than the rest of the team, for example, and are down for less time after being tased.
The best way to deal with them is either overwhelming firepower (shotgun slugs, requiring 5 shots at 24 damage each, or sustained laser fire, 10 shots at 10 damage each) or stun weaponry; even with 60/60/50, they're not invincible, and if they don't have adrenals, it's not too hard to outmanouvre them and land a stunbaton, .38 or taser hit, then empty a laser gun into them.

**Pull request merged**
