### PR TITLE
Lowers the price of Gang Implants

### PR DESCRIPTION
**Pull request by ToGWtF**
Refer to issue #728 
### Intent of your Pull Request

Lowers the price so its more viable to buy them and actually use them.
Hopefully makes murdering high-profile enemy gangsters less common and
converting them to your cause more common.

### CODE REVIEW

**Comment by Super3222** [comment]
You need a changelog as well buddy

**Comment by ToGWtF** [comment]
still need input on the issue page

**Comment by DavidEdwards** [comment]
I am fine with this. Needs a changelog though.

**Comment by ToGWtF** [comment]
@DavidEdwards    Can merge now

**Pull request merged**
