### PR TITLE
[Ready]  Gang Gameplay Update

### PR DESCRIPTION
**Pull request by FluffySurvivor**
Gang is supposed to be by excellence a guns FFA team deathmatch. Unfortunately, the core mechanics of the gamemode were left relatively meaningless (tagging and wearing special outfits) and thus gang was not that different from other gamemodes because guns were very expensive. It's dumb when only one person manages to afford an uzi the whole round, so I adressed that. Now, everything revolves around spraying and wearing the gang uniform. Giving your gangsters guns is now way more affordable and the _only_ way to succeed.

**Guns**
Reducing the Uzi's cost, adding the Tommy Gun.

_Uzi_
Cost: 60 --> 40 Influence
Bullet damage: 20-->15
Ammo cost:  40-->15 Influence

 _Thompson SMG_
Cost: 60 Influence
Bullet damage: 18
Fire modes : semi-automatic or 3-round burst.
Weight class : 4 (can be placed in armor storage but cannot fit in backpacks)
Magazine: caliber .45,  50 rounds drum
Ammo cost: 20 Influence

**Sleeping Carp changes**
With guns being cheaper and better, these guys needed some love.

new _Throwing Stars Box_
-Contains 5 deadly stars
Cost: 50 Influence

_Sleeping Carp Scroll_
Cost: 30-->25

_Wrestling Belt_
Cost: 20-->15

**Equipment**
_Gang outfit_
This IS the second core item of the gamemode. If you wear this, you'll have a much higher chance of surviving shoot-outs, while greatly contributing to the gang's influence income.
Bullet resistance: 30-->35

_C4 Explosive Charge_ 
Cost: 10-->5 Influence
More explosions !

_Spraycan_
Consolidating the position of the core gang item.
Cost: 5-->3

**Gang communication**
The name of gang bosses and lieutenants is now displayed in gang chat.

**Influence income**
Base income each turn: 15-->3
Influence scaling for territories and gangsters with outfits massively increased.

**Gang pen improvements**
#1019 You can now check for gang/implant status even when the cooldown is on. ///THIS CURRENTLY DOES NOT WORK (and I need help here) **/////DROPPED**
#898 Gangsters can use gang pens to check antag/implant status without being able to convert. ///NOT YET DONE **/////DROPPED**

Notes:
I kicked the c20r out of its ammo type to allow room for balancing the tommy gun, the c20r has no functional changes.
The l6 saw MG now fires in a 3 rnd burst instead of 5(way overkill). (unrelated, I know, but a really quick and easy fix doesn't hurt)

Changelog later. 
Do not merge tag pls. 

UPDATE : 
Uzi cost increased to 45 from 40 (live value: 60)
Uzi damage increased to 17 from 15. (live value: 20)
Tommy gun cost increased to 65 from 60.
Tommy damage increased to 20 from 18.
Gangtools and spraycans are now more obvious upon examination.
You can now use gang comms even when outside the station Z level.
Wrestling belt removed ( reason: it was pretty strong but totally RNG based, a next step in the fight against combat RNG)
Dope bling (/tg/ port- https://github.com/tgstation/-tg-station/pull/13724 by @PKPenguin321 ) added.
Gang outfit influence scaling per member increased further.
Fixed stuff that was included in the notes but wasn't changed code-wise.

UPDATE 2:
You can now see the gang you belong to in your notes, is removed upon deconversion.
Gangtools now only beep for the user.
Renamed the recaller.dm file to gang_tool.dm (which is more suggestive)
Gang outfits can now hold uzis and tommy guns.

:cl: FluffySurvivor
rscadd: Gang has received several changes that are aimed at accentuating the core identities of the the gamemode: using gang outfits, tagging territory and being a pure team deathmatch. Some various quality of life improvements as well. 
tweak: Uzi cost reduced to 45 from 60. Ammo cost reduced to 20 from 40.
tweak: Uzi bullet damage reduced to 17 from 20.
rscadd: Adds the Thompson SMG, uses .45 calibre drum, holding 50 rounds. Can either fire in a 3-round burst or semiautomatic mode. Bullet damage is 20. Costs 80 Influence, while ammo costs 25.
tweak: C4 cost reduced to 5 from 10.
tweak: Spraycan cost reduced to 3 from 5.
rscdel: Sleeping Carp Wrestling belt removed.
rscadd: Adds Throwing Stars boxes exclusive for the Sleeping Carp, available for 50 influence.
tweak: Sleeping Carp Martial Arts Scroll cost reduced to 25 from 30.
rscadd: Adds a dope necklace, purchasable for 1 influence. (/tg/ port)
tweak: Base influence income reduced to 3 from 15
tweak: Starting influence increased to 25 from 15.
tweak: Influence scaling based on gangsters with outfits and territories massively increased.
tweak: You can now see the gang you belong to in your notes.
rscdel: Gangtools now only beep for the user.
rscadd: You can now see the name of lieutenants and bosses in gang chat.
rscadd: You can now use gang comms outside the station Z-level.
tweak: Gang tools and spraycans are now more obvious upon examination.
rscadd: Gang outfits can now hold tommy guns and uzis.
tweak: Gang outfits now have slightly more laser and bullet armor.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Nice work so far.

**Comment by ghost** [comment]
I disagree with tommygun and UZI.

Now.

Let's move on- a few more things you can add.

On /tg/, gangsters can buy gold chains for 1 influ. They're just neat cosmetics-might want to port that.

Also on /tg/, sleeping carp scroll grants complete immunity to all ranged attacks-I advise porting that, and it'll be worth the high 60 influence cost.

Wrestling belt is also complete trash, so replace it with something (bo staff, throwing star kit, sleeping scroll rather than sleeping carp to be only gang with 4 items) until an actual wrestling moveset (a la goon) can be implemented.

**Comment by ShadowDeath6** [comment]
Tommy guns shoot 5 rounds and crit in 3 hits. 
Unless it's 1000 influence, no.

**Comment by FluffySurvivor** [comment]
> tommy guns shoot 5 rounds and crit in 3 hits

Bro do u even read. It takes 6 bullets to crit someone, and you can't even place it in your backpack.

**Comment by ShadowDeath6** [comment]
Just remove tommygun and buff uzi if it really is that shitty, guns are not the problem in gang though

**Comment by FluffySurvivor** [comment]
After a lot of testing, the current iteration seems quite balanced. Of course, fiddling with 5 combat vars is very difficult and it's hard to determine an optimal setup without extensive live testing. 

@AdamElTablawy spending 60 points for PASSIVE IMMUNITY to ranged attacks is completely worth it and would become meta EVERY round. They would just stay out of range forever and kite, becoming unkillable. It's a horribly unbalanced idea.

**Comment by ghost** [comment]
They can't use ranged weapons tho, only melee, so they're forced into stunbaton range

**Comment by Groudonmaster** [comment]
How about we add a radio chip costing 3 influence to allow quick communication with other gang members since half the time that's the biggest issue a gang encounters is lack of communication.

{Gang name} encryption chip
Influence: 3
Requires a gang member to plant a communications relay somewhere for it to be usable
Suspicious communication relay
Influence: 20
IS NOT METASHIELDED.

**Comment by ghost** [comment]
nothing in gang is metashielded

if you shift click a spraycan it's suspicious paint the suspicious device isn't metashielded if you look at the flashing gang pen it's gang even the jumpsuits are on examine gang

**Comment by FluffySurvivor** [comment]
> it's suspicious paint so not metashielded
> yet claims suspicious toolboxes are metashielded

**Comment by ShadowDeath6** [comment]
Suspicious toolbox is just a black toolbox

**Comment by ghost** [comment]
sus toolboxes can be gotten from derilect or mining and it's literally a toolbox

**Comment by FluffySurvivor** [comment]
More feedback on tommy gun pls.

**Comment by Kmc2000** [comment]
I'm working with super and tog for more gang stuff, if you want some icons lemme know

**Comment by Super3222** [comment]
> KMC not linking his own issue that he's refrencing.

HGYBN MN B NBV BBV NBN MNB 
(bashing my head against my keyboard)

#865

**Comment by FluffySurvivor** [comment]
I am doing the (hotline) bling. 
Gang rulez.

**Comment by ToGWtF** [comment]
@Kmc2000 @FluffySurvivor   I got brass knuckles done. Going to work on a baseball bat, works like bostaff but has increased damage to offset its lack of disarmintentinstastunbullshit. gang individuality so no more buypistol>>win

**Comment by FluffySurvivor** [comment]
Updates, read the main post.

**Comment by PKPenguin321** [comment]
I've no comment on the rest of this PR but I assure you dope bling really brings gang mode up to 100%, you've made the right decision by porting it :wink:

**Comment by ghost** [comment]
okay but so here's an idea

specific gangs should start with specific items available, in the way sleeping carp does

also smoking a blunt should grant an influence boost

**Comment by ShadowDeath6** [comment]
> encouraging drug use

I'm calling the police

**Comment by FluffySurvivor** [comment]
any additional comments?

**Comment by ghost** [comment]
yeah actually

smoking blunts increase influence gain

Also, I do sort of want to emphasize the gang vs gang part of, well, gang, and security needs to be a smaller part of gang. Either give gang jumpsuits some energy resistance or make gang implanters gang on implanting. It's supposed to be antag VS antag, and it's usually security VS one gang.

**Comment by FluffySurvivor** [comment]
Gangs got buffed while security stays the same. 

Gangs will be stronger vs sec. I can see upping the laser resistance on outfits a bit tho. 

and no smoking, you need to fight for influence, not get it for free or for memes

**Comment by ghost** [comment]
> not encouraging weed-smoking gangsters in gold chains running around shouting YO DOG WHAT UP IN THE HIZZLE' for influence

**Comment by FluffySurvivor** [comment]
yeah and then a security officer stumbles upon you and arrests you then he gets banned

**Comment by ShadowDeath6** [comment]
Remove tommygun and I'll support it

**Comment by FluffySurvivor** [comment]
give me a reason to

**Comment by ShadowDeath6** [comment]
Unless you've lowered the firing speed, this will crit in a few seconds tops due to its insane DPS and will be a bitch to fight because it fires so quickly. And if I'm reading the OP right, you're making it as cheap as current uzis are? That means a gang leader that isn't retarded (gang leaders include LTs, meaning 3 of them) will have one on them at all times, making firepower extremely unbalanced in favor of the gangs.

**Comment by FluffySurvivor** [comment]
dude what are you saying

the firing speed was lowered, it's now standard like all the non-admin bus guns

To counter the damage, you wear outfits. And I don't understand what you mean by making firepower extremely in favor of gangs, the gamemode is SUPPOSED to be gang vs gang. Do you mean that security becomes weak? They are never weak, well played security stomps every antag no matter what. They also have 80% bullet resistance armor. 

And I clearly stated it costs 65.

**Comment by ShadowDeath6** [comment]
Security only has three 80% bullet blocking armor suits, less if gangs raid armory, and having the same firing speed as a c20r is still more lethal than I'd prefer. The most I can see happening is one ganger with an SMG running into the other gang, shitting on everyone with 20 damage bullets, then getting disarmed and killed with his own gun. I'd prefer it stay admin-only.

**Comment by FluffySurvivor** [comment]
> The most I can see happening is one ganger with an SMG running into the other gang, shitting on everyone with 20 damage bullets, then getting disarmed and killed with his own gun

-learn to dodge 
-learn to wear outfits
-learn that one dude trolling team antags happens in every gamemode and it's not an excuse to deny new features or balance changes

**Comment by ShadowDeath6** [comment]
Learn to dodge shots that move as fast as c20r bullets xdddd

**Comment by ghost** [comment]
Tommyguns were originally part of gang and weaker than they are in fluffy's PR. They were still overpowered and removed as a result.

It's hard to dodge spammable ballistic weapons with a high clip-you can dodge a revolver if you see someone's already drawn one as it only has 6 shots and juking around will make them miss. The tommygun is significantly harder to evade as the hard to see ballistic shots are very fast, and come out in fucking groups with a high clip. One gangster with a tommygun can mow down multiple people even if they're security through spam and high dps-three will likely clear out an entire gang. 

Armor is also insignificant-the high fire rate and bullet clusters mean that the bullets will hit multiple times for low damage, instead of one for high damage. Compare the revolver to the cr-20 for nukeops on bulletproof armor-the high power revolver shot will be stopped by the armor and do medium damage with a slow fire rate, the cr-20 will fire multiple low damage shots that will shred the armor. The same thing applies here-even if wearing gang armor and bulletproof vests, it'll afford an extra second of actual survivability, and the armor won't help against the stamina damage at all-sometimes armor makes it worse-and you get to lie on the floor stunned for one extra second.

Yes a taser will win vs the tommygun if you're in gang armor and bulletproof armor and manage to land your first shot, but in general the tommygun will sweep in a 1v1, and in a clusterfuck firefight for the dominator, the tommygun is going to absolutely obliterate multiple people as everyone is busy fighting and can't land a clear shot.

The uzi is balanced as it is in your PR, so please leave it and drop the tommygun-or make the tommygun the expensive replacement for the uzi for one gang and one gang only so that we can have some actual gang-specific items.

**Comment by FluffySurvivor** [comment]
Thank you for your good points Adam. 

What I am considering:
- Upping the tommy cost to 80-85 so only VERY influent gangs can afford it, also making the guy wielding it an important tactical asset, because if he goes down you lose a lot of firepower. We can always nerf/buff it afterwards. 
- Making it unique for one gang, as you suggested, the issue here is that it may prove difficult to balance in comparison to other gangs in the future. 

I am strongly leaning for the former tho. And btw tommys have no stam damage. 
@AdamElTablawy

**Comment by FluffySurvivor** [comment]
Tommy is now 80.
Ammo cost increased to 25

**Comment by FluffySurvivor** [comment]
@Oisin100
@DavidEdwards 
Merge to make gang more fun with much more amazing gang fights when

**Comment by oisin100** [comment]
@AdamElTablawy What do you think about the new nerfs? Ill merge this tomorrow unless you have anything else left to say.

**Comment by FluffySurvivor** [comment]
Minor adjustment, increased starting influence so gangs don't start weaker than intended.

**Comment by Robertruler77** [comment]
Maybe cap the number of Tommys if it's still op. 

Sad fact of the current meta is if you don't get ganged and a Dom goes down, just hide. You'll be shot to shit no matter who you are and what your intentions are. Even after the Dom blows this is the case, feels like. 

Maybe add a high costing but very late game thing that allows you to see if a crewman has an alligence (maybe not specify on his if they're your gang their gang or sec) but then again if it's too low it becomes the meta over sec Huds and too high means never bought.

Just an idea so le always in robotics roboticist doesn't always get cucked for not leaving and getting ganged in the first 20 mins cause they have shit to do.

**Pull request merged**
