### PR TITLE
Adds new Changeling ability, biodegrade!

### PR DESCRIPTION
**Pull request by ShadowDeath6**
Refer to issue #848 .
### Intent of your Pull Request

Adds biodegrade, letting lings have a chance at breaking out of cuffs when abducted / cuffed by security / cuffed by anyone else. Also adds being able to resist out of straitjackets, if that wasn't a thing before.

### CODE REVIEW

**Comment by Cruix** [comment]
:+1: death to specific checks. But you really should have made two separate PRs.
EDIT: upon further review, the two new features are interdependent enough that it makes sense for them to be in one PR.

**Comment by Cruix** [comment]
Oops I closed it disregard.

**Comment by ShadowDeath6** [comment]
Two seperate PRs for what?

**Comment by Super3222** [comment]
This will be hell to get through ingame.

Hopefully lings won't mind getting their skulls caved in by harmbattons and ending up fully stripped enclosed in the middle of walls in an unknown area.

**Comment by ShadowDeath6** [comment]
Same thing happens with lesser form.

**Comment by FluffySurvivor** [comment]
No. Cuffs ARE supposed to be mostly a gg no re. Making an ez counter ability to that is duuuuumb. 

You can already adrenal when you get stunned, lesser form etc etc. 

Lings don't need to be spoonfed. 

OR if you do it, make it cost 65 chems so you can't fleshmend/adrenal afterwards

**Comment by ShadowDeath6** [comment]
Keep in mind you can only use fleshmend/adrenals with biodegrade once before waiting the however long time it takes to regenerate 30 chemicals and you can just get stun/tased again while your biodegrade is melting your restraints.

**Comment by ghost** [comment]
It takes 1 minute to melt restraints.

If sec can't beat you to death, remove the melting cuffs and put new ones on in a minute you deserve to get free.

Also it reveals you're a changeling without letting you actually run away immediately, unlike lesser form, so.

**Comment by ShadowDeath6** [comment]
It actually takes like 5 seconds, adam, 1 minute is regular resist

**Comment by FluffySurvivor** [comment]
wait it's not instant? 

this actually takes skill to use as you need to foresee where you will be 1 minute later and if you can rely on the moment

yeah i am fine with it. 

Edit: dont make it 5 seconds make it 1 minute so it's not a brainless "lol ez i got away" ability

**Comment by ghost** [comment]
Make it 5 seconds for cable cuffs, 10 seconds for zipties and 17 seconds for handcuffs.

Make it for straightjackets and lockers 2 minutes.

**Comment by ShadowDeath6** [comment]
I'd like to keep it as-is since a giant "HEY LOOK AT ME I'M A LING" and -30 points is balanced enough, and stunning the person twice is enough to negate any chance they have at escape. 
(Also definitely not because I have no idea how breakout time is determined with the ability)

**Comment by ghost** [comment]
Then close this, as it's just a superior version of lesser form with you blindstinging the officer, melting your cuffs and strolling off.

**Comment by DavidEdwards** [comment]
Any additional comments? Seems possibly controversial.

**Comment by Super3222** [comment]
I agree with adam. It shouldn't be a 

> "HEY LOOK AT ME I'M A LING"

Because lesser form already covers that type of tactic. Regardless, if suddenly the cuffs dissapear off someone, a security officers next action should be bashing them with the ol' harmbaton. Just like with a freedom implant, risky.

**Comment by FluffySurvivor** [comment]
Close it, too unbalanced in its current form.

**Comment by ShadowDeath6** [comment]
I fixed it, cool. 
Fleshmend and adrenaline now have genetic damage requirements so you can't use them IMMEDIATELY after biodegrade. I also increased the genetic damage done by biodegrade a bit.

ALSO- I increased the time it takes to corrode out of things by quite a bit.

**Comment by FluffySurvivor** [comment]
> can't murderbone medical as freshcloned ling because no adrenals/heal

no

**Comment by ShadowDeath6** [comment]
Does cloning do genetic damage to the ling? I don't think it does.

**Comment by FluffySurvivor** [comment]
Genetic damage aka cloneloss.

**Comment by ShadowDeath6** [comment]
That isn't genetic damage. Lings have a var for genetic damage to prevent ability spam.

**Comment by ShadowDeath6** [comment]
Well I don't think this is gonna go anywhere. Feel free to open it back up if you feel like it's balanced after my most recent change.

**Pull request closed without merging**
