### PR TITLE
Disables editing of sound related variables unless admin has +SOUND.

### PR DESCRIPTION
**Pull request by AsV9**
There are probably more abusable variables but this has got to do for now.

### CODE REVIEW

**Comment by Wardog390** [comment]
i take it your making sure only +SOUND can counter this line of code?

**Comment by AsV9** [comment]
Currently nobody. I could do that though.

**Comment by AsV9** [comment]
Voila.

**Comment by Wardog390** [comment]
seeing as we are sucking all the fun, you might as well spend the time looking up sounds that can be changed in VV and limiting those, getting +SOUND has to be worth it.

**Comment by AsV9** [comment]
To be honest nobody should be touching things they're not supposed to touch. That shouldn't be too much to ask for.

**Pull request merged**
