### PR TITLE
Adds supply crates for tesla

### PR DESCRIPTION
**Pull request by Time-Green**
+Tesla Generator Crate (10 Points)
+Tesla Collector Crate (20 points)

### CODE REVIEW

**Comment by Time-Green** [comment]
Those were very much necessary. So I added them.
I'll probably making more PR's like this with things that are needed, but does not get attention.

**Comment by oisin100** [comment]
Uhm, You managed to get your preference PR mixed in with this one...

**Comment by Time-Green** [comment]
Oh what the hell...
How do I fix that?
Nevermind I think that did it

**Comment by ShadowDeath6** [comment]
How much does the singlo generator cost? I don't think it's 10 points.

**Comment by Time-Green** [comment]
It is 10 points

**Pull request merged**
