### PR TITLE
Mindslave implant

### PR DESCRIPTION
**Pull request by oisin100**
Created the Mindslave implant as requested here:[Forums](http://forums.yogstation.net/index.php?threads/mindcontrol-implant.6641)

Currently the mindslave implant costs 12 TC.

The mindslave implant will cause whoever is implanted with it to become the implanters slave! You cant implant people with loyalty implants but you can implant anyone else including other traitors! once someone is implanted they are given the objective "Serve <Their Master> no matter what!" and are added to the list of traitors for that round so that they are revealed at round end results.

When the implant gets removed(EG, Via surgery) then the slave gets is told "You feel as if you have just been released from eternal slavery. Yet you cant seem to remember anything at all!" and their serve objectives are removed. If they have no objectives left then they are removed from the round traitor list.

Please criticize and provide salt for our pretzels!

### CODE REVIEW

**Comment by Super3222** [comment]
Are you sure surgery should be the only way to remove it or should a loyalty implant be able to override it?

If surgery is the only way to get rid of it completely and loyalty implants won't stop them from serving their masters, would the slaves resist loyalty implants like revheads?

I also love the duo bundle.

**Comment by oisin100** [comment]
Its super easy to remove implants with surgery... But maybe i should make it so you can be implanted with loyalty implants whilst your under the influence of the mindslave... As i was kind of thinking the mindslave implant was a kind of Syndicate Loyalty implant so maybe they should both cancel each other out or something?

**Comment by Xantam-13** [comment]
This feels good from an RP perspective. Just have to ensure the player who is slaved actually obliges.

**Comment by oisin100** [comment]
Yea... I cant really think of what i could add to make them do that... Maybe give the slave owner a remote to blow up their slaves or something...

**Comment by Xantam-13** [comment]
I like that. Could you perhaps adapt the explosive PDA cartridge and remodel it  for this purpose?

**Comment by oisin100** [comment]
"Adapt" the detomatix cartridge for this? Not sure what you mean hardy... I can make something like the detomatix cartridge though. I assume that what your trying to say is that you will get a cartridge what you can put into your PDA to blow your slaves up?

**Comment by Xantam-13** [comment]
Yeah. Like use the same principle. Insert a cartridge and use PDA to blow slaves up. But should of course remain independant from detomax.

**Comment by oisin100** [comment]
Alright, Will do! Should be done by some time tommorow!

**Comment by ghost** [comment]
The only thing necessary to keep implanted players in line is admins.

Just like nothing is stopping cultists from murdering other cultists but admins, disobeying your implanter should be bannable.

Make sure to adminlog it and make the implantee visible on check-antags so that admins can actually see if someone's mindslave implanted.

**Comment by Groudonmaster** [comment]
Or we could make an rp perspective and allow slaves to martyr to sell out their master

**Comment by ghost** [comment]
NO

A traitor item that you can use but on the other hand the slave IMMEDIATELY goes and rats out their master?

Are you shitting me?

That'd make it so useless it might as well just be 0 TC and come free.

That's so fucking retarded. Like no not even I'm actually mad now that's so dumb of a suggestion. No.

No.

NO.

**Comment by oisin100** [comment]
Uhm what groudon?

Implants can be seen in the attack log but i can send a message to the admins if you like with something like "ByondKey/(IC name) Enslaved ByondKey/(IC name) with the Mindslave implant"

**Comment by oisin100** [comment]
Sorry bout the large amount of commits... My git has kinda gone a bit weird and its not including some changes... 

But yes, You can now use the Slavemaster pack to detonate your slaves. Its maxed at 1 slave per pack because im lazy.. Ill change this in a bit... 

Slaves blow up with a 1, 2, 3, 3 explosion.

The Duo pack doesent have a Slavemaster pack yet... Im not sure if i should give it one or not.

**Comment by Groudonmaster** [comment]
It's called RP adam >.>  You can't hold your antag's hand the whole time.  If they want to take a risk with a slave and a slave is willing to die for the cause why shouldn't they be able to?  It's different from cultists or revs because they're brainwashed.  The way this works it's basically obey or get your head blown off.

**Comment by ghost** [comment]
RP should not determine if it functions or not. If you make an item 12 TC but someone feels buttmad anyway and goes to disobey and explodes OR tries to kill their implanter before they can blow them up that's a waste of 12 TC and nobody will ever buy the item because it's shit.

Making items that are RP dependent is the stupidest fucking idea I have ever heard. It's not hand holding when the item is literally called a fucking MIND SLAVE implant.

Because they are ENSLAVED.

They are FORCED TO OBEY. 

It's EXACTLY like rev or cultists and making it a worthless 12 TC piece of SHIT that has no guarantee it'll work at all and won't just have your implanter SCREAMING your name into public comms and getting autocloned immediately because they were a fucking precloned scientist and having the AI shove twelve fucking secborgs into your asshole is the worst idea I have ever heard.

No.

There's no fucking 'im willing to die for the cause'  because that's RETARDED for the same reason revs and cultists and gangs can't fucking disobey because it is a MIND SLAVE implant. 

Rp should have NOTHING TO DO WITH THIS because more often on yogstation RP is just an excuse to grief and then say 'wELL MUH CHARACTER DIDNT KNOW LOL'.

We are NOT baystation. We do not give traitors a twelve TC item that can very well COMPLETELY DICK THEM OVER AND RUIN THEIR ROUND because the mindslaved guy just screamed into public comms that they were mindslaved, stun their implanter and beat them to fucking death on the spot before they can blow them up or even if they did blow them up kill their master in the process.

**Comment by oisin100** [comment]
Gotta agree with Adam... 
If this was left to RP and RP alone there would be no point in it as you could just take chem implants from brig or order them from cargo if you wanted to be able to "threaten" someone that you would kill them if they didn't obey you.

**Comment by Super3222** [comment]
If you are reading this comment, it will be deleted soon!

**Comment by Super3222** [comment]
You see, you can definitely RP with someone and turn them into your slave by bargaining over a brief case full of space cash for 1 TC.

But to make them a valid slave for 12 TC should be forced like rev and cultist.

**Comment by oisin100** [comment]
Removing [WIP] Its pretty much done code-wise it could probably do with some more testing and someone else having a look at the code as I probably missed something obvious.

**Pull request merged**
