### PR TITLE
Fixes blob health

### PR DESCRIPTION
**Pull request by X-TheDark**
Refer to issue #696.
### Intent of your Pull Request

Fixes blob taking too much damage from brute as well as fire. The resists have been modified in accordance to the new take_damage() damage calculations.

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
I'm not too educated on how resistances work, will this make it as they were before the update?

**Comment by X-TheDark** [comment]
Yes, this merely converts them to the new format, nothing else.

**Comment by ShadowDeath6** [comment]
:+1: x :100:

**Comment by ShadowDeath6** [comment]
**pls speedmerge blob needs fixing**

**Pull request merged**
