### PR TITLE
Adds Icon for Yogstation Specific Ghost for Donators

### PR DESCRIPTION
**Pull request by utahclock**
Yogstation donator ghost.

### CODE REVIEW

**Comment by AsV9** [comment]
Also I'm 99% sure the conflict is in the changelog file as that file doesn't exist on the dev branch anymore.

**Comment by Alek2ander** [comment]
P A Y 2 W I N

**Comment by DavidEdwards** [comment]
Looks fun, you should add a new yml file. Make sure you give it a unique name.

The DMI is off center, does it animate?

**Comment by utahclock** [comment]
yes it animates.. recentering now. will add a new yml

**Comment by TehFlaminTaco** [comment]
Wait, so it's that adorable ghost thing?

BEST FEATURE.

**Comment by Iamgoofball** [comment]
# copyright infringement

**Comment by DavidEdwards** [comment]
Ahhhhhh.... AAHHHHHH,,, [AHHHCHOOOO](https://github.com/tgstation/-tg-station/blob/master/icons/mob/alien.dmi)!!!!

**Comment by Iamgoofball** [comment]
yes but you're actively selling this sprite, alien sprites aren't donator locked

**Pull request merged**
