### PR TITLE
Adds tactical dolphin

### PR DESCRIPTION
**Pull request by Cruix**
from this thread: https://forums.yogstation.net/index.php?threads/tactical-dolphin-disky-the-dolphin.8221/
*available to nukeops for 20TC, with the same spawning process as syndicate cyborg.
*can fly around space with no problems like any other dolphin.
*like all simple mobs, it is immune to most stuns.
*100 health, 15 melee damage.
*heals 5 health from each bite of a syndicake, comes with 5 syndicakes.
*has an unremovable syndicate headset.
*understands English/Human, but can only speak in random dolphin noises. Can emote normally. Can speak in random dolphin noises over its radio.

Comes wearing a removable harness. While wearing the harness, the dolphin has:
*toggleable emag and night vision.
*inventory the size of a backpack. The dolphin cannot put items in it, but any human can through the strip menu. The only way to remove items are to have the dolphin drop them, or remove the harness, which takes a human 6 seconds.
*laser that shoots swarmer speed (once every 3 life ticks) and never runs out of charge. It has support for multiple weapons it can cycle through, but there is only the one installed by default.

Screenshots:
dolphin 1

dolphin 2

dolphin 3

### CODE REVIEW

**Comment by Cruix** [comment]
This has a lot of hacky stuff in it, so I would appreciate any constructive feedback from other coders.
Also the entire UI is codersprites so KMC should fix that.

**Comment by ghost** [comment]
the sprites looks like barfed vomit

the idea is barfed vomit too what is this autism

jesus christ

one laser every three seconds are you fucking kidding me

you can buy an absolute murderkill machinegun for 16 TC that's going to kill 3 sec officers

this will have a hard time killing one assistant

what the fuck is this it's so bad holy fuck

holy fuck

this is so fucking bad

it's worth 6 TC, tops, as is

**Comment by Cruix** [comment]
> 6TC

Each op can buy like 4 dolphins.
Just swarm the station with 16 dolphins.
I love it.

**Comment by ghost** [comment]
fund it

**Comment by Cruix** [comment]
An emag costs 6 TC.
The dolphin has an emag, and is a nigh-unstunnable player-controlled companion that attacks with 15 damage and occasionally shoots lasers, and is basically a free jetpack and backpack.
Let's make the dolphin cost 6 TC. We are the future.

**Comment by ghost** [comment]
It also fires a laser every 3 seconds

It's a space carp that can juke and dodge in a gamemode where ops can buy permanent invincibility to 90% of ranged tools for 16 TC.

Why should I spend 20 TC on this instead of 20 TC on a macrobomb or an eshield and a few stun slugs for my bulldog?

This thing is shit for 20 TC. 

So fucking what if it's unstunnable? It has 100 health and does as much damage as a lit welder to an unarmored guy where you can buy a 30 damage murder tool for I don't know 7 TC?

It's terrible and if you have more than two brain cells you'd see that.

One laser, it's dead. Fucking dead. Hell you could kill it with a welder, god knows carp are easy to kill.

It's terrible in every fucking way compared to anything else.

Buff it. Either make the laser a heavy laser, or make it shoot 3 bullets for 20 damage each on a 3 second cooldown, and give it 150 health. Then it's maybe BARELY worth 20 TC.

Also, instead of a dolphin, this should just be Cayenne in power armor instead. Don't implement shitty dolphins any more than we have to, they're already autistic and we have a perfectly good space carp.

**Comment by TehFlaminTaco** [comment]
6TC HYPE!

**Comment by ShadowDeath6** [comment]
Buff cayenne when

This is kind of underpowered. Maybe if it was like 1 second laser cooldowns.

**Comment by AsV9** [comment]
I don't understand the dolphin meme

**Comment by ghost** [comment]
nobody does but it makes me vomit

**Comment by Super3222** [comment]
so when pukeops declare war, 50% of the crew may suicide hoping that one of the ops spends all of their TC on dolphins.

gg when swarm of dolphins approaches the station.

You should be able to draw a circle which makes you immune to these by the way.

Clowns are too clumsy and draw ovals.

**Comment by Cruix** [comment]
> so when pukeops declare war, 50% of the crew may suicide hoping that one of the ops spends all of their TC on dolphins.

I would like to say that our playerbase is not that autistic, but I fear I would be wrong. At least that might actually make it worth the 20TC

**Comment by Cruix** [comment]
I buffed tactical animals a bit, increasing their health to 150 and decreasing the laser cooldown to 1 life tick (I was in error when I said it used to be 3 life ticks, it was actually 2 at the time).

I also made the harnesses generic, so it's easy to make one for any hostile simple_animal. I replaced the dolphin spawner in the nukeops uplink with a tactical carp harness, because Adam hates dolphins. The carp harness will attempt to give the carp sentience when you put it on the carp, and if it does not succeed, you cannot place it on the carp and can refund it. I don't have a sprite for tactical carp, so at the moment it just changes the sprite to that of a tactical dolphin.

Space carp can't eat syndicakes but still come with 5, because why not?

No changelog yet because it will almost certainly change a lot, if it is even considered for merging at all.

**Comment by ghost** [comment]
Laser is still too UP.

Needs to be either a heavy laser, or fire 3 bullets-preferably lower damage bullets like the stetchkin or the bullets fired by the syndicate operative mobs that do stam damage (the bullets should have the initial 3 second cooldown. Perhaps 2 seconds.)

This means that the dolphin can then lay down fire support alongside it's team and still stand a reasonable chance instead of being a waste of 20 TC.

**Comment by ShadowDeath6** [comment]
Also, problem. Cayenne isn't a carp, it's some horrifying abomination of code that makes it like a space bat. (I THINK) Might need to make it an actual carp or something.

**Comment by TehFlaminTaco** [comment]
I can confirm, Cayanne is a space bat.

**Comment by Cruix** [comment]
I...but...<i>why</i>?

**Comment by Groudonmaster** [comment]
Because carp are inherently hostile so even if you took away it's damage it'd still nuzzle the shit out of the nuke ops and generally get in the way.

**Comment by ghost** [comment]
> Because carp are inherently hostile so even if you took away it's damage it'd still nuzzle the shit out of the nuke ops and generally get in the way.

WHY IS THIS NOT A FUCKING THING

WHY DO WE NOT HAVE TACTICAL NUZZLE OPS

**Comment by Cruix** [comment]
Couldn't you just set Cayanne's AIstatus to AI_OFF and it wouldn't nuzzle the crap out of the ops?

**Comment by AsV9** [comment]
Yes, `AIStatus = AI_OFF` does just that if I remember correctly.

**Comment by X-TheDark** [comment]
I'm pretty sure it would make her not move, though.

**Comment by Cruix** [comment]
That's what I did to make the tactical dolphin not molest me while I was testing with it (I had to hurt it to test the syndicake healing, and attacking a dolphin makes it attack you back), and it still wandered around. It was quite annoying, actually, since it would sometimes randomly move when I was trying to add/remove the harness.

**Comment by Cruix** [comment]
You now get a harness that works on both carp and dolphins. Dolphins move about 50% faster than an unencumbered human, and fire three shots instead of 1 per cooldown. Carps have 300 health instead of 150, and fire one heavy laser shot per cooldown. Cooldown is still 1 life tick.
Also added a tactical carp sprite (from https://tgstation13.org/phpBB/viewtopic.php?f=11&t=290) and fixed a few bugs.

**Comment by Kmc2000** [comment]
You're my hero

Im so fucking happy my suggestion got added

**Comment by FluffySurvivor** [comment]
> sniper rifle when
> REEEEEE

**Comment by ShadowDeath6** [comment]
> sniper rifle

good one, I chuckled a bit. Let's add wall-penetrating bullets that 2hit kill armored people, right?

**Comment by DavidEdwards** [comment]
@Kmc2000 Would you mind helping to fix up the sprites for this PR?

**Comment by Kmc2000** [comment]
@DavidEdwards

Sure, just gimme a list

**Comment by Cruix** [comment]
It's all in icons/mob/screen_dolphin.dmi 
night vision on
night vision off
emag on
emag off
weapon safety on
weapon safety off
open inventory
dragging

**Comment by Cruix** [comment]
UI is no longer codersprites:
untitled2

untitled3

**Comment by Cruix** [comment]
I added a dolphin to the syndicate mothership, and made Cayenne an actual carp. I'd say it's ready to merge now. (After I add the changelog).

EDIT: Yeah, nevermind, I messed up their speaking. Still DO NOT MERGE.

**Comment by ShadowDeath6** [comment]
Spider carp ops confirmed best buff of the decade

**Comment by AsV9** [comment]
Can't merge this if I wanted to.

**Comment by Cruix** [comment]
Pretty sure Borers caused a conflict somewhere

**Comment by AsV9** [comment]
The conflict is located inside animal.dmi if I am reading this correctly.

**Comment by ghost** [comment]
Okay good, now that we fixed all of that.

Close this and burn it. 

I've already gone over how terribly thought out it is, how horrible the sprites still are, how ridiculous and childish dolphins even are as a concept, how badly balanced it is, ect.

The carp is basically a cyborg with a heavy laser and the dolphin will move fast enough it's liable to shoot itself, not to mention that 60 burn damage per shot on something that moves faster than a human and is player controlled is horribly unbalanced.

**Comment by AsV9** [comment]
Any more input?

**Comment by oisin100** [comment]
Even if its never used i want to see it added for the occasional flukeops who want to use it. Make it come with a carp spawner.

**Comment by Time-Green** [comment]
just kill this

**Comment by Cruix** [comment]
I'll take the uplink datum out so it's not a buyable item. KMC will still be able to adminspawn them in for his shenanigans.

**Comment by Kmc2000** [comment]
HONK

Also, badam, how are they unbalanced? cruix took in all of your suggestions/rages about them

**Comment by DavidEdwards** [comment]
With it only being available by Admin spawn, I am happier to merge this. It can be tested by admin bus.

**Pull request merged**
