### PR TITLE
hopefully maybe manages to port /tg/'s newest buttload of blob chems

### PR DESCRIPTION
**Pull request by ghost**
help i don't know how to computer

control + v is my only coding tool HELP

anyway, it adds all the shit /tg/ added. Specifically, Ripping Tendrils now does medium brute and some stamina damage, 
Replicating foam, which does low damage but has a chance to expand 2x when blob expands
Energized fibers, which does low burn damage and high stamina damage, and reacts to stamina damage,
Regenerative materia, which convinces the person they are fully healed on hit, and does low toxin damage, meaning you don't know when to stop fighting until ded,
Hallucinogenic nectar, which replaces drugs, which poisons you and makes you hallucinate.
Zombifying feelers, which turns unconcious/critted humans into, well, zombies. Whew.
Envenomed filaments, which does toxins and stamina damage, and dump spore toxin into the hit person.
Cyclonic Grid, which basically replaces lexorin jelly, flinging you around and draining air from your lungs.
Lexorin jelly is no longer stupidly hitting for 40 damage.
Explosive lattice, which does brute damage in an AOE area, and is resistant to explosions.
Reactive gelatin, which does high brute damage, and reacts to brute damage.
Cyrogenic liquid, which slaps you with frost oil.
Electromagnetic web, which emits a freaking EMP when killed, but is a LOT weaker than other blobberinos.
Penetrating spines, which uh, goes right through armor to stab you in the face.
Pressurized slime, which basically wets tiles under targets or when killed, meaning you better have galoshes.

Again, hoping this doesn't bork anything.

### CODE REVIEW

**Comment by ghost** [comment]
oh no it failed

i have no idea what that means

**Comment by Cruix** [comment]
You didn't port all the stuff it needs and it's yelling at you because it can't find it.
Most of it seems to be in this commit: https://github.com/tgstation/-tg-station/pull/15250/files

There are some things, like weak blob spores, that I can't find, so you'll have to dig through /tg/ code to find them too.

**Comment by AsV9** [comment]
Ye, some stuff is missing. Also changelog grrr

**Comment by ghost** [comment]
I removed weak blob spores because sporing pods is removed from this PR.

Because i'm all for new blob chems but fuck that zerg spam shit.

**Comment by ShadowDeath6** [comment]
Sneaky comment by explosive gelatin-
"//I'm going to burn in hell for this. "

Also if you wanna replace space drug blob you should probably remove it

Also why do you hate spore pods they're so cool

**Comment by ghost** [comment]
i was wrong it does not replace space drug blob now shush i'm trying to make this not bork

**Comment by ShadowDeath6** [comment]
Maybe you need to add sentient blobbernauts since they behave differently on tg than on here :^)

**Comment by ghost** [comment]
i'm not adding setinent blobbers because i removed anything blobber related from this PR

**Comment by ShadowDeath6** [comment]
> removing code

Might be a reason that shit is acting up

**Comment by ghost** [comment]
no mate it's acting up because i forgot some important things

**Comment by ghost** [comment]
also, fuck this noise i'm not touching this again with a ten foot pole because git is dick

**Pull request closed without merging**
