### PR TITLE
Porting /tg/ major shield overhaul

### PR DESCRIPTION
**Pull request by Super3222**
### Intent of your Pull Request

Ports tg's massive shield overhaul by @KorPhaeron . It mainly changes IsShield() with hitreaction()

Blocking overhaul ported from [tgstation/-tg-station#13327](https://github.com/tgstation/-tg-station/pull/13327).
Stunbatons RESPECTING shields ported from [tgstation/-tg-station#13823](https://github.com/tgstation/-tg-station/pull/13823)
Energy shields won't reflect stunbatons. [tgstation/-tg-station#13785](https://github.com/tgstation/-tg-station/pull/13785)
Reactive mechanic expansion, and shooting grenades/flamethrowers in peoples hands. [tgstation/-tg-station#13585](https://github.com/tgstation/-tg-station/pull/13585)
Police and telebatons will respect sheilds as well ported from [tgstation/-tg-station#15591](https://github.com/tgstation/-tg-station/pull/15591) @Lobachevskiy

Mechanic wise changes explained:
-Attack type definitions added to combat.dm
-Riot shields, and the variants of them, get a 60% blockchance.
-Stunbatons and normal batons respect shields and have a chance of getting blocked.
-RD's armor now has two new variations of it. One with tesla lightning that will shock people around them, and another one that sets them on fire.. Not possible to get during a shift, basically adminspawnable only.
-Wearing the clown suit will make a HONK noise whenever you get hit.
-You can no longer catch objects that have an embed chance.
-You have a chance to shoot grenades/flamethrowers in peoples hands, setting them off / rupturing them!
-Tele Shields now require level 6 combat research and cost a little more silver for obvious reasons.
-People will get a random amount of toxin damage when wearing the tele armor from the radiation.
-Riot shields will block thrown projectiles.

Feel free to discuss. Also if there's anything else regarding the shield overhaul from /tg/ just inform me, and I'll port it.

### CODE REVIEW

**Comment by FluffySurvivor** [comment]
Cool, cool, I respect this pr.

What i don't like however is that you added more rng to combat, which is bad. Either make the things guaranteed to block or make em 0 chance

**Comment by imtakingabreakdontatme** [comment]
@FluffySurvivor 

How do you guys handle things like riot shields if not rng?

**Comment by imtakingabreakdontatme** [comment]
@Super3222 

It's a bit more work to port since it requires mobs, but I highly recommend the reactive stealth armour. Easily my favourite of the reactive armours.

**Comment by Super3222** [comment]
> What i don't like however is that you added more rng to combat, which is bad. Either make the things guaranteed to block or make em 0 chance

@FluffySurvivor
I KNOW HOW YOU FEEL. RNG to combat is terrible, if you are more experienced random occurrences shouldn't stump you. I wanted the same thing, but it seemed like I should have consulted with the other coders. I tried getting some discussion on the coder channel of our github, but the responses only asked for me to raise the block chance instead of making it 100%. I wanted it more to be on the side of "most likely going to block a stunbaton" because RNG is terrible. 

> It's a bit more work to port since it requires mobs, but I highly recommend the reactive stealth armour. Easily my favourite of the reactive armours.

@KorPhaeron 
Will do.

Don't merge this until I've ported some more things, please. I'll make the updates seperate

**Comment by FluffySurvivor** [comment]
@Super3222 you could try the following :
Roman shield: immunity to punches and throws, nothing else

Riot shield: full melee immunity (LIKE IT WAS ALWAYS SUPPOSED TO BE), 0 ranged resistance. 

Eshield: full ranged energy weapons immunity and 0 for melee and bullets (looks like you've already done this one) 

@KorPhaeron
Luck-based combat is completely unfair and instead of rewarding skill... It creates randomness.

**Comment by KorPhaeron** [comment]
@FluffySurvivor 

I'm not trying to debate the merits of RNG combat, I'm asking you how you guys currently handle shields if you think this PR "adds" randomness

**Comment by X-TheDark** [comment]
Damn, really nice work.

My biggest gripe with shields is still the fact that they give a 360 degree protection. I'd have no issue with giving riot shield 100% melee resistance IF it only protected like the frontal 3 squares, so you can flank the opponent.

**Comment by imtakingabreakdontatme** [comment]
I actually just did directional combat for mechas if you guys are serious about that. The code to compare mech facings vs attacker direction should work for any two mobs.

https://github.com/tgstation/-tg-station/pull/16607

I think it might be a little wonky for humans though considering how fast they turn

**Comment by X-TheDark** [comment]
/tg/ coders, always X+1 step ahead.

One thing, though, is it possible to be hit from a diagonal? As in, does combat register diagonal as a separate direction or it follows the rounding rules and picking the closest valid cardinal direction?

**Comment by ShadowDeath6** [comment]
What are the stats on eshields from this? I got mixed information from the linked stuff.

**Comment by imtakingabreakdontatme** [comment]
@ShadowDeath6 

They reflect 100% of energy projectiles, and never block anything else

@X-TheDark 

It picks the closest direction. I don't know about your codebase, but ours automatically orients the attacker prior to the attack/animation

**Comment by ghost** [comment]
Riot shields not having a % to block tazers and lasers is gonna be a pretty big nerf to the teleshield and riot shield. I'd say letting them keep an RNG blockchance rather than complete and total immunity is a better option.

I mean, i'm all in favor of riot shields 100% blocking any melee attacks, including stuns from batons and telebatons and stunprods, but I sort of want them to at least have the % chance to block incoming tazers or lasers or disablers, too. Otherwise the riot shield is a slot that could be better occupied by anything else, including staying the fuck out of melee range.

Not to mention, eswords have a blockchance too, from what I saw on /tg/code. Might want to port that-it's a nice buff to a basically useless weapon.

**Comment by imtakingabreakdontatme** [comment]
If you guys really, really, REALLY hate any sort of RNG at all, I have coded a solution for that as well, and this block refactor is part of it.

https://github.com/tgstation/-tg-station/pull/13717

The hit_reaction system allows for stuff like regenerating overshields that block 100% X number of hits before fizzling out and leaving you unprotected (before recharging later).

But if you don't want to go that route for lore/fluff reasons, it'd be very easy to make a shield that blocked stuff 100% of the time but broke down as it got hit, and had to be repaired before it could block again (or a fancy recharging version for RD or something.)

**Comment by ghost** [comment]
ew

stick with the RNG  instead of breakdowns

**Comment by imtakingabreakdontatme** [comment]
@AdamElTablawy 

I like RNG personally, since I am a big fan of tabletop. Don't really understand the aversion to it. Option is there though.

**Comment by Super3222** [comment]
Give me a second before merging please.

**Comment by AsV9** [comment]
How merge-ready is this?

**Comment by Super3222** [comment]
@AsV9

It's ready now. If someone wants to look it over one more time, that'd be great. In other news, nerfing 360 block will be another pull request.

**Pull request merged**
