### PR TITLE
Surgery crate

### PR DESCRIPTION
**Pull request by ToGWtF**
Refer to issue #1028 

todo : ~~changelog~~  ,  ~~make delay on wrenching so you cant steal tables instantly~~  ,  ~~check how surgery computers work~~

:cl:
rscadd: Adds surgery crate to cargo
rscadd: Adds operating table to cargo
rscadd: Operating tables may now be unanchored and moved
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
Why not make them one crate?

**Comment by ghost** [comment]
one crate

**Comment by ToGWtF** [comment]
not one crate. you can order backup surgery tools without having to do sexual favors for the QM to let you use 50 of his points. everything for surgery can be found around the station or built (ghetto tools and bedsheets).

now that i think of it should the anesthetic masks go with the table crate? 10 points for a mask and tank that can put someone to sleep the entire round

**Comment by DavidEdwards** [comment]
Two crates are fine. 15 might be a little bit too little for the fun tools, but we shall see.

**Pull request merged**
