### PR TITLE
Shades can return to their soulstones

### PR DESCRIPTION
**Pull request by Super3222**
### Intent of your Pull Request
#617

Ghosted Shades can re-enter their soulstone homes by clicking on the shard.

When you summon shades out of their soulstones, it'll force the ghost into the shade as well.

FAQ:
'what if i don't wanna play'

The only solution is suicide.

### CODE REVIEW

**Comment by ToGWtF** [comment]
So infinite ghosting to find targets? eh. cultists can already astral journey and ghost anyway

**Comment by Super3222** [comment]
It'll be considered meta if they use any information that they gather from ghosting.

This is just so that they aren't completely fucked if they ghost because of boredom.

**Comment by DavidEdwards** [comment]
I think, if they ghost out of boredom, they get what they deserve.

I'm wary of giving players more ways to meta.

Open to thoughts.

**Comment by ShadowDeath6** [comment]
Reminder that posibrains work the same way and we haven't had any real problems with it

**Comment by ShadowDeath6** [comment]
Merge reeeeeee

**Comment by Super3222** [comment]
reeeeeeeeeeeee

**Comment by DavidEdwards** [comment]
> Reminder that posibrains work the same way and we haven't had any real problems with it

Can you pop in and out of ghost at will multiple times with Posibrain?

**Comment by ShadowDeath6** [comment]
Yes you can, but somebody can take your body while you're out.

**Comment by ShadowDeath6** [comment]
Merj pls ;_;

**Pull request merged**
