### PR TITLE
Adds wanted posters

### PR DESCRIPTION
**Pull request by Cruix**
Implements wanted posters from this thread:
http://forums.yogstation.net/index.php?threads/wanted-posters.5746/

All records on the security records computer have an option to print a wanted poster right next to the option to print the record. The poster uses the picture from their security record. By default, the description contains the name of the subject and a list of their crimes at the time of printing, but this can be changed to anything you want.

### CODE REVIEW

**Comment by TehFlaminTaco** [comment]
Screenshots?

**Comment by AsV9** [comment]
The code looks good but I'd like to see a screenshot.

**Comment by Cruix** [comment]
Screenshots:
wanted poster option

wanted poster

**Comment by TehFlaminTaco** [comment]
Looks awesome.

**Pull request merged**
