### PR TITLE
Added Cybermen gamemode. Still requires extensive testing. To enable …

### PR DESCRIPTION
**Pull request by Cruix**
Pull request redone through a branch of my fork. Like I should have to start with.

http://forums.yogstation.net/index.php?threads/mode-cybermen.8096/

Cybermen is a team-antag mode in which the antagonists can "hack" objects, which requires them to initiate the hack by standing within 1-tile distance of the object, and then remain within 10 tiles of it until the hack completes. Hacking objects has various effects, many of them similar to emagging the object. Doors are bolted open, borgs get a 0-priority law, etc.

The antagonists are given four objectives throughout the round, with each new objective chosen and displayed after the previous objective is complete. The final objective is always one of: Make at least 60% of the station be cybermen (by killing or converting non-cybermen), hijack the shuttle so no non-cybermen escape on it, or destroy the station with the nuclear device.

### CODE REVIEW

**Comment by george99g** [comment]
Do you have the "Automatically set FILE_DIR for sub-directories" enabled in your dream maker?
That seems to be adding file directories to the .dme which shouldn't be there.
Could you fix that?

**Comment by Cruix** [comment]
Sorry about that, I've disabled it.

**Comment by AsV9** [comment]
I'm just going to say do not merge before this has been tested properly.

**Comment by ghost** [comment]
how's tests goin'

**Comment by Hydre** [comment]
Think test is gonna be this weekend

**Comment by Time-Green** [comment]
SO LETS PLAY IT THEN!!!!!!!!!!

**Comment by AsV9** [comment]
Yeah forgot about this last week.

**Comment by ghost** [comment]
so did it get tested

or 

did we forget????

**Comment by george99g** [comment]
AsV's testing it.

**Comment by Hydre** [comment]
> Yeah forgot about this last week.

Read as: "Too busy playing R6S"

**Comment by AsV9** [comment]
I'll take my chances.

**Pull request merged**
