### PR TITLE
Ports Saline-Glucose replenishing your blood (+INJECT method of application)

### PR DESCRIPTION
**Pull request by X-TheDark**
Refer to issue #1095 .
### Intent of your Pull Request

You know, giving a way to replenish blood other than bloodbags (which are still more efficient) is a pretty damn good idea.

Ports these PR's from /tg/ made by @lordpidey
https://github.com/tgstation/-tg-station/pull/12921 - Saline-Glucose now replenishes blood (lower your bloodlevels, the more efficient the transfusion)
https://github.com/tgstation/-tg-station/pull/12700 - Adds new method of reagent application INJECT

:cl: LordPidey
rscadd: Saline-Glucose Solution can now be used as a blood replacement (the lower your blood amount, the more effective this is). Must be applied via injection (IV Drip or Syringe). Ported by X-TheDark.
/:cl:

### CODE REVIEW

**Comment by EMT321** [comment]
I thought it did this already, +1

**Comment by lordpidey** [comment]
This will also fix a bug related to space cleaner.

Space cleaner pills will no longer magically clean your clothes.

**Comment by X-TheDark** [comment]
That pill thing actually sounds hilarious.

**Comment by ShadowDeath6** [comment]
> space cleaner pills will no longer clean your clothes

:-1:

**Pull request merged**
