### PR TITLE
Giving the rev flash and hijacker tech levels.

### PR DESCRIPTION
**Pull request by Super3222**
Refer to issue #1014 where I clearly did not completely comprehend the hijacker.
### Intent of your Pull Request

Rev flashes will gain level 1 illegal tech and level 2 combat.

Rev HIJACKERS will gain level 6 electromagnetic and level 3 illegal.

:cl:Super3222
rscadd: Rev Flash can be deconstructed in R&D for level 2 combat and level 1 illegal tech.
rscadd: Revolution Hijacker tools can be deconstructed in R&D for level 6 magnet and level 3 illegal tech.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
> be rev
> get illegal 3 with flashes and tyrant board
> make illegal borg modules
> subvert borgs
> borgs now have lasers and death syringes with a vendetta against the heads

:+1:

**Comment by oisin100** [comment]
Mmm, Shadow has a point...

**Comment by ghost** [comment]
> getting a revhead to deconstruct his most important conversion tool
> miners doing work during rev
> managing to subvert borgs and AI during rev when it is probably paladin and sec is going turbohitler
> someone being intelligent enough to print the illegal borg module in the first place after subverting AI and not just screaming for borgs to rush the brig
> all this happening in one round

Itd happen maybe like once and chances are sec will just turbohitler the borgs too the moment they get subverted + usually when AI is rev security gets gg'd within 5 minutes to plasma

**Comment by ShadowDeath6** [comment]
Flashes aren't hard to make though

**Comment by Time-Green** [comment]
Just make it only the Hijacker.

**Comment by Super3222** [comment]
The reason I'm giving syndicate tech levels to the flash and hijacker is so they become apparent that they are in fact syndicate equipment. 

I am also aware that you can scream "REVS" when you see one of these on the ground.

**Comment by ShadowDeath6** [comment]
Tbh if revs are smart enough to abuse illegal tech and get pins and whatnot they deserve the items, it encourages originality

**Comment by oisin100** [comment]
I suppose your right Shadow and Adam.

**Pull request merged**
