### PR TITLE
Various balance changes for cybermen

### PR DESCRIPTION
**Pull request by MacHac**
### Intent of Pull Request

This PR includes some minor changes to the cyberman game mode.
- Cybermen are significantly more vulnerable to EMP grenades.
- De-cybermanization surgery makes more sense in the context of other, similar operations
- De-cybermanization surgery is no longer invariably fatal for the victim

Also,

### CODE REVIEW

**Comment by Cruix** [comment]
Why is clamping the bleeders before you saw open the bone? That's how it goes in organ manipulation.

Also what was wrong with that shade of red?

**Comment by ghost** [comment]
it looked like bloody diharreah tbh

**Comment by DavidEdwards** [comment]
Why remove a step in the removal process? Do the nerf  changes make sense to you Cruix?

**Comment by Cruix** [comment]
Oh, I thought he was adding a step, now I see he is removing one. I'm not sure why. I'm fine with everything other than the surgery change, but it's not a big deal, since the surgery is pretty much never used anyway.

**Comment by ghost** [comment]
Surgery for deconversion is really tedious and bad tbh

**Comment by MacHac** [comment]
I changed the surgery because for debraining, it's
Scalpel - Retractors - Saw - Hemostat - Scalpel - Hemostat
and the old surgery, which did effectively the same thing, was 
Scalpel - Hemostat - Retractors - Saw - Scalpel

It just made no sense to me that there was randomly a hemostat in there for a procedure that otherwise looked so similar to debraining. (And, I feel, is implied to do something very similar).

@AdamElTablawy The surgery option is intended for special cases, or critical staff members.  For example, if the captain started seeing binary, the security staff could forcibly deconvert him if they captured him instead of shrugging their shoulders and taking a toolbox to his head.

**Pull request merged**
