### PR TITLE
Borer Updates

### PR DESCRIPTION
**Pull request by oisin100**
Borer talk is now a shitty brown color(Or colour if you're american)

Basic medical chems now cost 35 chems instead of 50

Borers can infect ANY carbon creature now. This includes monkeys and Xenomorphs

Antags don loose their objectives or powers anymore.
#471
#470
#459

### CODE REVIEW

**Comment by oisin100** [comment]
More updates:

Fixes #472

Borers arent killed by the cold.

Borers And their hosts now have HUD icons showing them whos infected.

PS: Borer hud sprite credit goes to @ShadowDeath6

**Comment by ShadowDeath6** [comment]
> sprite 

If you can call it that :')

:+1:  though, borers are getting better every day.

**Comment by AsV9** [comment]
> Borers can infect ANY carbon creature now. This includes monkeys and Xenomorphs

Not sure if I like this, might be just me but I think borers shouldn't be able to farm genetics.
Other than that :+1:

**Comment by oisin100** [comment]
Latest update: Borers cant infect catatonic or braindead people.
Borers are given a new mind when spawned. No more borer nuke ops!

**Comment by AsV9** [comment]
Yeah I like that :+1:

**Comment by Time-Green** [comment]
Can we have medical scanners detect borers?
it was kinda anoying being CMO and trying to remove on borer. And then have 20 people with borers killing me.

**Comment by oisin100** [comment]
> Can we have medical scanners detect borers?

Sure

**Comment by oisin100** [comment]
Health analyzers now show the following message when someone is infected

`Foreign virus detected in subjects cranium. Recommended treatment: Brain Surgery and a dosage of sucrose in solution.`

**Comment by ghost** [comment]
Health HUD's too.

Make health hud's detect them the same way it detects xenomorph infections, with the same sprite, ect.

Yes, this is balanced, it was done before on Paradise. And with how quickly borers replicate, this might stem the tide some.

**Comment by ShadowDeath6** [comment]
Paradise did it so HUD only detected borers when they were controlling people.

**Comment by ShadowDeath6** [comment]
> borers can't infect braindead/catatonics

they're not punished if their host DC's or ghosts, right?

**Comment by oisin100** [comment]
> they're not punished if their host DC's or ghosts, right?

they can stay in their host if the host DC's they just cant infect DCed mobs.

**Comment by ShadowDeath6** [comment]
You might want to say "organism" instead of "virus" on the health scanner thing.

**Comment by oisin100** [comment]
> You might want to say "organism" instead of "virus" on the health scanner thing.

Good idea!

> Paradise did it so HUD only detected borers when they were controlling people.

Sounds good. Ill see what i can do!

**Comment by oisin100** [comment]
Fixed #487

Borers now show up in the Med hud IF the borer is in control. Looks like regular xenomorph hud.

Changed `virus` To `organism` in health scanner message.

**Comment by ShadowDeath6** [comment]
**_MERGE WHEN_**

**Pull request merged**
