### PR TITLE
Port of /tg/ fixes for overlays in BYOND 510

### PR DESCRIPTION
**Pull request by X-TheDark**
Issue #264
Oh god, it's finally done. Kill me.
All original credit to @Neersighted and his pull on tg tgstation/-tg-station#14981

Stole his modifications to .dmi's to make overlays work. Stole and adapted his code for overlays.

This fixes several issues in BYOND 510 with overlays:
- Mouse clicks not catching objects under it;
- Blind/Flash overlays not working causing people to be blind on start;

What's updated in .dmi's:
- screen_gen.dmi -> flash (Made into 1 frames of pure white)
- screen_full.dmi -> +impairedoverlay1/2 (Stole overlays for various levels of impaired vision)

Tested stuff:
- Can click on stuff;
- Flashes/Screwdrivers on Human mob;
- Flash on Cyborg mob;
- Aghosting in/out of mob (used to break overlays);
- Same as above but on BYOND 509;

EDIT: ISSUES (completely forgot to include this):
- Target _CANNOT_ be reflashed until the previous flash animation ends, meaning that the stun will still go, but you vision will not be impaired.
  If you want me to do any more tests, please tell me.

### CODE REVIEW

**Comment by neersighted** [comment]
:+1: nice work

**Comment by X-TheDark** [comment]
Also thanks for the help on #coderbus, you literally saved me as I was stumped at that point.

**Comment by neersighted** [comment]
Anytime

**Comment by DavidEdwards** [comment]
Nice work. I'll test this ASAP.

**Pull request merged**
