### PR TITLE
Remote disintegrate

### PR DESCRIPTION
**Pull request by TehFlaminTaco**
Removes disintegrate from the wizard's spellbook, at Hardy's request.

### CODE REVIEW

**Comment by X-TheDark** [comment]
Is this a permanent solution or is this temporary until the spell can be adjusted/new spell be made to replace this?

**Comment by AsV9** [comment]
Strongly opposed to this.
:-1:

**Comment by TehFlaminTaco** [comment]
https://i.gyazo.com/e55adfd5ce85df127e74b40d3598a7fe.png

**Comment by AsV9** [comment]
I dun care about that. Still strongly opposed. :-1:

**Comment by B1gb3ast** [comment]
You can't Just remove the ONEEEE PUUUNCH!

**Comment by Alek2ander** [comment]
:baby_bottle: :baby: :lollipop:

**Comment by TehFlaminTaco** [comment]
Just realised I named the commit wrong, it's supposed to be "Remove's Disintegrate"

**Comment by X-TheDark** [comment]
Ranged EI NATH would be a blast, though, but I guess that would probably just mean adding Death Bolt to buyable spells for Wiznerd.

Although...maybe Death Bolt - a spell that doesn't hit stunned targets (because they are down and you can't aim at them - think fireball) would be a great replacement spell?

**Comment by ghost** [comment]
Again, disagree. It's already heavily nerfed as is, has the considerable drawback of eventually ending in an army of angry security borgs coming after the wizard, is an inhand spell so it's no longer an instant gib, and one of two spells the wizard has that can actually be used to kill someone-the second being lightning bolt. Anything else and you have to use lasers, melee, or waste a spell point on a staff of chaos/wand belt/get lucky with a staff of change and make the guy into a butterfly and hope he doesn't become a syndieborg.

**Comment by AsV9** [comment]
@X-TheDark Might be you're misunderstanding, this PR is about removing the disintegrate from the wizard spellbook.

**Comment by Super3222** [comment]
Gah! New players won't get the same experience we did the first time a wizard magic missle'd and ei nath'd us.

**Comment by shrimptk** [comment]
**booooooo**. getting rid of an iconic spell just because people get a lil' buttmad, just as lame as making C4 and minibombs not gib.

**Comment by AsV9** [comment]
Closing this due to input here and in #77 
I'm leaving the issue open, though.

**Pull request closed without merging**
