### PR TITLE
New Emotes

### PR DESCRIPTION
**Pull request by Super3222**
### Intent of your Pull Request

Adds some new emotes (it's been a while), that have been bugging me for a year, since they aren't in there.

*whistle - whistling innocently
*waggle - moving your eyebrows up and down
*smirk - makes a smirk, usually used to piss people off
*smug - makes a smug look on your face

Oh, and I also threw in

*catwhistle - for whistling when uhm...

Also, for the record, I'm not a badperson. I'd never would want to harass someone.

:cl:Super3222
rscadd: NEW EMOTIONS!
rscadd: *whistle - whistles innocently
rscadd: *waggle - eyebrows bop up and down
rscadd: *smirk - devilish smile
rscadd: *smug - :^ )
rscadd: *catwhistle - you'll get slapped for this one.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
*smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug *smug 

Don't even pretend that you aren't putting literal ",':^)" into the game

**Comment by oisin100** [comment]
10/10

**Comment by krgii** [comment]
Add *tip that checks to see if you're wearing a fedora and then tips it.

**Comment by Super3222** [comment]
> Add *tip that checks to see if you're wearing a fedora and then tips it.

Haha, I like your thinking. But @B1gb3ast has already created that at #148!

**Comment by ShadowDeath6** [comment]
*smug

**Pull request merged**
