### PR TITLE
Nuke Ops turrets

### PR DESCRIPTION
**Pull request by ToGWtF**
Refer to issue #596 #330 
### Intent of your Pull Request

Mutha'fucking turrets. ~~Offline until nukeops call war~~. ~~Do shit tons of damage~~.

can scale the damage down and make them active always if shadow begs hard enough

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
you should make them active always

**Comment by ghost** [comment]
Always active, lower damage to 30 per bullet + stamina.

**Comment by EMT321** [comment]
Please make them always active, and not an instant kill if an engineer walks too far south and gets hit by a single bullet.

**Comment by AsV9** [comment]
> scale damage down and always active

pls

**Comment by ToGWtF** [comment]
No stamina damage. You wouldn't be able to scream help if you took enough bullets for stamina damage to knock you down before you crit.

I'll lower the damage from 60 to 25. Its a deterrent, not a weapon.

**Pull request merged**
