### PR TITLE
Small bugfixes

### PR DESCRIPTION
**Pull request by Cruix**
Fixes not logging and messaging admins when an admin makes someone a shadowling through the traitor panel. Fixes issue #35.

### CODE REVIEW

**Comment by george99g** [comment]
Why did you add 4 commits to it that delete each other?
Wouldn't it be better to just include 65e8c2f5cfdc4b5d4a82f3bccf3cdccde49f0007 in the PR and remove the others?

**Comment by Cruix** [comment]
It would have been. I just have no idea how to use github.

**Comment by Cruix** [comment]
Added admin messages when a head rev is given an uplink, fixing issue #62.

**Comment by Alek2ander** [comment]
Don't commit file_dir lines in the dme. 

Also how to remove extra commits: rebase the branch onto the commit before your changes in interactive mode.

**Pull request closed without merging**
