### PR TITLE
ToolTip feature

### PR DESCRIPTION
**Pull request by Super3222**
Adds a tooltip feature to Yog. Courtesy of #167. 

Q: What is a tooltip?
A: It's basically a small menu that comes down when you hover your mouse over one of the alert icons. (ex: weightless, no oxygen, too much pressure, etc.), it provides the description of the alert as well. So you no longer have to shift click it.

Q. W-why all the edits on the skin.dmf Super? You trying to destroy the game?
A. It took some time to actually get tooltips on there. At first I was confused, but than I realized something. The tooltips were BEHIND the actual main screen, so I had to rearrange them to be the very first.

### CODE REVIEW

**Comment by Xantam-13** [comment]
Sorry I may have missed the point or context. What exactly do they show? Can you give me an example of when I might need this or what it'd say when I hovered over? 
I only ask because I don't fully understand

**Comment by Super3222** [comment]
tooltip

@05rhardy, It'll look like this when your mouse is over the alert.

**Comment by Xantam-13** [comment]
Great. Is there a delay, or does the tip disappear immediately? If there's a delay, for admins mainly, would this interfere with pressing buttons? Obviously if there is no delay this question is irrelevant. 

Are there any known bugs? Have you tested it?

**Comment by Super3222** [comment]
The tip disappears immediately when you take your mouse off of the alert it's over.

I also did test & search for bugs, though you never know what players might discover. I also had a look at /tg/s git to see if there's any current bugs that haven't been fixed. Basically everything's fine.

**Comment by oisin100** [comment]
Looks epic! Would be pretty cool if it would work for other things such as sleepers and chemistry too!

**Comment by DavidEdwards** [comment]
@Super3222 I need you to re-create this PR - so that it will base on the "dev" branch. That way I can easily test it on the dev branch, rather than having it merge onto master.

**Comment by Super3222** [comment]
Will do.

**Pull request closed without merging**
