### PR TITLE
Support for Discord bot. Tickets and Rebooting.

### PR DESCRIPTION
**Pull request by oisin100**
Allows admins to answer tickets Via discord
And also allows admins to force a world reboot via discord.
- Stops annoying python compile files from getting in the way.

### CODE REVIEW

**Comment by oisin100** [comment]
Requires updating of https://github.com/yogstation13/Yogbot13 ill message someone when that's ready to be updated.

**Comment by Alek2ander** [comment]
Reboot should have a whitelist for discord accounts permitted to do that

**Comment by oisin100** [comment]
The bot(Once updated) now has a permission system based on YML. It can be configured to restrict certain commands to certain groups. EG, !reboot restricted to Council.

**Comment by oisin100** [comment]
Also makes Asay messages and OOC messages show the players name in bold.

**Comment by AsV9** [comment]
@DavidEdwards

**Pull request merged**
