### PR TITLE
New emote (shouldn't be borked)

### PR DESCRIPTION
**Pull request by B1gb3ast**
By bothering the actual coders to bassically write this for me, you can
now tip any hat. As long as you're holding it, because handsfree hat tipping is heresy.

### CODE REVIEW

**Comment by Super3222** [comment]
Finally! I can properly tip off my beret as a mime when I save people from the evil clowns clutches!

**Comment by ghost** [comment]
John Sweeps tips his fedora.

**Comment by shrimptk** [comment]
Jessica Alvarado tips her Fedora.
Jessica Alvarado slips on the banana.
Jessica Alvarado is hit by a bullet in the head!
Jessica Alvarado is hit by a bullet in the head!
Jessica Alvarado is hit by a bullet in the head!
Jessica Alvarado is hit by a bullet in the head!
Jessica Alvarado is hit by a bullet in the head!
Jessica Alvarado is hit by a bullet in the head!
Jessica Alvarado seizes up and falls limp, her eyes dead and lifeless...

**Comment by X-TheDark** [comment]
Next logical step - a tipoff battle between two fedora wielding masters. Loser gets tipped off...permanently (as in death).

**Pull request merged**
