### PR TITLE
Gives the rev flash and flashbulb hijacker tech levels

### PR DESCRIPTION
**Pull request by Super3222**
### Intent of your Pull Request

Title says it all.
Rev flash gets illegal 5, combat 3, and magnets 3.
Hijacker tool gets illegal 1 and bio 4.

:cl:Super3222
rscadd: Added tech levels to the rev flash and hijacker tool.
/:cl:

### CODE REVIEW

**Comment by DavidEdwards** [comment]
Need feedback on balance for this PR.

**Comment by ghost** [comment]
> rev flash has higher levels than the original tool
> 
> giving illegal five for a mass-reproducable item 
> 
> revs with decloners, clusterbang mechs and borgs with illegal tech modules

No

Rev flash should be the exact same as a normal flash.

The hijacker tool, however, should be emp 6, illegal 3, combat 2.

**Comment by Super3222** [comment]
> clusterbang mechs and borgs with illegal tech modules

YES.
However you can't get decloners without combat 6, that's why you never see them during a round, ever.

But really, I completely forgot about clusterbangs and and those illegal tech modules. So I'll revert the syndicate levels.

**Comment by ghost** [comment]
no you duxkinf

GIVE THE HIJACKER HIGHER TECHS THAN THE HIJACKED FLASH

**Comment by Super3222** [comment]
I know...

**Pull request closed without merging**
