### PR TITLE
Ports /tg/'s CLF3 buff to increase potency. Additionally makes phlogistion slightly more potent, fixes a typo in the pyrosium chem's description, and makes pyrosium and cyroxadone not completely useless.

### PR DESCRIPTION
**Pull request by ghost**
Okay.

First off, it ports this: https://github.com/tgstation/-tg-station/pull/16280

Because CLF3 was sort of hilariously dinky before and didn't do shit to plating. Now it's an actual dangerous chem.

Phlogistion is now mildly more lethal in order to contend with the buffed CLF3, applying one more firestack and doing slightly more damage. In testing, this makes pyrosium lethal, but not ungodly overpowered, meaning that one 15u syringe still won't be an instant GG unlike certain chems. Mixing it with a stun of some kind, like neurotoxin, will do the trick though.

Fixes a typo in Pyrosium chem's description saying that it cooled reagents, which was cyroxadone's job.

Actually makes pyrosium and cyroxadone more potent in heating/cooling so that they aren't entirely garbage and useless.

Yes i've tested, it's not gamebreakingly overpowered from what i've seen, it just makes some unused chems more potent and makes phlog and CLF3 mildly lethal instead of making your balls slightly warm.

FAQ:

'BUT CLF3 IS OVERPOWERED NOW'

It's a fucking chem that melts concrete into soup. It's gonna melt some tiles because a maxcap clf3 foam grenade right now will break two tiles and make you slightly toasty. 

'BUT PHLOG IS OVERPOWERED NOW'

You're on fire. You being on fire should be an actual worry instead of 'let me just take a lesiurely stroll.' It's not going to kill you instantly or anything, from what i've seen 15u phlog will do 10-20 more damage than it used to, meaning you actually have to go to medical.

Neurotoxin + Pleuflora will always trump it in the end.

### CODE REVIEW

**Comment by ghost** [comment]
travis y u fail

what i do

**Comment by ShadowDeath6** [comment]
> clf3 
> unused

Literally every chemist will make it, and last I checked it was already pretty potent to begin with.

**Comment by Cruix** [comment]
Woo Adam's using Git again!

It failed because there is a + that should not be there on line 63.

**Comment by ghost** [comment]
I removed the +.
It was actually surprisingly impotent prior, a 15u syringe of the shit that melts concrete into putty wouldn't even put you in orange.

**Comment by EMT321** [comment]
I used to use a 5u spray of ClF3 to keep people from breaking into chemistry to make lube - it did so little damage that people would finish making their chems before trying to extinguish it.

**Comment by ghost** [comment]
Now the spraybottle not only makes a 3x3 fireball for each square traveled, but using it in a grenade will likely fuck the whole room over like phlog does.

It's also more potent on contact as well due to more firestacks.

I'll see about buffing fire all around since rn fire does barely anything.

**Comment by Notamaniac** [comment]
Cryostylane not cyroxadone, crox is the healing chem

**Comment by Notamaniac** [comment]
You  mean cryostylane in the PR right? Cryoxadone is the healing chem.

**Comment by ghost** [comment]
yes that

**Comment by oisin100** [comment]
So make last whisper even stronger?

**Comment by ghost** [comment]
Oh for fuck's sake, oisin.

'Wahh wahh muh last whisper' is not a valid argument.

Yes, there is a chem deathmix that b1g discovered.

This is a good thing.

Last whisper will kill you fucking dead anyway- I tested this out using their mix and speed of death was only slightly-perhaps a second-faster.

Two, not everyone knows that mix-five people do tops-and it's a really bad mix in comparison to the shit you can make-so it's not an unbalanced mix.

You want an unbalanced mix, go look at the one that makes you instantly gib. That's a fun one.

I cannot stress how annoying an argument of 'oh lol make last whisper even stronger then xxxddddd' is.

It's not making it that much stronger, it makes some previously sort of pathetic chems useful again, and last whisper is a really shitty crude mix in the first place.

**Comment by ShadowDeath6** [comment]
> LW kills you in 3 seconds
> shortens by a second
> die in 2 seconds now
> xxxddddd

**Comment by EMT321** [comment]
I can agree with Adam: LW is a needlessly involved way to kill someone.

**Comment by AsV9** [comment]
Has this been tested to make sure it works as intended?

**Comment by AsV9** [comment]
@AdamElTablawy pls

**Comment by ghost** [comment]
ye it works fine from what i saw

nothing gamebreaking 

feel free to merge or whatevs

**Comment by ShadowDeath6** [comment]
> > > > > > > > > > unironically buffing the most powergamey job outside of science

**Comment by ghost** [comment]
fuck off shadow this is barely even a buff

hell you can't even use clf3 spraybottle anymore without being caught in the fire

**Pull request merged**
