### PR TITLE
Remove chaplains one source of fun - Bible Duping

### PR DESCRIPTION
**Pull request by ToGWtF**
### Intent of your Pull Request

Removes fun. Also removes lag.

### CODE REVIEW

**Comment by george99g** [comment]
What do you mean by, "removes fun"?

**Comment by ToGWtF** [comment]
This kind of !Fun!

http://puu.sh/jIl54/a45f5bf983.png

**Comment by george99g** [comment]
Seems good!

**Comment by ShadowDeath6** [comment]
;_;

**Pull request merged**
