### PR TITLE
Adding Survival Capsule that Adam likes so much from /tg/. 

### PR DESCRIPTION
**Pull request by PineappleWolf**
It was already in the code just not implemented in any way to get it.

GG.

Costs 700 points. Can be adjusted, just grabbed a mid-important level.

### CODE REVIEW

**Comment by Time-Green** [comment]
Err, what is it?
Is it a pill that makes you temporarily invincible?
Or is it some sort of nuke bunker?

**Comment by ghost** [comment]
Activate inhand.

Spawns a small wooden room with a sleeper, a microwave, a comfy chair, a table, and a box of donk pockets.

It's very cozy and very nice.

**Comment by oisin100** [comment]
How long does it take to spawn it? If it spawns instantly i could see there being some balance issues... And i assume it only works on the mining Z-Level?

**Comment by DavidEdwards** [comment]
Well. I'm willing to give this a go.

**Comment by Super3222** [comment]
it's gunna be a fun time

**Comment by ShadowDeath6** [comment]
> sleeper
> Actaully mining with other people
> Implying you have medical access

**Comment by X-TheDark** [comment]
Make it impossible to activate on station Z-level.

**Pull request merged**
