### PR TITLE
New Traitor Bundle called "The Professional"

### PR DESCRIPTION
**Pull request by Super3222**
The incorporated idea is from the link below. I remember it being one of the first suggestions I read.
http://forums.yogstation.net/index.php?threads/new-traitor-item-ideas.5097/
New Traitor bundle containing:
-slightly armored executive suit
-nitrite gloves
-syndicate pistol and suppressor 
-syndicate brand dufflebag with more ammo (3 10mm mags), more explosives (3 C4s), and body bags (3 of those) for a quick get away

### CODE REVIEW

**Comment by Super3222** [comment]
Something broke it seems, time to fix it.

**Comment by ghost** [comment]
already exists idiot

**Comment by Super3222** [comment]
> already exists idiot

I realized the guns bundle was similar to it in the process of making it, but I still liked the aspect with a silenced pistol instead of a loud as fuck revolver.

**Comment by McShooterJr** [comment]
jeezus Adam, Dont have to be such a dickhead. Also I really like this idea. There is a bundle kind of like it already, but it doesnt have anywhere near the amount of features. I say this should replace it.

**Pull request merged**
