### PR TITLE
Adds Medihover borg sprite

### PR DESCRIPTION
**Pull request by utahclock**
Adds V.2 medihover borg sprite

### CODE REVIEW

**Comment by Notamaniac** [comment]
The eye sprite needs to be a separate icon rather than drawn on the borg. Also the outline sprite is a bit too purple for my taste, I'd personally darken it to blue but that's my opinion.

The reduced rocking looks a lot better though.

**Comment by utahclock** [comment]
where can i find the borg eye file then. i dont see it anywhere....

**Comment by Notamaniac** [comment]
Just make the icon in the robots file, with it as a normal movie and label it eyes-medihover so the coders know what it is. It might help to overlay the normal borg with a layer using GIMP or a program with layers so you can easily do it for the animation states without having to check back and fro

**Comment by utahclock** [comment]
right found the other eyes in the dmi dont know how i missed those, eyes are done now. Ill also need a robo transform too. Ill work on that now and push version 3 soon. with bluer outline too.

**Comment by utahclock** [comment]
closing for version 3.

**Pull request closed without merging**
