### PR TITLE
Makes wet/lubed floors SUPER obvious

### PR DESCRIPTION
**Pull request by X-TheDark**
Refer to issue #993.
### Intent of your Pull Request

Shared by both water/lube, so you can't really tell which is which.

wetness

If anyone wants to do a better overlay, feel free. I just upped the Alpha by about 3.5 times.

:cl: X-TheDark
tweak: Wet floors (Water/Lube) are now MUCH more visible.
/:cl:

### CODE REVIEW

**Comment by EMT321** [comment]
Thank you, so very much.

**Comment by Kmc2000** [comment]
RIP traitor janiborg

**Comment by Groudonmaster** [comment]
Too hard of a counter :-1: x :100:

**Comment by EMT321** [comment]
People can now see lube while moving != game breaking change. Lube has little to no counterplay. This still allows for lube in maintenance/darkened areas while not requiring you to shut the gravity off or wear magboots every time someone in medbay rolls traitor.

Earlier today on Rev a single lubed floor tile in the middle of the hall allowed enough time for the luber to come back and kill 4 people before they had a chance to stand up.

As to the objection "Just look harder, you suck at situational awareness": lube and water is only visible if you are actively slowly looking for it. I will call bullshit on people running at speed being able to see those dozen changed pixels on a single tile.

TGstation made it more visible, and cut down on lubepocalypse every round. Especially given how one can still spray maint and drag/push people onto lubed tiles, this will not make lube unusable. It will prevent it being a hard counter to the station, as it has been of late.

**Comment by EMT321** [comment]
Plus, given the average level of awareness on the server, people are going to keep running into it. For reference: all janitor signs demarcating wet floors.

**Comment by X-TheDark** [comment]
Honestly, maybe just adding a pair or two of security magboots like Adam suggested would be enough (they'd have slowdown, so you'd need to trade speed for the ability to not be slipped).

**Comment by EMT321** [comment]
TGstation did what they did to prevent lube being a hard counter to the crew as a whole. That's why I wholly agree with making it more visible, so it comes down to player error rather then just having one of 3 roundstart items.

**Comment by ghost** [comment]
merge it, this is not unbalanced

it works the same for both water AND lube

meaning you can see it instead of it being a tiny, impossible to spot dark tile

observant players will notice, not others

lube and water share the same sprite, so if you try to walk on water OOPS ITS LUBE and you go sailing

**Comment by DavidEdwards** [comment]
Lets give it a try! I'm a little bit skeptical about making it more dark, but we can always revert.

**Pull request merged**
