### PR TITLE
Porting TGUI systems and refactors, includes cargotgui

### PR DESCRIPTION
**Pull request by Super3222**
If you are coming here, you've come to the right place. Ignore #1110 and #1106.
### Intent of your Pull Request

Implements cargo tgui, stock market system, file arrangements for the shuttles, moved scattered files concerning cargo into one folder under modules, implements /tg/s shuttle code refactors, adds the new cargo console to the map. Additionally humans now have lungs which can determine when they can speak, and secret documents can now be copied in cargo.

Special thanks to:
@neersighted
@MrStonedOne 
@Iamgoofball 
@Core0verload 
@bgobandit

and other [/tg/ coders](https://github.com/tgstation/-tg-station) who have made corrections, refactors, and additions here and there to the code.
- [x] Fix the last few errors with the tgui system
-  [x] Remove the procs called for testing. delete my own comments as well
-  [ ] Fix merge conflcits
-  [ ] Double check literally everything.
-  [ ] Make a changelog
-  [ ] Have someone else check over everything again.

### CODE REVIEW

**Comment by Cruix** [comment]
> Finally porting tgui

You are my hero.

**Comment by MacHac** [comment]
Files changed: 169
Good fucking luck :+1:

**Comment by FluffySurvivor** [comment]
:+1: :+1:
our hero

**Comment by AsV9** [comment]
I have faith

**Comment by ghost** [comment]
@Super3222 DONT LET THE DREAM DIE

**Comment by Super3222** [comment]
The dream will never die.

**Comment by Super3222** [comment]
Another step goes into the right direction guys, I'd like to thank @neersighted personally for explaining basically everything I needed to do for us to finally find the bug.

And of course we have merge conflicts. Great.

**Comment by AsV9** [comment]
hype

**Comment by Super3222** [comment]
Alright, there we go. Now to fix merge conflicts.

**Comment by Super3222** [comment]
Travis isn't checking it..

**Comment by Super3222** [comment]
And here comes the crippling depression.

**Comment by Super3222** [comment]
Christ, why.

**Comment by AsV9** [comment]
512 changed files.

wat

**Comment by Super3222** [comment]
Something went wrong.

**Comment by AsV9** [comment]
rip

**Comment by Super3222** [comment]
Yeah, it's gone now.

**Comment by MacHac** [comment]
Super.

For the love of god.
Take this shit down until you finish it so that other people can make PRs too without merge conflicts out the ass.  Please?
I understand that its a big job, but leaving a 508 file refactor PR sitting open for three weeks makes it hard to change anything of significance without getting merge conflicts.

**Comment by oisin100** [comment]
> Take this shit down until you finish it so that other people can make PRs too without merge conflicts out the ass. Please?

It wont create any conflicts till its merged...

Your branch is 12 commits behind and its editing line which have been edited in the 12 commits, Theres nothing wrong with this PR.

@MacHac

**Comment by oisin100** [comment]
This has actually been moved to a new PR however.

**Comment by neersighted** [comment]
@MacHac That is not how git works :p

**Pull request closed without merging**
