### PR TITLE
Attempts to fix orion trail bug.

### PR DESCRIPTION
**Pull request by AsV9**
Because I hate fun.

### CODE REVIEW

**Comment by TehFlaminTaco** [comment]
**-1**. Removes fun.

**Comment by Kmc2000** [comment]
:-1:  x :100: 

Removes fun

-1

**Comment by ShadowDeath6** [comment]
For what reason? :-1:

**Comment by oisin100** [comment]
**0/10**
Why so mean?

**Comment by AsV9** [comment]
oops lol totally accident

**Comment by george99g** [comment]
You forgot these labels.

**Comment by ShadowDeath6** [comment]
George you were too slow you jerk

**Comment by george99g** [comment]
Blame @AsV9

**Comment by oisin100** [comment]
> oops lol totally accident

Totally... I totally believe you...

**Pull request merged**
