### PR TITLE
Thrown Spells

### PR DESCRIPTION
**Pull request by TehFlaminTaco**
Changes the Fireball spell to be thrown, instead of dumbfired.
Code placed here and there to make it possible to hook into throwing
things better.
:cl:
tweak: Fireball changed from Dumbfire to Thrown.
/:cl:

### CODE REVIEW

**Comment by FluffySurvivor** [comment]
all the :+1:

**Comment by ShadowDeath6** [comment]
Does this automatically set you to throwmode upon casting?

**Comment by TehFlaminTaco** [comment]
Yep.

**Comment by DavidEdwards** [comment]
Looks very cool!

**Comment by Groudonmaster** [comment]
Rip the days of abusing 0 cooldown fireball as an admin

**Pull request merged**
