### PR TITLE
Removes borg christmas hats.

### PR DESCRIPTION
**Pull request by AsV9**
ayy lmao

### CODE REVIEW

**Comment by X-TheDark** [comment]
nofun

**Comment by Super3222** [comment]
The remove fun tag is so well placed here.

but than again Christmas has been over for awhile

**Comment by ShadowDeath6** [comment]
Christmas died when Blukey removed his christmas avatar ;_;

Thanks for listening to the forums.

**Comment by TehFlaminTaco** [comment]
Seems good.

**Comment by AsV9** [comment]
Here I am hoping I didn't accidentally delete a sprite.

**Pull request merged**
