### PR TITLE
Adds client verb to view antag weight

### PR DESCRIPTION
**Pull request by MacHac**
### Intent of Pull Request

Adds a verb which displays information about your current antagonist weight.  This includes your exact weight, and an approximation of how many rounds you'll have to wait to get antagonist.

I'm an SQL noob, so someone needs to check my work here.  I can't really test it because I don't have DB access.

### CODE REVIEW

**Comment by ghost** [comment]
M E R G E
E
R
G
E

**Comment by FluffySurvivor** [comment]
HOLY SHIT

:+1:  :+1:  :+1:

S P E E D M E R G E

**Comment by Kmc2000** [comment]
:yes: 

Gimmegimmegimme

**Comment by TehFlaminTaco** [comment]
Many strings aren't sanitized, EZ as fuck SQL injection when?

**Comment by oisin100** [comment]
> Many strings aren't sanitized, EZ as fuck SQL injection when?

Cant use special characters in Ckeys.

**Comment by Cruix** [comment]
sanitize it anyway, it's a big enough danger. If someone can find out how do it they could literally drop every single table in the database, or ban everyone, or set random values to "faggot".

**Comment by AsV9** [comment]
This has to be sanitized before I merge this.

**Comment by oisin100** [comment]
> sanitize it anyway, it's a big enough danger. If someone can find out how do it they could literally drop every single table in the database, or ban everyone, or set random values to "faggot".

None of the SQL statements are sanitized. Eg, Bans, credits, notes.

**Comment by MacHac** [comment]
I basically copied the commands verbatim from the code that actually handles the weighting.  I can sanitize, but nothing else in the codebase is sanitized.

Edit: It occurs to me that I can't sanitize anything, since the database entries aren't sanitized.  We would need to rebuild our entire database + recode everything in the code referencing SQL or risk players with spaces in their names losing their entries.

I think that the danger is reasonably low that anyone will be able to get a dangerous name, which is probably what the people who wrote every other bit of sql code in the game (Including Kn0ss0s) thought.

**Comment by DavidEdwards** [comment]
Ckeys are safe. This however isn't safe to merge because a !FUN! player can spam the verb and probably crash the server with SQL queries. That needs to be regulated. Once per round is plenty enough. So this could be cached in /client for example.

**Comment by Iamgoofball** [comment]
You should be told this after antags are assigned if you dont get antag instead, or when you connect

**Comment by DavidEdwards** [comment]
@Iamgoofball  Yes, even better. 

The value doesn't change except through the antag selection process.

@MacHac You could edit my antag change to set an antag weight value in the /client. Do **not** print the value out everytime it changes in the selection process. The user could end up with over 10 lines of antag processing printed out if it is a big round. They will see what kind of round it is before it has even started.

**Pull request merged**
