### PR TITLE
Merges malf-AI with traitor AI. Removes the malf AI mode.

### PR DESCRIPTION
**Pull request by AsV9**
This is a port of tgstation/-tg-station#13759.

I will now shamelessly steal their pull message;
"Merges Malf AI and traitor AI into a single antag type, no longer has its own mode #13759

...

And adds malf powers to traitor AIs. Malf is a dull mode that is usually 20-40 minutes of nothing followed by a few minutes of the same AI core assault by the handful of people with enough gear or access to do anything. Then the round ends. It's also a redundant mode considering AIs can and do go rogue and murder everyone in every other mode.

Pseduo-malf AI in traitor/DA rounds will open up possibilities like the AI working with badguys, badguys helping to stop the AI from nuking everything, stuff actually happening while the AI is hacking APCs, etc. It will also mean that AIs without cyborgs are not completely fucked.

Traitor AIs start with only 50 points to spend, but gain 10 more for every APC they hack.

For 180 points they can buy a nuke on a 400 second timer and blow the station up (if they live through the timer). This power triggers the usual malf sounds/runtime alert/ANGRY RED TILES."

Also I have no idea what I'm doing regarding gamemodes. So please don't murder me.

### CODE REVIEW

**Comment by oisin100** [comment]
So, Does the AI get the objectives to blow up the station or something?
Im not sure how i like the fixed timer for blowing up the station. I think we should keep the core mechanics of Malf AI, where the more APC's you hack the quicker you blow shit up.

**Comment by AsV9** [comment]
Currently you need to hack **at least** 13 APCs to get the nuke and that is if you don't use any of the toys. I don't remember how far 13 APCs get you with the current malf system.

**Comment by ghost** [comment]
13 apc's is like 100 seconds so.

Make sure that escaping to mining counts for escape alive if nuke is active.

**Comment by AsV9** [comment]
Also I polled the players ingame about this and they were generally positive to this change.

@AdamElTablawy If the AI gets killed which happens a lot right now, the nuke is disabled.

**Comment by ghost** [comment]
malf almost never dies

the station blew up, if they're on mining they escaped alive

**Comment by FluffySurvivor** [comment]
won't this make the newmalf ai mechanics very rare?

**Comment by AsV9** [comment]
Malf dies a lot mate. I'm not sure what you're onto. You have people running around with traitor gear and changeling sometimes so actually surviving is going to be hard.

Also, most malf AIs that win work their way down to like 200 seconds before going delta, the bomb is now _always_ 450 seconds regardless of what happens.

**Comment by ghost** [comment]
fine but at least make shunting increase time so you can't cheese it

**Comment by AsV9** [comment]
30 BYOND seconds == 60 realtime seconds. ;^)

**Comment by imtakingabreakdontatme** [comment]
Because Doomsday Device is tied to the AI core, if the AI shunts you can still disable the nuke by killing the core

**Comment by imtakingabreakdontatme** [comment]
https://github.com/tgstation/-tg-station/pull/13665

You'll want this PR as well as the line above it about forceend if you want traitors to succeed be fleeing to mining

**Comment by Cruix** [comment]
You'll have to give special consideration to whether or not traitors should be allowed to get their survive/escape objectives if they survive by hiding in the chef's fridge.

**Comment by imtakingabreakdontatme** [comment]
The above code I linked doesnt actually include a Z check (in fact it overrides it) so you wont need anything extra for people who somehow survive on z1

**Comment by Cruix** [comment]
I know, I'm talking about if you _want_ to let traitors all scramble in desperation for the fridge until one of them decides to blow it up just to ruin everyone's greentext.

**Pull request merged**
