### PR TITLE
Super Bug Fix

### PR DESCRIPTION
**Pull request by ghost**
Refer to issue #0.
### Intent of your Pull Request

Fixes all bugs.  : ^)

### CODE REVIEW

**Comment by Time-Green** [comment]
ALL???
Oh wait, you just deleted about 10000 files. That is an odd way of doing that. But there are no bugs for sure

**Comment by ghost** [comment]
Just about.

**Comment by ShadowDeath6** [comment]
Merge this

**Comment by X-TheDark** [comment]
Not even going to entertain this shit.

**Comment by X-TheDark** [comment]
Also, no, MEME ZONE PR usually have more effort than this.

**Comment by ShadowDeath6** [comment]
> literally only one meme zone pr other than this
> effort

**Comment by Groudonmaster** [comment]
I mean, technically he's not wrong.

**Comment by oisin100** [comment]
Why was this closed? This was a great fix!

**Pull request closed without merging**
