### PR TITLE
Syndiborg buff

### PR DESCRIPTION
**Pull request by X-TheDark**
Issue #271 

Syndiborgs now come with plethora of buffs:
1. LMG recharges every 2 ticks (instead of 5), supports firing modes of 1/3/5 rounds. Examining the Cyborg LMG now tells you how much ammo it has in it. Maximum capacity is 30 (not changed, just readily apparent now).
2. Grenade Launcher replicates 1 shot every 6 seconds when activated and standing still (500 energy per replicated shell);
3. Emag added (no energy usage);
4. Crowbar changed to red (no energy usage still);
5. Energy Sword cost down to 150 (from 500);
6. VTEC module comes added;

Flash is unchanged, still works the same way it did. 
As a sidenote, after this PR, energy weapons will support burst_size properly.

I expect this to make Syndicate Cyborgs completely broken.

**ANY ADDITIONAL COMMENTS/THINGS TO ADD WELCOME**

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
Tfw no ebow

Looks good, syndieborgs SHOULD be broken. They suck right now.

**Comment by Alek2ander** [comment]
> syndieborgs SHOULD be broken

They are already broken.
Additional teammate who is unstunnable by normal weapons, blocks weapon fire, suffers no slowdowns, is always fire and spaceproof, has all access, and can solo-destroy the AI. Apparently that's not OP enough.

**Comment by X-TheDark** [comment]
What do you mean blocks weapon fire? Unless you mean acting as a bullet magnet, other than that, it doesn't reflect any bullets.

**Comment by DavidEdwards** [comment]
> has all access, and can solo-destroy the AI

That is certainly dangerous. Why is it never taken?

**Comment by DavidEdwards** [comment]
> has all access, and can solo-destroy the AI

That certainly is dangerous. Why is it never taken?

**Comment by ShadowDeath6** [comment]
> Why is it never taken?

Because it sucks against fighting crew. An 80 TC AI kill isn't worth it when you can buy 2 c4 and an eshield for the same effect.

**Comment by ghost** [comment]
It's terrible V crew, right now.

Not to mention, the moment ops hit the station and they're declared, AI just turns off environmental control, GG.

The AI core we have is in the center of the station, not on a sat like every other core, meaning gee fucking gee.

Not to mention that borgs are only ever bought during WAR!, where the crew knows they're coming and all have flashes.

**Comment by X-TheDark** [comment]
Either way, the borg should have options now, cutting bolts if AI dicks him over (doesn't use energy) and crowbaring while defending itself with infinite LMG.

**Comment by X-TheDark** [comment]
Reverted the infinite ammo LMG, back to regular energy consumption, just faster recharge (2 ticks instead of 5).

**Pull request merged**
