### PR TITLE
Adds new preferences

### PR DESCRIPTION
**Pull request by Time-Green**
Adds preferences for
+Borer
+Xenomorph
+Slaughter Demon

Does exactly as it says above. Adds some more specific preferences. I feel like Slaughter Demon has way more potential for the future. So I decided to throw it in aswell.

> mfw i didn't get 100 errors
> (Also changed the message when actual Xenomorphs spawn on the station to give the crew a little more chance of not getting disintegrated)

### CODE REVIEW

**Comment by timkoster1** [comment]
Is it changelog worthy?

**Comment by Super3222** [comment]
Could you keep BE_ALIEN instead of adding BE_OTHER? For miscellaneous use in the future.

Other doesn't specify much, and if there's a new antagonist added than it'd have its own pref.

**Comment by Time-Green** [comment]
Almost everything falls under alien. Also the things already listed in preferences. Thats why I changed it.

**Comment by Super3222** [comment]
Yeah, I know aliens fall under aliens. It's just you are making specific preference checks for a few antags/mobs, and we could still need a BE_ALIEN for specific miscellaneous alien antags.

**Comment by Time-Green** [comment]
Thats where the "other" is for. It's made for the smaller midround antags that were first part of the GIANT alien pref.

**Comment by Super3222** [comment]
That's the point I'm trying to get out of you Tim. You've moved smaller midround alien antags to a preference which says BE_OTHER, and that doesn't state much at all. Small alien antags in my opinion should be in something that says BE_ALIEN.

It's confusing, and eventually we're probably going to have a big list division dividing the mains from the midrounds. So if I want to be a nonalien miscellaneous antag, and it's under BE_OTHER, while an alien antag is under there, the problem you're having will just arise again and they'll want them separate.

**Comment by Time-Green** [comment]
Ok, I get it.
I'll change it tomorrow
Aaand done. Sorry for the commit spam. I edited straight in of github

**Comment by Super3222** [comment]
> using github to edit anything ever other than a comment

bad times my friend

**Comment by Time-Green** [comment]
I was to lazy to go and do it the hardway. So why the hell not?

**Comment by AsV9** [comment]
\merge\ /conflicts/

**Comment by Time-Green** [comment]
Didnt't have that before. I'll fix it

**Comment by Time-Green** [comment]
Travis you lazy fuck

**Comment by oisin100** [comment]
Nuffin wrong with Travis. Fix yer conflicts and he'll wake up.

**Comment by Time-Green** [comment]
There is a conflict when merging a file
That has not changed. You can basicly remove all spider.dm commits, because it changes nothing right now from the original.
I don't know how tho...

**Comment by Time-Green** [comment]
Ok, this messed up hard.
I am gonna close this and make a new PR

**Pull request closed without merging**
