### PR TITLE
Shadowpeople fix

### PR DESCRIPTION
**Pull request by MacHac**
Refer to issue #475.
### Intent of Pull Request

+Shadow people can now see in the dark.
-Shadow people can not use guns

This pull request modifies shadow people so that they act more like (gimped) shadowlings.  They can now see naturally in the dark like shadowlings, and can no longer fire guns as the muzzle flash would wound them, like shadowlings.

NOTE: Adam said in the comments of the original report that the lack of darksight was intentional.  However, upon examining the code, I noticed line 340 in code/modules/mob/living/carbon/human/species_types.dm, which suggests otherwise, so I put together a fix anyway.

### CODE REVIEW

**Comment by oisin100** [comment]
Hmm not using guns sounds like a major nerf... Maybe make them regen in the dark?

**Comment by MacHac** [comment]
I just copied that over from the shadowling code.  They now have the exact same attributes as shadowlings.

They already regen in the dark.

**Comment by oisin100** [comment]
> They already regen in the dark.

They do? My bad. Never played shadowpeople before..

**Comment by MacHac** [comment]
Not many people do lol.  They kind of suck even with this patch, I think they're intended to punish those who screw around and get mutated.

**Comment by ShadowDeath6** [comment]
They're only available through getting lucky with xenobio fuckery or magic mirrors.

**Comment by DavidEdwards** [comment]
Are there any concerns with this PR?

**Comment by oisin100** [comment]
Sounds good to me. Just fix the conflicts!

**Comment by MacHac** [comment]
Closed and reopened to fix odd merge conflict bug.

**Pull request closed without merging**
