### PR TITLE
Ronald McDonald OUTFIT! Mask + Costume

### PR DESCRIPTION
**Pull request by Super3222**
I'm an idiot... but anyway..

http://forums.yogstation.net/index.php?threads/ronald-mcdonald-costume.8507/
Adding in a RonaldMcDonald costume + mask.
The mask can be created by pressing Z with the original clown mask in your hand. (Choose "The Mascot")
The costume can be retrieved by putting a coin in the autodrobe and selecting 'ronald mcdonald costume'.
Unfortunately still needs some work... the following icons need submissions:
an icon for the suit when its on someone (has)
an icon for when the suit is in someones hand on the hud (has)
an icon for when the mask is in someones hand on the hud (has)
an icon for when the mask is in someones hand in the game (none) - has been managed with default clown mask icon
an icon for when the suit is in someones hand in the game (none) - has been managed with default clown mask icon

The icon for the costume has some problems it's self. When facing east or west, they leave out some of the mobs feet/legs.

morph mask
inside vendi

### CODE REVIEW

**Comment by AsV9** [comment]
Curse you for taking #100 
Damn it.

**Comment by Super3222** [comment]
> Curse you for taking #100 

It was my ultimate plan all along muwahahahaha. :^ )

HONK

**Comment by Super3222** [comment]
mcdonald costume icon

You can see that the icon is a bit off (costume).

**Comment by AsV9** [comment]
It looks weird when you fall on your gif? Any chance that could be improved?

**Comment by Hydre** [comment]
Yeah it kinda looks like someone threw up over the lower half of the sprite when he falls down

**Comment by Super3222** [comment]
@ASV9 @Hydre The program which I used to record myself just had poor quality. You can look at (and even download) the sprite here. http://forums.yogstation.net/index.php?threads/ronald-mcdonald-costume.8507/

**Comment by Hydre** [comment]
Ayy all good

**Comment by AsV9** [comment]
:+1:

**Pull request merged**
