### PR TITLE
Sec updates. Secway keys and RP

### PR DESCRIPTION
**Pull request by oisin100**
Related to #224 And #230 

Sec now dont start with their helmet, armor or stunbaton. Just the basic flash and hudglasses. 
Now stun batons and handcuffs spawn in their security closet so they have to involve in the obscure thing called "Roleplay" and put their armor on.

Also, Warden now starts with his secway key and a spare key is also place in his locker.

### CODE REVIEW

**Comment by Alek2ander** [comment]
What about latejoin sec? Do they have to get involved in the obscure thing called "getting dunked in arrivals"?

**Comment by oisin100** [comment]
Yup. They can go to the office just beside arrivals and suit up with everything they need.

**Comment by Cruix** [comment]
Have you tested this? It looks like officers will not spawn with a taser, since by default it spawns in the suit storage slot, and without wearing armor, the taser will register that it can't be held and delete itself. You could just make tasers spawn in the officer's backpack instead.

**Comment by DavidEdwards** [comment]
That could be annoying for the late joiners. There's no guarantee that the
lockers contain something. You could just leave that as "IC". But I'd
rather not antagonise the player base. Security get a bad rap as it is!
I'll leave this one open for feedback.

> ## 
> 
> MfG
> David Edwards
> Android Software Engineer

**Comment by oisin100** [comment]
Oh shit. I completley forgot about the tazer... I can make it spawn in the backpack yea. If theres no armor in the security closet at arrivals you can always just go straight up to sec 10 seconds walk and get one.. All in all i dont fully agree with not starting with armour.. i was just reading through the issue and saw that. I do think they should always start with the glasses though.

**Comment by AsV9** [comment]
Eh. :-1: from me. I don't like forcing people to go suit up, it's just going to get them annoyed.

**Comment by oisin100** [comment]
Alright, Re-added armor and stun-baton with cuffs but the security locker is still buffed i should probably recreate this PR with just the warden's keys depends on whether or not your fussy about how many commits there are like TG is...

**Comment by Super3222** [comment]
I like Warden finally getting his secway key, but wouldn't it be more convenient to place it on the map like the jaintors key?

**Comment by oisin100** [comment]
It is. He gets one and a spare is placed in his locker.

**Comment by oisin100** [comment]
Closing this for less commits and only secway keys.

**Pull request closed without merging**
