### PR TITLE
Adds Medihover borg sprites

### PR DESCRIPTION
**Pull request by utahclock**
v.3 medihover borg - with correct file this time

### CODE REVIEW

**Comment by Notamaniac** [comment]
Minor issue, your eye overlay is going to be static while the borg bobs up and down. I'm not sure if that's going to be noticeable in motion, but if you've got the time make four animation frames and drop the eyes one pixel, another pixel, then up one pixel, naturally with the same delays as the borg animation

Oh and if you know how try to squash those commits. Not sure what type of git you're using, but eph might get a little mad with the commit spam.

**Comment by oisin100** [comment]
Adding the icon to the DMI wont allow people to use the sprite when they choose what borg type they want. You need to do some actual coding if you want to add this to the actual list of usable sprites.

Unless of course your replacing an already existing mediborg sprite.

**Comment by utahclock** [comment]
Right oisin i dont know where the code file is to edit that for mediborg , nor if im sure if i could. i know very very minor coding. thats why ive asked for coder help.

**Comment by utahclock** [comment]
adding 1 frame to medihover eyes

**Comment by oisin100** [comment]
Its not hard to add one. You can do it at line 209 in the code\modules\mob\living\silicon\robot.dm file. The icon choosing for the mediborg isnt really set up to have multiple icons. You'll have to look at the if statement on line 220 and see if you can replicate the code there.

**Pull request closed without merging**
