### PR TITLE
Command hardsuit

### PR DESCRIPTION
**Pull request by Time-Green**
Adds command hardsuits to command EVA
-Moderate armor
-Pretty fast for a hardsuit
-dank kmc sprite. (+ my amazing spriting to fix a few errors and missing icons)
#221

:cl:Time-Green
rscadd: Added command EVA suits to command EVA
/:cl:

### CODE REVIEW

**Comment by Super3222** [comment]
:+1: Nice work.

**Comment by ghost** [comment]
It looks like the dong of an albino cthulhu and also why extra hardsuits when every head role that should be in space has the hardsuit to do it

This will just encourage overly flamboyant HoPs to jetpack around in space while looking like the hatesex lovechild of cthulhu, MS paint and a pez dispenser

**Comment by oisin100** [comment]
Nice, You included all your `Thumb.db` files!
You might want to turn off your thumbnail caching!

**Comment by Time-Green** [comment]
Yeah...
I thought I un-included them.
Will that break stuff?

And adam, I'll take that as a compliment

**Comment by Kmc2000** [comment]
Adam that was the single best description i have ever heard on github ever.

**Comment by oisin100** [comment]
@timkoster1 Can you post some screenshots of the hardsuits?

**Comment by Time-Green** [comment]
http://imgur.com/a/nRlYH
I will be fixing one more error in the spriting.

**Comment by DavidEdwards** [comment]
I don't see any issues with it. Anyone else?

**Comment by ShadowDeath6** [comment]
Why is the helmet so small

**Comment by ghost** [comment]
@DavidEdwards 

why, though

heads of staff already have hardsuits should they be space-needed and you can give the CMO a medical hardsuit if needed, so this is really only for the RD and HoP and that's fairly useless, also the sprite is horrible

**Comment by Time-Green** [comment]
Adam. Command can already fly to fucking space. This just replaces the boring EVA suits with cooler and betters ones. That's it.

**Comment by ShadowDeath6** [comment]
> cooler 

That's objective. 

It should have higher slowdown. Being a direct upgrade is too memey.

**Comment by FluffySurvivor** [comment]
why the fuck would you fly to space as a head if you get banned for it

**Comment by Time-Green** [comment]
It was intented for emergencies.
This does not change anything with that.
There is already a command eva with suits, this just replaces them with hardsuits.

**Comment by Time-Green** [comment]
@oisin100 Any plans on merging this? If yes I will fix the conflict

**Comment by oisin100** [comment]
Are these suits replacing the suits to the right of Main EVA? If so, I dont see whats wrong here, Just a new texture and some slight damage values.

Fix the conflicts.

**Comment by Time-Green** [comment]
Am I not seeing something?
I fixed all the differences with icon files and normal files. Still this thing keeps creaming has a conflict. So excuse me for the commit spam, but I am about to try everything
Could it have something to do with map changes?

**Comment by oisin100** [comment]
Its probably the map changes.

**Comment by timkoster1** [comment]
@oisin100 I redid the map, and well.
I think I am just going to throw this away, not like it was that much effort

**Comment by Time-Green** [comment]
I am actually going to close this. I kinda lost interest and when I regain it, I'll make a better PR.

**Comment by oisin100** [comment]
</3

**Comment by ShadowDeath6** [comment]
rip kiddo

**Pull request closed without merging**
