### PR TITLE
Adds basic discord bot.

### PR DESCRIPTION
**Pull request by oisin100**
Adds a discord bot. Required additional setup when merged.

PS: Sorry for the extreme amount of changes Python doesent have the native support to work HTTPS Post requests.

The Requests library is licensed under Apache Licence

### CODE REVIEW

**Comment by oisin100** [comment]
Fuck, I forgot to add the actual licence.

**Comment by oisin100** [comment]
Ill be using the requests library in the statistics system anyway.

**Comment by AsV9** [comment]
speedmerge @DavidEdwards

**Comment by DavidEdwards** [comment]
Not sure what it is you pushed that for xD

I'll fiddle it around like we discussed.

**Comment by DavidEdwards** [comment]
Since I can't push to your repository to fix it, I'll simply merge your code as it is now and edit it directly.

**Comment by oisin100** [comment]
Oh! sorry, I forgot to push my commit...

**Pull request merged**
