### PR TITLE
Security Magboots and Engineers will get magboots

### PR DESCRIPTION
**Pull request by Super3222**
Refer to issue #1079 and #993.
### Intent of your Pull Request

This will give security combat-issued magboots. Why? Because as security on a space station, they are essentially supposed to be enabled to handle space-like transitions and issues without worrying about drifting off from space wind

Combat magboots are superior to normal magboots in speed, but lesser than the advanced magboots. Because NT is cheap.

Combat magboots will spawn in the security suit storage (located above wardens desk), in the centcomm commander and security suit storages, and replace the magboots that the engineer ERT gets in their own locker.

I also put a lot of thought into giving engineers magboots, and @00aquir brings up some interesting points. It made me wonder why Engineers haven't been given them before, but now they'll spawn with the engineer suit storages.
#### Changelog

:cl:Super3222
rscadd: NT is funding the production of a new magboots called "Combat Magboots". They will enable the wearer greater speed than the normal kind, but are still nothing like the CE's advanced magboots. Special thanks to UtahClock for spriting the combat magboots!
rscdel: NT's security ert and commander suit storages will no longer start with oxygen tanks.
rscadd: NT's commander and security ERT will be granted combat magboots inside of their suit storage.
rscdel: NT's engineer ERT locker will no longer start with normal magboots.
rscadd: NT's engineer ERT locker will start with combat magboots.
rscadd: Nanotrasen was willing to throw in a few stacks of space cash to allow engineers to begin the shift with classic magboots in their suit storages.
/:cl:

### CODE REVIEW

**Comment by Super3222** [comment]
Also, if a spriter could create a security version of the magboot, that'd be great.

I... I can't sprite.

**Comment by ShadowDeath6** [comment]
use nukeops magboots

**Comment by ghost** [comment]
take the normal magboot sprite but paint it light red

**Comment by Super3222** [comment]
If a spriter could do that, than that'd be great!

**Comment by utahclock** [comment]
Ive completed the combat mag boot sprites. waiting for super to get into discord so he can have files

**Comment by utahclock** [comment]
might want to rename them they arent red....

**Comment by ShadowDeath6** [comment]
can we see a pic of the magboots

**Comment by Super3222** [comment]
Sure @ShadowDeath6 
screenshot_1
screenshot_2

**Comment by FluffySurvivor** [comment]
These look like darth vader's boots. 

Can you give them some actual security light red?

**Pull request merged**
