### PR TITLE
adds Brass Knuckles and Baseball Bats

### PR DESCRIPTION
**Pull request by ToGWtF**
Refer to issue #1049 
### Intent of your Pull Request

Adds brass knuckle items. Planned to add to a single gang in replacement for switchblade for more gang individuality. ~~Currently not implemented anywhere yet~~  Given to Newton gang in place of switchblade.    Depending on reception will add them to @utahclock 's mining update as a craftable item from Copper

Adds baseball bat item, and more lethal gang version. Added to Newton gang in place of Uzi for a much much lower price. Adds weaker version (read: toolbox damage) version to crafting

todo : changelog  ,  ~~implement into gang shop~~  , implement into crafting  , figure out how to handle hulks wearing them ,  ~~remember to test if it bypasses armor or not~~  , decide if I want to fix it bypassing armor or not because that would mean fixing sleeping carp kungfu as well as it bypasses armor too

### CODE REVIEW

**Comment by FluffySurvivor** [comment]
less dmg than the switchblade and makes you look obvious, while removing the possiblity of wearing insu gloves

bad

**Comment by ToGWtF** [comment]
same damage as the switchblade, sprite is not very noticable but will show on examine, gives up insulated gloves in return for not losing your weapon to a RNG disarm spam

**Comment by ghost** [comment]
> undisarmable weapon

christ almighty

**Comment by ToGWtF** [comment]
already super low strip delay.

lower damage to RNG between 8-12 damage?

also going to cost more points than switchblades do on gang rounds

**Comment by ShadowDeath6** [comment]
> making it worse than switchblade and cost more

Keep it same damage as switchblade, if people are too autistic to only rely on le blue intent then that's their problem, stunning still works fine

**Comment by Cruix** [comment]
You should probably add "can't [disarm/grab] with brass knuckles!" messages like boxing has so people don't wonder why their disarms don't do anything.

**Comment by ToGWtF** [comment]
Disarm/Grab still works with brass knuckles.

**Comment by Cruix** [comment]
Oh

**Comment by FluffySurvivor** [comment]
how are you expecting me to drag and drop your sprite in the middle of combat?

**Comment by ToGWtF** [comment]
UPDATES:

Baseball bats for gangs that deal 24 damage and cost 15 points(Same damage as the bostaff that only costs 10 points for Sleeping Carp gang). Higher price to balance its increased knock-out chance versus the bostaffs knockout chance

Craftable 15 damage baseball bats for non-gang(Same damage as toolboxes, so not OP). Costs 15 wood, can strip arrivals/library wooden desks for the wood to craft them roundstart.

**Comment by ghost** [comment]
Fuck off don't nerf sleeping carp and toolboxes do not do 15 damage, also adding more improvised weapons is a dumbshit idea

**Comment by ghost** [comment]
If anything add baseball bats to one, specific gang and center their theme around shit like baseball bats and brass knuckles and shit, and leave sleeping carp alone

Also make the sleeping carp scroll attacks spells because they're underpowered

**Comment by ShadowDeath6** [comment]
Toolboxes do 10 damage

Pleeza no nerfo sleeping carpo

**Comment by ToGWtF** [comment]
still does less damage than a spear

**Comment by ghost** [comment]
It does three less damage than a wielded spear, can fit in backpacks or belt slots, and requires one hand. It's not a good idea.

Adding more improvised weapons is also a dumb idea-see, stunprods. It makes antags less threatening and kills the fear of being killed some, and goes against the general theme of ss13, where everything is lethal but lethal weapons aren't just lying around.

Onehanded 15% knockout chance that does the same damage as a circular saw, lit welder, butcher knife, null rod and is freely available to everyone? No. What keeps these things balanced is their low availability to general crew/fuel requirement. The spear is balanced in that it is obvious and giant, and to use it effectively you need empty hands. Baseball bat is a bad idea for general crew period.

**Comment by ShadowDeath6** [comment]
Brass knuckles is a cool idea for gangs :^)

**Comment by ToGWtF** [comment]
Cannot fit in backpacks, on belt slots, or even on back slots. Only does 10 damage when held by one hand. Does less damage (and has now embed chance or throwforce) than a spear.

**Comment by ShadowDeath6** [comment]
did you say that baseball bats can embed

**Comment by Time-Green** [comment]
It should fit in bags, and why does a bat embed?

**Comment by ToGWtF** [comment]
bat doesnt embed, doesnt fit in bags because bostaff doesnt fit in bags

**Comment by ghost** [comment]
So its a better version of the bostaff then? Way to nerf carp

**Comment by FluffySurvivor** [comment]
:-1: to craftable bats and craftable knuckledusters
:-1: to carp nerfs, seriously they're weak af atm. 
:-1: to fireaxes that replace an important gun

**Pull request closed without merging**
