### PR TITLE
adds new brig

### PR DESCRIPTION
**Pull request by utahclock**
adds new brig layout

### CODE REVIEW

**Comment by Groudonmaster** [comment]
What's with the random rwalls by interrogation?

**Comment by utahclock** [comment]
those can be  changed to normal walls

**Comment by EXOTICISME** [comment]
So many cells. Can you put firing range instead? With practice laser and such. Also the empty space at labour exit can be decorated with plants or chair for whoever want to watch the prisoner suffer.

**Comment by EMT321** [comment]
Does the detectives office get a shutter? Otherwise people can just break the glass and run in.

**Comment by utahclock** [comment]
walls change, fixed door where it was not supposed to be, added shutters to det office.

**Comment by ghost** [comment]
why is det office in sec

det is not a sec officer he's a PI get his office out of sec it's not supposed to be there for a reason

same with the lawyers

**Comment by utahclock** [comment]
@AdamElTablawy they are in brig not sec office. the lawyer is where its at so he can over see inmates. det is where its at because he needs to be able to investigate, evidence and stuff.

**Comment by utahclock** [comment]
@AdamElTablawy det and lawyer have same access as they do know which is innerbrig.

**Comment by FluffySurvivor** [comment]
Sec equipment room accesible by maint, not even protected by rwalls. 

nuff' said

**Comment by Groudonmaster** [comment]
Don't worry Utah I think you're doing a fine job

**Pull request closed without merging**
