### PR TITLE
Nerfs Keek

### LINKED ISSUE #1244: Removal of the mini-hypospray.
I personally had the mini-hypo added 2 years ago and it was all my idea. It wasn't a bad idea at the time but with the addition of goofchem and players learning how to abuse it, the mini-hypo has become beyond broken and the hypospray feature should once again remain limited to the CMO for obvious reason.

I don't need to go into details about how people can get crit and take 160~ toxin damage with only 5 units of some deadly mix. There is no counterplay against the mini-hypo, even if you catch the tiny prick message you'd be long gone and in crit in some corner of maint.

I'd even issue a challenge for someone to find a counterplay to a stimmed chemist running around hypospraying anyone in sight.

### PR DESCRIPTION
**Pull request by Cruix**
Fixes #1244
### Intent of your Pull Request

You can no longer refill minihyposprays.
#### Changelog

:cl:
tweak: The manufacturer of minihyposprays has decided that it is more profitable to charge for their products to be refilled. You can no longer refill minihyposprays.
/:cl:

### CODE REVIEW

**Comment by EMT321** [comment]
I cant honestly recall the last time I saw the minihypo's used for good.

**Comment by ParagonPrime** [comment]
that means MINIHYPO CRATES must be orderable

**Comment by EMT321** [comment]
Why not code it like goon does with their hypos: only healing chems can get put in (choosing from a list). And with 20u, its hard to OD someone.

**Comment by FluffySurvivor** [comment]
:+1:

**Pull request closed without merging**
