### PR TITLE
Rules broken are now added to ban reason

### PR DESCRIPTION
**Pull request by AsV9**
Adds a new text prompt for when bans are added which specifies which rule a player has broken.

image

Image above is nearly respective of what it looks like ingame.

[https://forums.yogstation.net/index.php?threads/vote-should-ban-reasons-have-which-rules-bans-are-based-on-stated-in-them.10454/](https://forums.yogstation.net/index.php?threads/vote-should-ban-reasons-have-which-rules-bans-are-based-on-stated-in-them.10454/)

:cl:AsV9
tweak: Slight change to bans, ban reasons will now have a rule attached to them for reference in ban appeals. 
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
Nerf ban reasons when :+1:

**Comment by Super3222** [comment]
This is a nice change. :+1:

**Comment by ghost** [comment]
What if no specific rules can be cited in the ban but they did something banworthy anyway? That happens, where someone does something very banworthy but not specifically mentioned in the rules.

**Comment by AsV9** [comment]
Then type that then. It's `as text|null` for a raisin.

**Comment by george99g** [comment]
> What if no specific rules can be cited in the ban but they did something banworthy anyway? That happens, where someone does something very banworthy but not specifically mentioned in the rules.

There's always 0.0 if they're being dicks and none of the rules cover it.

**Comment by AsV9** [comment]
The input field defaults to 0.0 so.. not really an issue.

**Comment by oisin100** [comment]
I suppose its worth a try.

**Pull request merged**
