### PR TITLE
Adds autoimplanter to nukeops cybernetic implants

### PR DESCRIPTION
**Pull request by Cruix**
### Intent of your Pull Request

:cl:
rscadd: Nukeops cybernetic implants now all come with an autoimplanter, removing the need for surgery after purchase.
/:cl:

Ported the autoinjector from @PKPenguin321

Requested by Adam.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
I'm gettin so many ports from you guys lately
:heart:

**Comment by FluffySurvivor** [comment]
Have all my :+1:

**Comment by ShadowDeath6** [comment]
Now I can get xray implants without relying on shitty people to know surgery :+1:

**Comment by Super3222** [comment]
Spoon feed the ops.

Might as well spoon feed R&D

**Comment by PKPenguin321** [comment]
Not spoon feed, it's that ops take 40 gorillion years to leave their base, and prepping a surgery for implants only extends that time. It holds back the round by more than necessary. This simply circumvents that

**Comment by ShadowDeath6** [comment]
Add autoimplanter to R&D tbh

**Comment by ghost** [comment]
why should nukeops need to do obnoxiously long surgery when they can barely leave their own shuttle iwthout shooting their cocks off

**Pull request merged**
