### PR TITLE
Detomatix cartridges no longer blow you up ever

### PR DESCRIPTION
**Pull request by X-TheDark**
Refer to issue #978 .
### Intent of your Pull Request

I love easy tweaks.

:cl: X-TheDark
rscadd: Syndicate are proud to announce their latest firmware upgrade to Detomatix. They no longer have a chance of blowing your own PDA up, ever. And they also always work. No more RNG rolls. Also no longer available during Double Agent.
/:cl:

### CODE REVIEW

**Comment by oisin100** [comment]
:+1: x :100:

**Comment by X-TheDark** [comment]
Adam suggests it always succeeding (instead of being RNG dependant on access on the PDA). Thoughts?

**Comment by oisin100** [comment]
> Adam suggests it always succeeding (instead of being RNG dependant on access on the PDA). Thoughts?

Yes. Fuck RNG forever.

**Comment by Super3222** [comment]
I agree, less RNG would be better. Especially since this item isn't all that powerful.

People may also want to buy this item for once.

**Comment by FluffySurvivor** [comment]
If you make it guaranteed, up the cost. 

Remote multiple 4 TC guaranteed paralysis+ mute + good damage is imba.

**Comment by ghost** [comment]
it's not guaranteed paralysis + mute

it rarely knocks the target out

not to mention after the first PDA bomb it is easily countered by disabling PDA messaging/dropping your PDA on the floor

PDA's are rarely used for anything aside from holding ID's anyway and most people have no issue with ditching them

**Comment by ShadowDeath6** [comment]
Can DAs get cartridges? If they can then remove them from it

**Comment by X-TheDark** [comment]
Changes in last commit:
- Removed any RNG from detonation, it always works.

Also, it's not a guaranteed knockdown. I think it has to do with armor, since it detonates with the light_damage range thing. Out of 8 HoS geared people I detmaxed, only 2-3 got knocked out.

**Comment by FluffySurvivor** [comment]
Fair enough. :+1:

**Pull request merged**
