### PR TITLE
Bag of Holding now holds EVERYTHING

### PR DESCRIPTION
**Pull request by ghost**
No more petty restrictions!

The Bag of holding, despite now requiring bluespace five, is massively buffed.

You can hold everything up to mech parts in there, and storage space is massively, massively increased-You could probably put in a whole fucking ripley chassis in there and have room for the shit to make it, too.

:cl: Adam El-Tablawy
rscadd: Bag of Holding can now hold anything imaginable and has increased space to boot.
/:cl:

### CODE REVIEW

**Comment by X-TheDark** [comment]
Are you mad? :+1:

**Comment by TehFlaminTaco** [comment]
> Not understanding how w_class works.

**Comment by Kmc2000** [comment]
Neat

M e r g e
e
r
g
e

(If it works)

**Comment by ghost** [comment]
it does work

w_class works fine @TehFlaminTaco

**Comment by Super3222** [comment]
What Taco means is that w_class 15 pretty much doesn't exist mechanic wise.

Five is the highest.

**Comment by ghost** [comment]
It was a precaution in the event of anything w_class above five being added to the game, the BoH can store it.

**Comment by TehFlaminTaco** [comment]
Fair enough. I don't see why w_class = 6 would happen, but meh.

**Comment by DavidEdwards** [comment]
Not really sure why this should be a thing

**Comment by ghost** [comment]
Because right now the bag of holding sucks ass.

To get any use out of it you need (non replenishable mind you there are a limited amout) of backpacks on hand to put items in it to store them, making it inventory management hell.

If you try to put bulky items in it it fills up super fast, which is dumb, as the intent of the boh is to hold almost anything, not hold one big thing or carry 5 bags to hold smaller shit.

So this means you don't get punished for using the boh as a normal bag, as it is now going to function as it should- a massive storage space, not a backpack full of backpacks.

**Comment by ShadowDeath6** [comment]
Giving it pretty much infinite storage space just prompts every assistant to get one and shove everything they can get their grubby hands on into it. Maybe make it like 60 or 70, not fucking 200, holy shit

**Comment by ghost** [comment]
good, bags of kleptomania shouldn't be handed out freely in the first place

**Comment by DavidEdwards** [comment]
Lets set the w_class back to 5, no need to preemptively change that. It will just confuse.

Set the max to 100 instead of 200. We can try a merge with that and see how it goes before going all out 200.

**Comment by FluffySurvivor** [comment]
Imo max stays 200 but revert w_class to 5, since there is a tech requirement increase as well.

**Comment by ghost** [comment]
HEY MERGE ME

@DavidEdwards

**Pull request merged**
