### PR TITLE
Removes Statue Room

### PR DESCRIPTION
**Pull request by ToGWtF**
Refer to issue #783
### Intent of your Pull Request

Replaced with firestafety area, making it a great hiding spot for
various antag types

img

or garden?
img

### CODE REVIEW

**Comment by Super3222** [comment]
Did you consult with @ASV9 before doing this?

This will basically delete and recreate an area in the space of #142.

**Comment by ghost** [comment]
G A R D E N

**Comment by ShadowDeath6** [comment]
bring back garden 2556
where the fuck will clown get his spare bananes now

**Comment by AsV9** [comment]
More feedback pls, this needs support before it can be merged.

**Comment by ToGWtF** [comment]
I'm going to map out the garden as well, and have a poll between the three

**Comment by FluffySurvivor** [comment]
No garden pls. We need more hiding spots for antags. 

But yes, remove trophy room pls because it made exploring space for bananium obsolete

**Pull request merged**
