### PR TITLE
Borer Rework

### PR DESCRIPTION
**Pull request by oisin100**
I wanted to make borer more fun to play so its not the same old thing every round.

With this borer rework it forces the borers to work together to get anything usefull, This is done by adding a evolution tree. Borers can work together to donate chemicals to a single tech which might costs something like 150 total chems. Once this tech is reached all borers will receive the buffs what the tech gives.

Current plan for the tech tree(Made this in 5 minutes, feel free to work out the balance issues for me.):  [Here](https://drive.google.com/file/d/0B7OvV5VTqmSYMnpYOVlvcFhpbzg/view?usp=sharing)

Goals:
- [x] Fix admins aghosting not being able to enter their body again
- [ ] Fix cult(And other conversion mechanics) converting the borer and not the host.
- [x] Get a rusty "Evolve" verb to donate chemicals. [Preview](http://prntscr.com/ax07mu)
- [ ] Add all the evolution's listed
- [ ] Remove Influence system.
- [ ] Clean up spaghetti code

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
:+1:

**Comment by oisin100** [comment]
I also want to add some ridiculously OP  end-game evolution for borers. Any ideas what?

**Comment by ghost** [comment]
:-1: 

they're a midround antag

no OP end game evolution, they're fine as is and they're not ascendant shadowlings

that being said a chemical pool to allow for use of chemicals ect is okay, but borers get chemicals extremely slowly and usually occur towards late-round due to low occurance chance so it'd more than anything end up like space ninja with not enough time to complete objectives

also the only thing that stops hosts from eating 50 sugar immediately is that borers can heal them, ect-if you have to wait to evolve that shit they have nothing to gain from you and kill you immediately

and to top it off adding more chem costs so that borers still can't use the punish ability or anything else without fucking themselves over, especially in this case where 90% of the round is donating chemicals and 10% of it is maybe using chemicals before your host evicts you

and again, while the 'HOLY SHIT THERE IS A BORER IN YOU' message shows

people will just immediately go get sugar while the borers are still evolving the necessary chems to actually defend themselves/be useful

and again, forcing yet another teamwork based antag is a shit idea and obnoxious because all teamwork based antags, without question, are extremely shitty, and people can barely play borer normally

no, this is a really bad idea, borers are going to run out of chems constantly, never be able to actually use their evolved chems because their host will as usual know that there's a borer trying to get into them due to the giant red message saying as much and go eat a bunch of sugar and if you try to leave/use chems to stop your host you still can't afford any useful chems and if you leave the host squishes you and if he's really spiteful he'll space himself and you will never be able to get back due to having no maneuverability in space and stuck in a space loop forever.

seriously stop pretending that the host spacing themselves isn't a death sentence for borers, 9/10 they're stuck in an unmaneuverable spaceloop.

and again, OP end game evolutions is a shitty idea too for a midround antag that can occur the same as revenant. it's not a blob, it's less easy to fight and less obvious than a blob, you don't give it overpowered shit. it's a role for ghosts to play and that's it.

how about instead of this shit give it it's own preference, hm?

**Comment by oisin100** [comment]
> no OP end game evolution, they're fine as is and they're not ascendant shadowlings

I should not have mentioned the word OP. But it would be nice to give them some sort of gimmick.

> that being said a chemical pool to allow for use of chemicals ect is okay, but borers get chemicals extremely slowly and usually occur towards late-round due to low occurance chance so it'd more than anything end up like space ninja with not enough time to complete objectives

I can buff the chemical regrowth rate without having to increase the price of the chems with this evolution system. Did you even look at the tech tree? Borers can massively upgrade their chem rate.

> seriously stop pretending that the host spacing themselves isn't a death sentence for borers, 9/10 they're stuck in an unmaneuverable spaceloop.

I never see anyone spacing themselves because 'lol borer' infact most of the time the borer and the host get on quite well together. Just a few people like to RP a bit more and kill one or two borers, which is fine.

> how about instead of this shit give it it's own preference, hm?

Borers have their own preference.

**Comment by ghost** [comment]
it's the alien pref

no 'borer' pref

if you don't want borer you lose out on being xeno

**Comment by ghost** [comment]
also you answered none of my other comments and it'd still be unbalanced

**Comment by ShadowDeath6** [comment]
I'd like borers to have like 2x chem gain off of now, remove influence completely, and make them able to gain chems while the host is KOed. Stupid cheese of host saying "HELP BORER PLS REMOB" and spamming sleep is retarded

**Comment by Alek2ander** [comment]
> Evolved evolutions

Purchased purchases

**Comment by ShadowDeath6** [comment]
> evolved evolutions

Kek

**Comment by oisin100** [comment]
Ill recreate this PR after the rebase.

**Pull request closed without merging**
