### PR TITLE
Ports /tg/'s lich beam.

### LINKED ISSUE #976: Lich Wizard Phylacteries are Immpossible to Find
### Expected Behaviour

There are counters to Lich wizards.
### Actual Behaviour

Cruix goes lich every time he rolls wizard and gets outrobusted by the crew at least 5 times, but still lives because his phylactery is in a 1x1 room you can only get into by ethereal jaunting.
### Solution

Make the pinpointer locate phylacteries.

or

Make using ARISE!!! drop an item on the lich's old body that points toward the phylactery, possibly deactivating when the ability is off cooldown, to give the wizard a chance to hide it again after a few minutes.
EDIT:
or

There is a revenant-style beam from the old body to the new body for around 10 seconds after the lich "dies".

### PR DESCRIPTION
**Pull request by Cruix**
Fixes #976 
### Intent of your Pull Request

Port's /tg/'s lich beam. Whenever a lich revives, there is a beam that leads from the old body to the new one for 15 seconds, about as long as the lich is stunned for when it revives.

:cl:
tgs: Added tg's lich beam. Whenever a lich revives, there is a beam that leads from the old body to the new one for 15 seconds.
/:cl:

### CODE REVIEW

**Comment by X-TheDark** [comment]
Putting a DUNK on it (the wizard's spell : Lich) :+1:

**Comment by Super3222** [comment]
Very nice. /tg/ knows how to balance.

**Comment by ghost** [comment]
> tg knows how to balance
> 
> tg knows how to balance
> 
> TG KNOWS HOW TO BALANCE
> 
> TG
> 
> BALANCE
> 
> TG KNOWING WHAT BALANCE IS

who is your dealer

**Comment by Super3222** [comment]
You know, when I made that comment I was wondering if I should take back what I said.

Okay, okay. Maybe a few people in /tg/ know how to balance.

**Pull request merged**
