### PR TITLE
Mindslave Metanerf Option #1

### PR DESCRIPTION
**Pull request by oisin100**
Implants now cost 8TC but explode after 20 Minutes.

Should kill the metagamers...
#284

### CODE REVIEW

**Comment by Time-Green** [comment]
I really dont see the deal here.

If they make a strong pair, Well good job. 

A player being robust is a reason for a nerf?
And this helps alot with finding metagammers.

I really dont see the prob here

**Comment by oisin100** [comment]
Some people think its too easy to get greentext with it...

But maybe we can get some admin feedback on how they are finding it when it comes to Metafriends antaging eachother as this is the main reason im nerfing it.

**Comment by Super3222** [comment]
@timkoster1, The problem is giving your metabuddy a free antag round.

The problem is there's a big difference between metafriending and blatant rule-breaking metagaming. I typed it up, but deleted it figuring it'd be too long the read.

Now the problem is, that everyone metagames. What this will do is make people think twice about getting implanted, knowing it will give them an antag round but at the same time they'll pop.

**Comment by FluffySurvivor** [comment]
I don't understand you guys in the slightest. 

If 2 metacommers go together via mindslave, ban them for metacommunicating. THE POOR ITEM IS NOT AT FAULT. 
If 2 non-metacomming players pair up via mindslave because the main antag likes the second player and cooperates well then it's perfectly within rules and serves the point this item was created for. You don't get an antag ally for free. You get it for 12 TC, and obviously you are not going to buy some guy named "McShitter Balls XDDD". The ally will show if the money was worth it or not. 

We get a new cool item for the first time in years, then we nerf it to uselessness in the first week because a bunch of favorable circumstances in a few isolated cases put the item into light then our lovely players QQ on github because they died. 
Bye "i ded plz restart", the era of "i ded plz nerf" has begun.

**Comment by oisin100** [comment]
If you dont want them to be nerfed vote it down. right now i dont really mind. Ive hardly even played since i added the implants xD

**Comment by ghost** [comment]
Leave it as is.

It's not overpowered by any means, and lets us admins actually catch metafrienders/metagamers in the act if they continuously mindslave the same person over and over.

**Comment by DavidEdwards** [comment]
Isn't this an issue for the person being implanted?

Their game gets cut short because someone else implanted them?

**Comment by Stealthkibbler** [comment]
I said it before and I'll say it again, just make it a revolution recruitment item.

**Pull request closed without merging**
