### PR TITLE
Blob Nerf (merge)

### PR DESCRIPTION
**Pull request by ghost**
Refer to issue #0.
### Intent of your Pull Request

Type here what the purpose of your PR is. Also set the issue number above, or delete the line if this PR is not related to an issue. You can type "Fixes issue #6" and issue 6 will be automatically closed as your pull request is merged. Much easier for everyone if you do that.
#### Changelog

:cl:
tweak: Blob health and fire resistance for all types nerfed so the blob can be combated better.
tweak: Time before blob burst is now 6 minutes to allow for proper sabotage and such things.
tweak: Blob win requirements lowered to prevent excessively long rounds.
/:cl:

### CODE REVIEW

**Comment by FluffySurvivor** [comment]
lower win condition

**Comment by ParagonPrime** [comment]
three fuckin' minutes?

that's nowhere near enough time

if you're in a shitty job like lawyer without maint access or sabotage capability, you're just about fucked in 3 minutes- getting access and/or sabotaging takes far longer than that

**Comment by FluffySurvivor** [comment]
I agree with para, 3 is too short. 6-7 is decent. 

Also, type in reasons for the changes, basically patch notes. Everyone has to understand why we are making the balance changes.

**Comment by ghost** [comment]
okay

**Pull request merged**
