### PR TITLE
Syndicate Scout Drones

### PR DESCRIPTION
**Pull request by Super3222**
### Intent of your Pull Request

Introducing... Syndicate Scout Drones.

Old PR - #488 
Idea - #341 

They are currently only admin spawnable due to imbalance in the traitor uplink. They'd make camera bugs useless for no reason.

### CODE REVIEW

**Comment by Super3222** [comment]
Don't merge yet until I commit an update for the icons.
Also after the next commit, it should be easier to read the actual additions.

**Comment by ShadowDeath6** [comment]
never forget the old PR

**Comment by Super3222** [comment]
I think Adam only disliked how it was going to replace camera bugs.

That's sorted out now, so it'll be a tool for adminbuse @KMC2000

It could be used in events where they need nukeops, just remember to spawn the controller (drone spawns with it).

**Comment by ShadowDeath6** [comment]
I'm interested to see how this would turn out if it was merged.

**Pull request merged**
