### PR TITLE
Plantpeople fixes

### LINKED ISSUE #502: Syndie Station Lighting In Regards to Phytosians
### Expected Behaviour

The syndie station is lit up completely along with the shuttle and cabbages shouldn't take damage over time
### Actual Behaviour

You die a slow and painful death as a cabbage operative without your spacesuit in hard-suit mode on  both the station and the shuttle (this also doesn't always work it seems to be 50/50)
### Steps to reproduce the problem
1. Spawn as cabbage op
2. Die slowly and painful
3. Get admin healed without blowing up (hopefully)

### LINKED ISSUE #623: Phytosians die in places such as arrivals/escape/syndicatehuttle
### Expected Behaviour

Lalala I am not dying and am a happy cabbage lalalala
### Actual Behaviour

OH GOD THE LIGHTNING IS BUGGED ON ARRIVALS AND ESCAPE AND I AM NOT GETTING LIGHT PLS HALP MEEEEEEEEHEHHHHH
### Steps to reproduce the problem
1. Be phytosian
2. Stand in arrivals
3. Die of malnourishment.

### LINKED ISSUE #658: cabbages dont have light inside mechs
### Expected Behaviour

Get in Syndie mech you spent all your $$$ on and win
### Actual Behaviour

You pass out inside of it and die

### PR DESCRIPTION
**Pull request by AsV9**
Fixes #502
Fixes #623
Fixes #658

### CODE REVIEW

**Comment by Time-Green** [comment]
:+1:

**Comment by ShadowDeath6** [comment]
Do they heal on shuttle turfs or is it neutral lighting?

**Comment by AsV9** [comment]
Nothing happens on shuttle turfs.

**Comment by Time-Green** [comment]
Nothing happen? Then they will still die.
A phytosian gains ''food'' from light.
If nothing happens he wont and will starve within 2 minutes, and will then very quickly die of malnourishment.

**Comment by AsV9** [comment]
He does not loose nutriment or take damage in those areas. It is simply turned off.

**Comment by Time-Green** [comment]
Oh, sorry then. :+1:

**Pull request merged**
