### PR TITLE
Floodlight nerf

### PR DESCRIPTION
**Pull request by MacHac**
Requested by Adam.
### Intent of Pull Request
- Flood lamps can no longer be both moveable and on at the same time.  They can be secured with a wrench.

The days of pulling a floodlamp behind you through maint and farming shadowling tears are over.

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
stop buffing shadowlings

**Comment by Super3222** [comment]
Ah, here's the big bad floodlight nerf.

With this...
Protip:
Secure floodlamps within glass windows.

**Comment by ghost** [comment]
after floodlights shadowlings had a 20% winrate

this is a needed nerf after taco's also shadowling nerf

balance is required

**Comment by ShadowDeath6** [comment]
I might just be the best shadowling ever but it's piss easy to just meme right toward them and stun them with whatever abilities you have, disable the floodlight, pull it into space, and remove the cell in about 10 seconds.

**Comment by ghost** [comment]
> borg guarding it
> 
> 2 people near it

good luck

**Comment by ShadowDeath6** [comment]
> icy veins
> sonic screech
> push one of the people over
> turn off light

**Comment by ghost** [comment]
> try to push one of the people over
> whiff the disarm
> stunbaton
> laser
> laser
> laser
> borg wakes up

**Comment by X-TheDark** [comment]
Doesn't Veil extinguish Floodlights?

**Comment by Cruix** [comment]
No.

**Comment by X-TheDark** [comment]
Oh, damn. No wonder they are really good at stopping slings. Yeah, then making them either movable (but Veil'able) or immovable (but un-Veil'able) seems like a good thing to try aka "I think this is good.".

**Comment by DavidEdwards** [comment]
Looks good. We can always revert / tweak if it is too much.

**Comment by ShadowDeath6** [comment]
> pull stunprod
> prod officer
> gg no re

**Comment by Nirnael** [comment]
Put cells into the floodlights, they should light up without power anyway, there is no spess magic.

**Pull request merged**
