### PR TITLE
Adds lethal slugs to the armory

### PR DESCRIPTION
**Pull request by Super3222**
Refer to https://forums.yogstation.net/index.php?threads/add-lethal-shotgun-shells-to-the-armory.7145/#post-101398.
### Intent of your Pull Request

This has been a long time coming, and I've recently pushed this due to a few balance changes that are being done.

This will add 3 different security bandoliers to the riot shotgun guncase. Each bandolier holds thirteen rounds.

Standard Edition - Holds rubbershot shells. They will deal 25 stamina damage with 3 brute damage, you may be familiar with these since they riot shoguns start full of these.

Crowd Control Edition - Holds buckshot shells. They have a 3x1 spread, and deal 15 brute damage per pellet.

Lethal Edition - Holds shotgun slugs. They simply do 60 brute damage straight.
#### Changelog

:cl:Super3222
rscadd: NT's security now starts with a variety of slugs for their shotguns!
rscadd: Rubbershot shells (in their own bandolier) start inside of the guncase at the beginning of the shift.
rscadd: Buckshot shells (in their own bandolier) will start inside of the guncase at the beginning of the shift.
rscadd: Shotgun slugs (in their own bandolier) will start inside of the guncase at the beginning of the shift.
/:cl:

### CODE REVIEW

**Comment by EMT321** [comment]
Will the bandoliers be labeled respectively?

**Comment by Super3222** [comment]
> Will the bandoliers be labeled respectively?

Yup. You'll be able to differentiate between them.

**Comment by FluffySurvivor** [comment]
So little ammo?

**Comment by oisin100** [comment]
Anything else to add or can i merge this?

**Pull request merged**
