### PR TITLE
Mimekitty

### PR DESCRIPTION
**Pull request by TehFlaminTaco**
Adds a new pet cat. Mimekitty.

The Mimekitty cannot speak if possessed by a player, and will follow anyone with the name "Mimekitty". They also can't be punched.

Not implemented in the map anywhere.

### CODE REVIEW

**Comment by Wardog390** [comment]
fucking lol

**Comment by X-TheDark** [comment]
Legit question : Why?

Who is Mimekitty and what did/do they do?

**Comment by Super3222** [comment]
> Who is Mimekitty and what did/do they do?

She's an old player from Yog. Left after awhile.

ShadowDeath6 had a crush on her, but that drove her away.

**Comment by george99g** [comment]
Yes, please.
Love it!

**Comment by X-TheDark** [comment]
If that is the case, I see absolutely no problem with this. Carry on, good sirs :+1:

**Comment by shrimptk** [comment]
> Map in offices for mime and cluwn
> Put mimekitty in mime office
> boom, done.

**Comment by TehFlaminTaco** [comment]
Mimekitty added next to honkbot in bar. Honk.

**Comment by AsV9** [comment]
:+1: to @TehFlaminTaco  for knowing how to merge maps.

**Pull request merged**
