### PR TITLE
Revamps brig

### PR DESCRIPTION
**Pull request by oisin100**
All credit goes to @utahclock 

:cl: UtahClock
rscadd: Brig has been completely revamped! Enjoy!
/:cl:

### CODE REVIEW

**Comment by oisin100** [comment]
687474703a2f2f7075752e73682f6f61526b532f376139366535626432612e706e67

**Comment by EMT321** [comment]
Still no blast doors in detectives office?

Place is gonna be broken through constantly go access rest of brig.

**Comment by utahclock** [comment]
Det office has shutters

**Comment by EMT321** [comment]
Furthermore, why are some walls rei forced and others regular in direct proximity to each other? Reference: interrogtstion.

**Comment by utahclock** [comment]
Map error that can be changed

**Comment by EMT321** [comment]
There are two regular walls in direct proximity to Rwalls at the labor shuttle exit, behind the venders.

Most of the southern facing walls for interrogation, lawyers office, and detectives office are regards walls, while other outward facing walls are reinforced.

**Comment by EMT321** [comment]
NW most cell as well. Open to space and not reinforced.

**Comment by utahclock** [comment]
Ill redo walls in morning then oisin can remerge lel

**Comment by ShadowDeath6** [comment]
That mech recharge room maint door

**Comment by ParagonPrime** [comment]
-mech room maint door is aggravatingly badly placed
-Waaay too much empty space- put more stuff in the morgue and some nice stuff in the corridor leading to the sec beds
-A few weird placements and adjacent rooms
-Give HoS office privacy shutters, specifically ones on the windows connecting to the armoury

**Comment by EMT321** [comment]
Some privacy shutters on the HoS windows, like TG has, would work wonders.

**Comment by GrayRachnid** [comment]
Connect eastern maint to the pod with a wall pls.

**Comment by AsV9** [comment]
image
This annoys me. Why are there windows then walls here? Hnng.

**Comment by EMT321** [comment]
I'm more perplexed at the random lack of RWalls leading into security locker room, from maint.

I thought conventional wisdom was that security had at least one Rwall to the exterior, and possibly just regular walls on the interior. For reference: All of current brig, except for HoS office and execution.

**Comment by AsV9** [comment]
Also, it looks like the top row of cells have their timer on the inside. Might want to fix that.

**Comment by utahclock** [comment]
Asv they look that way in dm. But on live test they are fine. They would be
in cell if on wall in dm

**Comment by oisin100** [comment]
If you could push up the top 5 cells so that you have a 3 tile hallway whilst also removing the glass from  all the top cells except the closest one to isolation it might look cool

**Comment by oisin100** [comment]
If you could push up the top 5 cells so that you have a 3 tile hallway whilst also removing the glass from  all the top cells except the closest one to isolation it might look cool

You could also swap the positions of the locker room and the security pod so that the locker room is vertically aligned on the right hand side of the HoS's office so that you can then move the Escape pod to be right beside the maint shafts. 

It would also be nice if the east main shaft had some windows in it.

The maint door to the south of the courtroom doesent look right with a glass window beside it, May i suggest you turn that window into a wall?

You also have a desk in the armoury which leads out into space.

I've taken the liberty of drawing the areas which need changing, Red are bits which need changing, Blue are walls what need to be turned into R-Walls [Image Here](http://prntscr.com/b63p4s)

**Comment by oisin100** [comment]
It would a

**Comment by oisin100** [comment]
Woops.

**Comment by utahclock** [comment]
Right ill make adjustments. Ill resend you file when done oisin. Maynot be
til tomorrow when i can.

**Comment by Alek2ander** [comment]
2ed2b8a0-1d55-11e6-91c5-7ceba34559b6

**Comment by EMT321** [comment]
Yeah, the fact the warden can no longer see the cells from his desk is disconcerting. The lack of external Rwalls is also concerning, as it makes it trivial to break in.

**Comment by oisin100** [comment]
This PR will be re-made once we have rebased to /TG/

**Pull request closed without merging**
