### PR TITLE
Do you feel lucky, punk?

### PR DESCRIPTION
**Pull request by ToGWtF**
### Intent of your Pull Request

Adds RussianRevolver to bartenders backroom, for high stakes betting

### CODE REVIEW

**Comment by AsV9** [comment]
:+1: \* :100:

**Comment by Super3222** [comment]
:+1: YES! HELL YES!

**Comment by ToGWtF** [comment]
should i put the shotgun in the beer cabinet and revolver on the table    or leave the shotgun out for it to be stolen?

**Comment by DavidEdwards** [comment]
What could possibly go wrong?

**Pull request merged**
