### PR TITLE
LITERALLY UNPLAYABLE

### PR DESCRIPTION
**Pull request by AsV9**
### Intent of your Pull Request

Fixes the worst bug of them all.
#### Changelog

:cl:AsV9
spellcheck: Fixes a spelling error in the mining point console thingy.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
OH THANK GOD I ALMOST QUITTED

**Comment by ShadowDeath6** [comment]
implying

**Comment by oisin100** [comment]
10/10 Asv...

Lets not exaggerate the changelog <3

**Comment by oisin100** [comment]
Thats still a terrible changelog...

**Comment by AsV9** [comment]
nu-uh

**Pull request merged**
