### PR TITLE
Space Lube Nerf 1

### PR DESCRIPTION
**Pull request by Cruix**
Makes space lube have the same overlay as water on a turf. Suggested as part of #303.

### CODE REVIEW

**Comment by DavidEdwards** [comment]
Just needs a changelog

**Comment by B1gb3ast** [comment]
Merge?

**Comment by TehFlaminTaco** [comment]
Nah, Spacelube is supposed to be invisible.

**Comment by B1gb3ast** [comment]
Discuss?

**Comment by DavidEdwards** [comment]
Big: Ive been away for family. This is fine to merge yes. We will see whether it makes lube pointless or not. If it is too much, we can simply revert this PR.

**Pull request merged**
