### PR TITLE
Adds Tactical Corgi

### PR DESCRIPTION
**Pull request by Cruix**
### Intent of your Pull Request

Refactors tactical animal harnesses to work on more than just hostile simple animals

Adds tactical corgi harness. Tactical corgis get a toggleable stun instead of a ranged weapon.

:cl:
rscadd: Centcomm has completed the training of tactical corgis for drug screening and support of Emergency Response Teams. Tactical corgis are equipped with a harness that allows them to stun targets in melee range.
/:cl:

untitled

### CODE REVIEW

**Comment by ToGWtF** [comment]
M E R G E
 E
 R
 G
 E

**Comment by X-TheDark** [comment]
Holy shit, this actually sounds so good.

**Comment by oisin100** [comment]
Changelog should be

:cl:
rscadd: Centcomm has completed the training of tactical corgis for drug screening and support of Emergency Response Teams. Tactical corgis are equipped with a harness that allows them to stun targets in melee range.
/:cl:

**Comment by ghost** [comment]
fuck off with the stupid meme shit this is obnoxious and irritating

ian has no access in the first place and a melee stun is fufilled by a stunbaton

**Comment by ShadowDeath6** [comment]
Ian has all-access :^)

**Comment by TehFlaminTaco** [comment]
Ian can move freely through doors.
Merge.

**Comment by Kmc2000** [comment]
Yesss cruix

Now add the other animals i gave you, MAINLY THE SYNDICAT REEE

**Comment by ghost** [comment]
> ERT corgi that cannot be stopped by anything short of walling it off/lasering it with an emag, a stunbaton, and a ranged attack and a license to validhunt

Hmmmmmmmmmmmmmmmmmm

**Comment by Cruix** [comment]
It doesn't have a ranged attack. It also only has enough charge for 10 stuns, and then it's helpless.

It is also only ever going to be spawned by KMC so balance isn't a huge concern.

**Comment by Super3222** [comment]
Giving ERT a tactical companion wouldn't hurt. As long as they don't speak human.

**Comment by X-TheDark** [comment]
I mean, it's an adminbus item. I don't see why not, allows to make Tactical Corgi ERT squad. That's a gimmick for at least a round or two right there.

**Comment by DavidEdwards** [comment]
Please double check that ERT Corgi cannot access all areas and pass through doors unhindered.

Other than that, this is no worse than tactical dolphin, memeshitwise.

**Comment by Cruix** [comment]
Only Ian can pass through doors, and he will keep this ability if someone puts a harness on him. The normal corgi has the same access as an ERT member, but cannot pass through closed doors.

**Comment by X-TheDark** [comment]
Yes, this is correct, Ian (which is a subtype of pet/dog/corgi/) is the only corgi that has the PASSDOOR flag (that allows him to, well, pass doors).

**Comment by ShadowDeath6** [comment]
Give ERT a borg with a pulse rifle

**Pull request merged**
