### PR TITLE
Odysseus Improvements, Part 2.1 : Rearming Syringes

### PR DESCRIPTION
**Pull request by X-TheDark**
Yup, this is still not dead yet.

Syringes can be rearmed now:
- 3 seconds per syringe;
- Can only be done in bulk (all or nothing);
- 250 energy per syringe : at 10, you are looking at 12.5% energy of the standard 20k cell mechs get.
- Must stand still for entire duration;

All of the above are purely for balance. I'd like rearm to be instant or have Syringe Gun not have ammo but generate syringe when firing.

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
:+1: x :100: 
Why use so much energy though? Making 300 bullets costs less.

**Comment by X-TheDark** [comment]
Balance. I would rather decrease the costs later, if needed. Also, keep making suggestions even in here. If you think this should cost less, tell me and I will do it if enough people think the same way.

Plus, you can pick the syringes back up. This is mostly added as **an option** (something Odysseus severly lacks in the syringe department).

Hell, if people want me to, I can just remove the ammunition on Syringe Gun entirely and make it shoot as long as you have energy (basically like laser guns and stuff).

**Comment by ShadowDeath6** [comment]
Maybe just make it have an infinite amount as long as it has chems to fire.

**Comment by X-TheDark** [comment]
Literally the reason for all this needless expense and time to rearm syringes is to prevent their spam, since, unlike lasers, one hit from this can be extremely OP, not mentioning the fact that if you use some stam-damaging chem, you can walk up to them and start punching them and they will not be able to do anything (since mech punches paralyze).

**Comment by ShadowDeath6** [comment]
Non-combat mechs don't stun on punch, I'm pretty sure.

**Comment by DavidEdwards** [comment]
Looks good! See how it runs in game when it is live. You can tune the numbers if it feels too sluggish.

**Pull request merged**
