### PR TITLE
Small engineering changes

### PR DESCRIPTION
**Pull request by FluffySurvivor**
Re-adds the 3rd engineering hardsuit that was part of #692

The solar pack crate has been removed from the map, due to being never used.

:cl: FluffySurvivor
rscadd: One more hardsuit has been added to Engineering.
rscdel: The solar components crate has been removed.
rscadd: A medkit has been added to Engineering.
/:cl:

### CODE REVIEW

**Comment by Cruix** [comment]
Please add the screenshots to this PR for convenience.

**Comment by FluffySurvivor** [comment]
engineering

**Comment by FluffySurvivor** [comment]
Hmmm. I think the additional hardsuit is missing in this PR.

**Comment by DavidEdwards** [comment]
Hardsuit isnt there, why delete the locker?

Doesn't matter too much if it isn't used - perhaps one day it will :D

**Comment by FluffySurvivor** [comment]
Yep, I'll fix it when I get on my computer

**Comment by FluffySurvivor** [comment]
Should be fixed now.

Also added a first aid kit, https://forums.yogstation.net/index.php?threads/medkit-in-engineering.7282/
RIP Silva.

Regarding the solar components, I've asked @ToGWtF to add the crate in his enlarged secure storage, #972

engineering

**Comment by FluffySurvivor** [comment]
why conflicts

**Comment by oisin100** [comment]
Mm, Conflicts.

**Comment by FluffySurvivor** [comment]
How do i fix conflicts?

**Comment by AsV9** [comment]
Considering this is a map change, I don't think there is a lot you can do other than redo the changes and create a new PR. Hence, I'm closing this, feel free to open a new PR.

**Pull request closed without merging**
