### PR TITLE
Buffs traitor thermals

### PR DESCRIPTION
**Pull request by FluffySurvivor**
Lings and slings have full thermals for free, but traitors have to PAY for a shittier version. Not anymore, uhhh, they still have to pay but now it's worth it.

:cl: FluffySurvivor
rscadd: Traitor thermal glasses now grant night vision.
rscadd: Thermal glasses are now disguisable as any other pair of glasses.
tweak: Thermal glasses cost reduced to 5 from 6 TC. 
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
cool

**Comment by ghost** [comment]
cham thermals, please. And keep the cost the same.

**Comment by Super3222** [comment]
Traitor's aren't xenobiological aliens which is why they don't get free shit, they also have a much different concept than changelings and shadowlings, but whatever.

I've been waiting for that price to drop on the thermal glasses though. Dual eswords + Meson combo.

**Comment by ShadowDeath6** [comment]
hype for ebow + thermals being better

**Comment by FluffySurvivor** [comment]
do you want the current, buffed thermals of this PR
or do you want 6 TC chameleon thermals + NV ?

**Comment by ShadowDeath6** [comment]
5 TC chameleon thermals + NV

**Comment by FluffySurvivor** [comment]
hmmm kay lets do the 5 tc cham thermals NV and flash resistance

**Comment by Super3222** [comment]
Flash resistance? No no no. That's literally the only thing that defeats mesons, nightvision, etc, period.

That wouldn't even make any logical sense. They are suppose to amplify light to let you see in the dark, a flashbang would stop them period.

Keep it as [flash > thermal mesons] pls

**Comment by FluffySurvivor** [comment]
thermals are now cham thermals
no flash resistance

**Comment by FluffySurvivor** [comment]
@oisin100

**Comment by oisin100** [comment]
Seems good, This should actually make them usefull now.

But can you update the changelog to be "tweak: Reduces Thermal Imaging Glasses price from 6TC to 5TC"

It can get confusing in the changelog if i merge multiple PR's of yours.

**Comment by FluffySurvivor** [comment]
Gotcha bruh.

**Pull request merged**
