### PR TITLE
Ninja spawns after 25 minutes

### PR DESCRIPTION
**Pull request by X-TheDark**
Refer to issue #1101.
### Intent of your Pull Request

Ninja now spawns after 25 minutes. Also added weight (which was unchanged), just so it's clear what the relative probability of the event is.

:cl: X-TheDark
tweak: Ninjas now can spawn after 25 minutes (down from 50)
/:cl:

### CODE REVIEW

**Comment by ToGWtF** [comment]
H E R O
E
R
O

**Comment by FluffySurvivor** [comment]
succ
:+1: :+1:

**Comment by DavidEdwards** [comment]
Oops. Forgot changelog. :<

**Comment by X-TheDark** [comment]
Didn't think this needed one, but I guess it's a big enough change to let people know of that. Added changelog. Can resubmit PR if necessary.

**Pull request merged**
