### PR TITLE
small engineering changes

### PR DESCRIPTION
**Pull request by FluffySurvivor**
#1009

:cl: FluffySurvivor
rscadd: Added an additional hardsuit to engineering.
tweak: The solar components crate has been moved to secure storage.
rscadd: Added a medkit to engineering.
/:cl:

### CODE REVIEW

**Comment by FluffySurvivor** [comment]
engi

**Comment by oisin100** [comment]
HURRY UP GIT.

**Comment by FluffySurvivor** [comment]
UH

**Comment by ghost** [comment]
> more hardsuits

why?

**Comment by FluffySurvivor** [comment]
It was part of #692. It was live for some time, and it worked out well. 
And 2 hardsuits for 5 engineers was bad.

**Comment by FluffySurvivor** [comment]
@oisin100

**Pull request merged**
