### PR TITLE
Sticky ban ingame interface

### PR DESCRIPTION
**Pull request by AsV9**
Allows for sticky bans ingame. Needs **a fokken lot** of testing to make sure this doesn't cause everyone to be banned. Do not merge before it has been tested.

Credit to MSO over at tgstation.

### CODE REVIEW

**Comment by AsV9** [comment]
kek

**Comment by Xantam-13** [comment]
The fuck is with all the tags!!!

Is this even possible? Stickybans are done through DD?

**Comment by Groudonmaster** [comment]
I mean it worked when tested but not the way it was intended. It banned everyone rather than sticky ban the singular profile.

**Comment by AsV9** [comment]
I can't for the life of me get this to behave. If someone else has any interest in trying to do this, go ahead.

**Pull request closed without merging**
