### PR TITLE
High Risk Item Logging

### PR DESCRIPTION
**Pull request by Cruix**
### Intent of your Pull Request

*Added a new var to items, "high_risk". If this is set to 1, admins will be notified whenever it is destroyed or changes z-levels. Most traitor objective items have high_risk set to 1 by default.
*When looking at a player's objectives in the traitor panel, admins can look at and jump to the locations of their targets. Due to how object paths work, some objectives might show strange objects, like the "steal 20 moles of plasma" showing the captain's jetpack because jetpacks are air tanks. This should work for steal objectives, and objectives with particular human targets like assassinate, protect, etc.

### CODE REVIEW

**Comment by Cruix** [comment]
Screenshots:
untitled1
untitled

**Comment by AsV9** [comment]
Neat.

**Comment by ShadowDeath6** [comment]
Will this work if the item is somehow deleted and respawned?

**Comment by Cruix** [comment]
Yes

**Pull request merged**
