### PR TITLE
Shadow Person Night Vision

### PR DESCRIPTION
**Pull request by TehFlaminTaco**
Shadow People now have night vision, like their sling counterparts,
although don't have thermal vision.

### CODE REVIEW

**Comment by Time-Green** [comment]
They already had this...

**Comment by TehFlaminTaco** [comment]
Yeah, but this is a different particular kind of nightvision.

That works better.

**Comment by ShadowDeath6** [comment]
:^)

**Comment by Cruix** [comment]
> declaring a subtype using nesting

You make me sick.
You should also probably change the description.

**Comment by TehFlaminTaco** [comment]
I nest subtypes. It's a thing I do.

Get Used to it.

**Comment by DavidEdwards** [comment]
You haven't been doing that with all your commits have you? There is a style plan to the entire codebase. Please try to stick to it.

It's not good to have multiple different code styles in one codebase.

**Comment by TehFlaminTaco** [comment]
Well, when adding a subtype that differs in a single variable, it's wasteful to type out the entire type once more.

**Comment by AsV9** [comment]
It's a lot easier to find things when they are not nested like these though.

**Comment by TehFlaminTaco** [comment]
Absolutely ignored. Killing.

**Pull request closed without merging**
