### PR TITLE
New space suit sprites by Kmc2000

### PR DESCRIPTION
**Pull request by george99g**

### CODE REVIEW

**Comment by Xantam-13** [comment]
Which space suits would this replace? Eva ones?

**Comment by Time-Green** [comment]
Command Eva suits?

**Comment by Alek2ander** [comment]
68747470733a2f2f692e6779617a6f2e636f6d2f38623531616436346337333631653764616537643632386231316364346265302e706e67

**Comment by george99g** [comment]
> Which space suits would this replace? Eva ones?

It replaces the standard space suits from EVA, yeah.

**Comment by Xantam-13** [comment]
It looks cyborgy... I'm not sure. Perhaps. I'm on the fence

**Comment by Super3222** [comment]
It'd be pretty cool if these space suits could be in the commands EVA storage so we can keep the old ones... than we can have the best of both worlds.

**Comment by Kmc2000** [comment]
@Alek2ander 

....

Why....

just why...

**Comment by AsV9** [comment]
I'd like these as a new subtype of suits so both are there. Maybe some fancy features such as reagent view, security records checking overlay.

**Comment by Kmc2000** [comment]
I like the command suit idea, that's probably the best way to add 'em as some people are unsure of them

**Comment by ghost** [comment]
it looks like a space suit for cthulhu

just use other station's command suits

CMO's medical hardsuit is the white ship med hardsuit

CE has his hardsuit

HOS has his hardsuit

Cap has his  hardsuit

RD can get the bombsuit that's in /tg/

no offense but this looks like a strange crossbreed between an albino penis, a stormtrooper, and H.P Lovecraft

**Comment by Kmc2000** [comment]
@AdamElTablawy You know those two suits on the right hand side of EVA that sit there, neglected and alone and never used?

That's what we're talking about

Also, THAT DESCRIPTION, LMAO

**Comment by AsV9** [comment]
Making these a new subtype.

**Pull request closed without merging**
