### PR TITLE
Adds tesla engine

### PR DESCRIPTION
**Pull request by AsV9**
tgstation/-tg-station#13258

Shamelessly steals tesla engine from goofball.
image
image
image
image

Because it's late and I want to get this moving asap, PR description also shamelessly stolen;

"Oh man, let's get this shit going.

Welcome to the future, Wardenclyffe style.

The new Tesla Engine is now in the game, only 499 days late.

How it works:

You have a Tesla Generator. It works just like the singularity generator does, except that it makes an Energy Ball. This big floaty ball of pure electricity can only be contained by the containment field. It will shoot bolts of electricity off at conductors, which it prioritizes in this order:
Tesla Coils -> Mobs -> Machines. It will also strike the closest distance-wise of the list after it goes through that criteria. This is non-negotiable because this solves a lot of problems down the line that I'm not going to go into here.

Tesla Coils will attract the bolts. They will take half the power of the bolt, pump it into the powernet it is hooked to, and then will send the other half of the power to the next available conductor, which follows the criteria listed above. Preferably, this will be another coil to harness more of the power and pump it into the grid.

If the Energy Ball is to get out of containment somehow, it will pass through walls, windows, anything. It will shoot electricity at conductors, mobs, etc, and direct bolts from the Energy Ball will instantly kill a spaceman. Dusting occurs if you run into the ball itself. Machines hit by the bolts will EMP or suffer explosive damage.

When you shoot the energy ball with the Particle Accellerator, it gains energy like a singularity, but when it hits 300 energy, it generates a mini-energy ball that orbits the big energy ball. This will send off an extra shock when the energy ball pulses, and this can happen as many times as you let it. The energy ball will also naturally generate small amounts of energy, so eventually a second ball will form.

Be warned, the more mini-balls the energy ball has, the more shocks it sends out at once, and the further it can travel each move. A good engineer can use this to generate lots of power, and a bad one can abuse this to murder the entire station."

Also, the tesla can easily generate more power than the SMES units can draw. I'm aware of this.

Changes from /tg/'s tesla:
The coils and the grounding rods start anchored into the ground, this saves engineering some time setting it up.

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
no thanks fuck tesla meme engine
:-1:

**Comment by Super3222** [comment]
Niceeeee.

Maybe we could add a book to engineering explaining how to set up the Telsa engine (with information inside of it as well), so none of our players screw anything up. . .

We could use a wiki page for the book to open up to, possibly.

**Comment by ShadowDeath6** [comment]
I'm gonna :-1: again because I can't emphasize my dislike for the tesla enough.

**Comment by ghost** [comment]
I quite like the tesla. 

It's a simple power source that's not going to escape except for sabotage, unlike the singularity, can't be beacon'd for traitors, and displays a VERY loud noise so that people know it's loose and can run.

A loose tesla is deadly. A loose sing is a shuttle call station destroying body gibbing event.

So yes, I like tesla.

**Comment by AsV9** [comment]
@ShadowDeath6 
Unlike the singularity, the tesla engine is actually quite dangerous when not handled properly.
Also, you can just hop into a locker and you'll be fine, considering you can hear it from 4 fucking screens away. Wearing a hardsuit will make you ~invincible to it if you don't walk into it.

**Comment by FluffySurvivor** [comment]
YES
MERGE GO GO GO
TESLA HYPE

**Comment by ShadowDeath6** [comment]
I'd rather not spend my entire round hiding in a locker as soon as I hear the noise from the tesla.

Also, considering the singularity was buffed recently, it has a lot of destructive power, plus it's actually usable by traitors via the singularity beacon which can cause a lot of damage.

**Comment by AsV9** [comment]
During my testing last night it took a fairly long time with the PA hacked to power level 3 before it broke containment. It's not going to be the issue you think it will be.

**Comment by AsV9** [comment]
Not happy yet, so don't merge just yet.

**Comment by AsV9** [comment]
I'll do anything else in a future PR me thinks

**Comment by ShadowDeath6** [comment]
I don't think the teala is supposed to break containment at all.

**Comment by ghost** [comment]
okay so this is ready for merge?

**Comment by ShadowDeath6** [comment]
No and it never will be

**Comment by AsV9** [comment]
yes, this is fairly merge ready

**Comment by ghost** [comment]
so I can merge it?

**Comment by DavidEdwards** [comment]
Don't do merges Adam, leave that to me & council.

**Pull request merged**
