### PR TITLE
Added dynamic UI

### PR DESCRIPTION
**Pull request by Cruix**
Requires testing
 Response to issue #43
#92 and #258 Redone in a new pull request with fewer commits

Adds:
 -Support for custom Cyborg and AI UIs
 -Support for donator-only UIs
 -The ability to change your UI in-game through the "Select UI Style" verb in preferences
 -Two new donator-only UIs, one for Cyborgs (Beepsky) and one for AIs (Matrix_OS)
 -Three new saved preferences for UI style (one for each of AI, Cyborg, and Carbon)

Removes:
 -the old method of selecting UIs in the pre-game lobby
 -the old saved preference for UI style

Issues:
 -When the UI redraws, there is a short period in which the health doll is not properly updated

Fixed:
-blindness and flash overlays no longer disappear when changing UIs

### CODE REVIEW

**Comment by Cruix** [comment]
Screenshots from the old PR:

 Popup window:
https://cloud.githubusercontent.com/assets/16478175/12739296/eddabec2-c92d-11e5-8fa3-93af48335565.png

New AI ui:(The 1s and 0s scroll down)
https://cloud.githubusercontent.com/assets/16478175/12739295/edd5d2d6-c92d-11e5-9194-487059f9d8a7.png

New Cyborg UI:(I just badly drew a picture of Beepsky on some of the icons, it was more as a test than to make a serious UI)
https://cloud.githubusercontent.com/assets/16478175/12739294/edd5c836-c92d-11e5-9ecd-18ab76a2cc5b.png

**Comment by AsV9** [comment]
> -When the UI redraws, there is a short period in which the health doll is not properly updated

Is this an issue or is it just a short moment after changing UIs this is borked?
Also conflicts. Ayy.

**Comment by Cruix** [comment]
DAMN CONFLICTS AGAIN

It's not really an issue, it never lasts more than about a second.

**Comment by Cruix** [comment]
Finally fixed merge conflicts. Turns out that the fix I had done for the flash/blind overlays disappearing was made moot by X-TheDark's port of overlays.

**Comment by X-TheDark** [comment]
Well, damn. Sorry about that.

**Comment by Cruix** [comment]
Nah, overlays look much better now, and my solution was pretty inelegant anyway. Plus, you know, you saved us from Taco's Blind Legion thing.

**Pull request merged**
