### PR TITLE
CE's blueprints and certain atmos pumps now notify admins and logs to log files.

### LINKED ISSUE #376: Make CE blueprint naming and plasma-pump turning on display logs in adminlog, not just on investigate. Also make CE blueprint naming log in the first place.
CE's can run around naming places of the station 'DICKVAG' and the AI has to open doors in 'DICKVAG' and if the dominator goes down it alerts the station to a domination attempt in 'DICKVAG.

And we can't tell who named it that. And it's tiring to see places named YOU MOMMAS ASSHOLE LOL and not deal with the guy who did it.

Also, plasma pumps being turned on, and N2O and CO2, should log the same way emitters log-loudly, so we know if someone's flooding ahead of time.

### PR DESCRIPTION
**Pull request by AsV9**
Renaming an area:
Renaming an area
Creating new area:
Creating new area

Pumps:
Pump logging
Which pumps are logged is decided by instances. Just edit the pipes in the map editor and
set adminlog = 1

Fixes #376

### CODE REVIEW

**Comment by Alek2ander** [comment]
Players can hide from the pump alert by deconstructing and rebuilding them.

**Comment by Cruix** [comment]
> Players can hide from the pump alert by deconstructing and rebuilding them.

I can't really see a way around that. Perhaps you could find the sensor in the distro loop that reports to the atmos monitoring consoles and do something similar for when it detects plasma or N2O. The problem is that I have no idea where that sensor actually is.

**Comment by Alek2ander** [comment]
Notify admins when a pump is deconstructed/deleted

**Comment by AsV9** [comment]
Alert for destroying

**Comment by ShadowDeath6** [comment]
Pretty good. Rip plasma flooding griefers.

**Comment by Super3222** [comment]
Nice one, no more plasma grief.

**Comment by ghost** [comment]
merge
merge
merge

**Comment by DavidEdwards** [comment]
Great! Nice work AsV!

**Pull request merged**
