### PR TITLE
Minedrones(merge now)

### PR DESCRIPTION
**Pull request by ghost**
+= minedrones
Issue #336

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
:+1:

**Comment by ghost** [comment]
:+1:

**Comment by ghost** [comment]
can you actually give specifics in the PR of what they do instead of minedrones

**Comment by Super3222** [comment]
:+1: SPECIFICS

**Comment by ShadowDeath6** [comment]
Please tell me that one of these is going to spawn on the asteroid and not need a miner to buy them, because that would make the drones entirely redundant to their purpose.

**Comment by ghost** [comment]
I have added a new drone shell that turns into a minedrone(new sprites included; thank you KMC). Its goals are to mine and refine minerals(using Adam's lawset from the original issue). The drone comes with a special backpack that holds items of weight-class 4, but it can't be removed, and starts with some essential miner tools. Upon the death of the drone, the backpack is deleted. It comes with a new HUD/inventory (thank you Cruix for helping me with the HUD) slot for holding devices and starts with an advanced mining scanner. There should be, if I edited the right map, 3 preliminary minedrone shells on the three main buildings(not security mining) of the asteroid. Miners can now purchase minedrone shells from the equipment vendors for ~600 points(requires ghosts to enter the shells and be competent and avoid death).

**Comment by ghost** [comment]
10/10

best shit

best shit

good shit best shit amazing

fantastic

beautiful

best addition this side of sliced bread 

Groxic 2016 i'll never ban you again

merge merge MERGE MERGE MERGE

**Comment by ShadowDeath6** [comment]
quality pr :+1: x :100:

**Comment by ghost** [comment]
They have extra health and an unremovable mining hard suit helmet. Check the files changed for more specifics.

**Comment by DavidEdwards** [comment]
Cool. I'll look this over as soon as possible.

**Comment by DavidEdwards** [comment]
Code looks fine at first scan. Ill test it locally. I advise all coders to do the same.

**Pull request merged**
