### PR TITLE
Fixes toggleable energy guns shooting the wrong type of shot once after toggling

### LINKED ISSUE #444: Hybrid tasers only switch after firing once after switching
### Expected Behaviour

Switch to disabler from taser, shoot disabler
### Actual Behaviour

First shot is a taser instead of a disabler, fixes itself after the first shot. Still annoying.
### Steps to reproduce the problem
1. Get Hybrid taser
2. Switch modes
3. Shoot

### PR DESCRIPTION
**Pull request by Cruix**
Fixes #444
### Intent of your Pull Request

Fixes toggleable energy guns shooting the wrong type of shot once after toggling. The old shot is refunded.

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
Will this break syndieborg LMGs?

**Comment by Cruix** [comment]
Don't think so, I'll test it. How exactly would it break them?

**Comment by ShadowDeath6** [comment]
The LMG is an energy weapon that uses bullets, so it needs to have bullets in the 'chamber', which had to apply to other energy weapons because it's a subtype. Looking through the code, it shouldn't have any conflicts since the actual ammo stays consistent in the LMG.

**Comment by EMT321** [comment]
Thank you, no more accidental lethals hopefully..

**Comment by AsV9** [comment]
Did you test it, @Cruix?

**Comment by Cruix** [comment]
I did, there were no issues I could find.

**Pull request merged**
