### PR TITLE
Cable coil fixes

### LINKED ISSUE #18: Borg coil bug on the ground
opened by David Edwards · 3 months ago
http://forums.yogstation.net/index.php?threads/borg-coil-bug-on-the-ground.7369/#post-75782
"I believe it requires the wire instance to be created by explosion in order to activate the bug and it's not an everytime thing."

### PR DESCRIPTION
**Pull request by Cruix**
Fixes some cable coil issues:
*You can no longer drag one cable coil stack over another to get one stack of 0 and one of potentially more than 30
*Taking cables from a cable stack, or splitting it in half, will now always give cables of the same color

Hopefully fixes #18 and #22

Much code was blatantly stolen from this /tg/ commit: tgstation/-tg-station@70d97ad

### CODE REVIEW

**Comment by DavidEdwards** [comment]
Why so many PDA / Botany changes. Were they linked to the cable issue?

**Comment by Cruix** [comment]
No, I pulled from the master branch to update my repository, and it is currently ahead of the dev branch for annoying and hopefully temporary reasons.

**Comment by DavidEdwards** [comment]
Don't pull from master. Stick to dev. Base from dev. PR to dev. Regardless
of the state of master. It is either an instance of previous PRs being
merged into master or someone committing directly to master. At any rate,
you shouldn't need to keep state with master. That will be done when I (or
council) merge dev into master for uploading to the server.

**Comment by Cruix** [comment]
I understand, it shouldn't happen again once dev is caught up to master, and it looks like it is.

**Pull request merged**
