### PR TITLE
Added custom suicide

### PR DESCRIPTION
**Pull request by B1gb3ast**
suiciding with a detective's fedora will now display a custom message.
I'm the best coder in the world IMO tyvm merge.

### CODE REVIEW

**Comment by Super3222** [comment]
Don't forget the

> H.facial_hair_style = "Neckbeard"

**Comment by Crazyhyperway** [comment]
If B1g can code then maybe I should try!

**Comment by B1gb3ast** [comment]
Its easy. All you need to do is get told by adam that your dreams are "Impossible." and you will surge with determination so hard you can't even sleep.
Also you need a senpai.

**Comment by Crazyhyperway** [comment]
I'm waiting, Adam!

**Comment by AsV9** [comment]
:+1:

**Pull request merged**
