### PR TITLE
Ported /tg/'s slime person split

### PR DESCRIPTION
**Pull request by X-TheDark**
Issue #374 (linked to /tg/ pull)
Ported over TG Slime Person Split ability by @Incoming5643.

**Damage:**
- 50% heat/burn damage resist;
- 2x cold damage multiplier;

**Splitting:**
- Requires 200 Slime Jelly in your body to split. When you are at 200+, 5% chance every tick for a "You are feeling bloated" message to let you know you are ready to split. Alternatively, go to medbay, the sleepers will show how much Jelly is in your body.
- Gain up to 200, if you stay above Well Fed;
- You gain up to 100, if you stay above Starving;
- During Slime Jelly creation, you burn nutrition MASSIVELY (EDIT: 2.5+0.1 nutrition per tick, instead of 0.1)

After splitting, you gain ability to Swap Bodies. I've made a few improvements and now you can select any eligible body to transfer yourself to (instead of strictly the one you split into/out of), no limits on range or anything. Splitting causes your other body to gain a random number suffix (1-1000) for identification purposes. When you press Swap Body, you get an Input prompt to select eligible body from list of names. Cannot swap into/out of unconscious bodies (too much damage or sleeping).

Enjoy.

**EDIT: Additional changes**
Nutrition consumption decreased to 2.5 (from 5), ported from latest /tg/ version.
5% chance of message that you are bloated when 200+ Slime Jelly, ported from /tg/ version.
Unconsciousness checks everywhere. Unconscious bodies and your current body are not shown in the selection panel, so you can quickswap without fear of ending up in the same body.

### CODE REVIEW

**Comment by TehFlaminTaco** [comment]
YES
PLEASE

**Comment by ShadowDeath6** [comment]
Crit means unconscious, or just too high damage?
Also 100/10 best ever coder 2016

**Comment by X-TheDark** [comment]
Crit means unconscious, in the process of dieing (Seriously, do I need to explain what Crit is?).

**Comment by Cruix** [comment]
I think he is asking if they can swap while asleep. On a related note, can they swap while stunned or restrained? Does it take a certain time, during which they can be interrupted?

**Comment by ghost** [comment]
They can indeed swap while stunned or restrained.

> I think he is asking if they can swap while asleep.

It's the same thing you dork

**Comment by ShadowDeath6** [comment]
There's a difference between being too damaged and going into crit and falling asleep from sleepy pen.

**Comment by Incoming5643** [comment]
To be clear there's a [line](https://github.com/tgstation/-tg-station/blob/73b4bb173eec6e72ed930a9c48ef36c749b68ce8/code/modules/mob/living/carbon/human/species_types.dm#L321) in the /tg/ version that keeps you out of unconscious bodies. So that effect in this pull is I'm guessing more of a balance concern than a technical one.

**Comment by X-TheDark** [comment]
I'll just include a check for that so you cannot swap into unconscious bodies, thanks for the tip, Incoming.

The process of swapping is instant, can be done while stunned/restrained.

You cannot swap out/into Unconscious bodies (whether it be too high damage or asleep).

**Comment by X-TheDark** [comment]
And this is now ready to be merged.

**Pull request merged**
