### PR TITLE
Adam's Changeling Rework Part 1: Changeling Organs

### PR DESCRIPTION
**Pull request by Cruix**
Preliminary commit for #172
### Intent of your Pull Request

Added the ability for changeling abilities to grow organs.
Repathed alien organs, alien abilities, and changeling abilities.
Added changeling organs for the following changeling powers:
*adrenal glands
*augmented eyesight
*chameleon skin
*digital camo
*fleshmend
*hivemind
*mimic voice
*anatomic panacea
*resonant shriek
*spiders
*strained muscles
### Info

The start of Adam's big ling rework. There are still many things to sort out - at the moment making any sting work off an organ will cause runtimes, because I have to move some vars from the changeling datum to carbons. At the moment all the changeling organs have the same sprite as the default alien organ. Still regularly runtimes during testing.

Respecting refunds the points from all the organs you currently have in your body, which means that if you get more, you will have more than the default points. Absorbing another changeling deletes any changeling organs they have and gives you DNA points equal to their cost. This means that as soon as a ling has another stunned, the ling that was stunned will be frantically clicking the respect button in an effort to not lose their DNA points.
### Todo
- [x] Make organ abilities weaker for non-changelings
- [ ] Add sting organs, possibly add a new zone for organ manipulation.
- [ ] Add transform and lesser form organs.
- [ ] Add sprites for each changeling organ.
- [ ] Fix ten million bugs as they are discovered.

### CODE REVIEW

**Comment by ToGWtF** [comment]
papa bless

**Comment by ShadowDeath6** [comment]
you should make the organ manip zone in the groin since all changelings are huge dicks

> sec with adrenal glands

**Comment by ghost** [comment]
it's happening

**Comment by ShadowDeath6** [comment]
You probably SHOULDN'T have basic things be organs, like hivemind and transform, giving regular people those abilities would be... Not good, especially hivemind. It should be secure.

**Comment by Time-Green** [comment]
The thing that will happen is that nobody trusts anyone to implant those organs in themself.
So they will probably just be eaten

**Comment by ghost** [comment]
No spiders organ.

Other than that, remember that these organs don't give people the changeling powers themselves.

Adrenal gland organ would offer a permanent, passive stun reduction when implanted.

The fleshmend organ would slowly heal over time, not give someone fleshmend.

Et cetera.

The exception to this is the hivemind organ-when removed, lings can no longer talk on the hivemind, and if implanted in a human, they gain access to the ling network-Under their regular name rather than Mr. Phi or whatever, meaning that talking will reveal their intrusion.

This is good-undetectable teamchats are shit, there should be a way to intercept their communications.

**Comment by Time-Green** [comment]
Can we just eat the organs for the power?

**Comment by oisin100** [comment]
> Can we just eat the organs for the power?

Yea please. The chance of killing a ling then having someone competent to implant it into you is so minuscule.

**Comment by ShadowDeath6** [comment]
Make all the organs contain initropidril so if you want to get the bonus from eating it you need to suffer

**Comment by ShadowDeath6** [comment]
Well, considering most every ling will be after each other for dem sweet DNA points, I don't know if giving the regular person the ability to validhunt them more easily as well. 

Speaking of DNA points, do you keep bonus points on respec?

**Comment by Cruix** [comment]
You do keep bonus points on respec.

**Comment by ghost** [comment]
It's intended to be difficult.

You have to kill a changeling, subdue it, surgically remove it's organs while avoiding getting fucking murdered by the ling.

By that point, then you can just have your surgery buddy do it with you.

The chance isn't so miniscule as you think-the moment a ling gets caught there'll be 4 people wanting them organs and shit, and so you'll have at the least the Captain and HoS watching, and one of them-or a doctor nearby-is likely to implant the organs into you.

Eating them is dumb shove off.

**Comment by Time-Green** [comment]
Like anyone is going to give those to a normal MD.
Adam, humans don't work that way in ss13.
Just make people be able to either do self surgery or shove it up their ass

**Comment by EMT321** [comment]
Self surgery would be a nice change. You'll already take a penalty from not doing it on a table.

**Comment by Super3222** [comment]
Honestly EMT... Self surgery doesn't make self at all, and I'm honestly glad it's no longer a mechanic you can do on the surgery table.

Anyway, good job Cruix.

**Comment by Cruix** [comment]
Not saying we should add self-surgery, but...
https://en.wikipedia.org/wiki/Leonid_Rogozov

**Comment by DavidEdwards** [comment]
So, what is the verdict on this one. Seems to be favourable so far.

**Comment by MacHac** [comment]
I like it.  I personally think that the whole rework should be one PR, since last I checked there are some interdependent parts.

Good shit @Cruix

**Comment by ShadowDeath6** [comment]
Also- since transforming and hivemind can't be respec'd, if a ling loses that organ, does it mean it's permafucked?

**Comment by Cruix** [comment]
At the moment free organs (hivemind and chemical storage) are regrown when a ling respecs. I believe Adam wants it to be a part of Anatomic Panacea.

**Comment by oisin100** [comment]
> I believe Adam wants it to be a part of Anatomic Panacea.

Please do. I want to sell organs to the crew in exchange for my objectives.

**Comment by ghost** [comment]
The ling is permafucked if those organs are stolen. Respeccing won't help.

If you can get a ling on an operating table long enough and get it to stop killing you long enough to complete an intensive surgery and remove those organs while fending off some asshole chaplain who wants to cremate it and all the other lings who are trying to kill you at the same time, well, by that time you could have cremated it.

Not to mention you know, prescans still work.

**Comment by Cruix** [comment]
Prescans don't save organ information. Should I make them? Changelings would be able to get cloned and eat their dead bodies over and over for infinite DNA points unless some measure is put in place to prevent this.

**Comment by ShadowDeath6** [comment]
Infinite DNA points sounds fun tbh, and it would only be possible with T4 cloning

**Comment by ghost** [comment]
if a ling is willing to minmax THAT hard that it i s literally letting itself get killed and cloned OVER AND OVER AGAIN and risking being caught every time it absorbs it's own body it deserves those points

Not to mention you know you /can't/ absorb your own body because you already have that genome

**Comment by Cruix** [comment]
New commit

Changeling organs now all give powers only to changelings
Adrenaline glands give non-changelings passive stun resist
Fleshmend glands give non-changelings passive healing
Removed changeling spider gland, it is now a non-organ changeling ability
Changeling organs now decay within 60 seconds of being removed from a body
Slightly refactored the organ decay system to be more generic

**Comment by ghost** [comment]
Why do the organs decay? It's gonna be impossible to put it in non changelings.

**Comment by Cruix** [comment]
You can just put them in a freezer and they won't decay.

**Comment by ghost** [comment]
make them not decay

**Comment by oisin100** [comment]
Decaying... We already went through how hard it would be to get a doctor to put the organ into you in the first place... AND now you have a 60 second limit to get a doctor to do it?

**Comment by Super3222** [comment]
There's a freezer inside of the surgery room.

Decay? Yes, they should decay. Maybe changeling organs specifically should take a much more longer time to decay, due to being "stronger" than the normal human organs (which take 60 seconds).

If you don't value the organs enough to store it in a place WHERE IT SHOULD be stored, than you don't deserve to keep it. CMO shouldn't be running around with 5 different changeling organs in his backpack, calling down the HoS to ask if he wants to get an adrenaline implanted into his groin (for Roxie).

Decaying should make the research values drop to one as a suggestion.

I don't understand why decay has to be taken out. Because it'll be easier to shove back into people? You don't just leave a rare study of an alien organ on a surgery table / floor / your backpack. You have to treat valuable things with value. Therefore, they the competent medical doctor would know better than to leave the changeling organ in their backpack.

With decaying, organs will be taken seriously and kept inside of a freezer WHERE THEY SHOULD BELONG. This isn't RnD

**Comment by Cruix** [comment]
> due to being "stronger" than the normal human organs (which take 60 seconds).

The only organ that decays right now is the heart, and that decays in 10 minutes.

**Comment by ShadowDeath6** [comment]
This is gonna be hell for the competent doctors who want their cool shit since half the crew can't do surgery for shit

**Comment by oisin100** [comment]
@cruix You should re-create this PR on the new repository.

**Pull request closed without merging**
