### PR TITLE
Adds the Rapid Engineering Device

### PR DESCRIPTION
**Pull request by Cruix**
Related to #659
### Intent of your Pull Request

The CE's locker now contains the Rapid Engineering Device, a fusion between an RCD, RPD, and Airlock Painter. You can toggle between the three modes by using a verb or alt-clicking on it. The RCD part holds 200 matter units instead of the normal 160, and the device does 12 melee damage instead of the RCD's 10. It currently has no inhand sprite. To avoid massive amounts of copy-pasted code, large portions of the RCD, RPD, and Airlock Painter code was refactored, but should remain functionally the same. Please be on the lookout for minor bugs this may have caused.

red <sup><sup><sup><sup>.d(ank)mi is copyright KMC2000 all rights reserved</sup></sup></sup></sup>

Additionally fixes a bug where you could open the menu to change airlock access on an RCD and be able to change its access forever from any range by never closing the menu.

### CODE REVIEW

**Comment by Time-Green** [comment]
Nice work cruix, looks beautiful.

**Comment by ghost** [comment]
the RCD has an airlock painter inbuilt

right click on it and you can choose the color of the airlock you build and it's access

**Comment by Cruix** [comment]
But then you have to destroy the airlock and rebuild it - this way you can do it without wasting materials.

**Comment by AsV9** [comment]
_overkillsprite_

**Comment by Alek2ander** [comment]
- Needs to be an antag objective instead of the normal RCD which is just too easy to obtain right now.
- Maybe replace the RCD in EVA with this?
- Test how it works with the disable RCD malf power.

**Comment by ghost** [comment]
RCD is not an antag objective

**Comment by Cruix** [comment]
At the moment the malf power disables it like any other RCD.

**Comment by Groudonmaster** [comment]
Yeah RCD was removed from antag objectives.
But I agree we could replace the RCD in EVA with this. That'd make sense seeing how RCDs are now public engineering access.

**Comment by ShadowDeath6** [comment]
> emag one door from maint
> have access to RCD and pipe spam

This better be a bulky item since the sprite is fucking massive, also maybe if it would be able to fit on engi hardsuits

**Comment by FluffySurvivor** [comment]
> merge when

**Comment by Super3222** [comment]
Encourages faster mobility, increase of space in your bag, and better decision making on what you'd actually need.

But I'll be the first one to say it, it discourages teamwork. That's not an entirely big issue because the antag engineers fuck off to plot on how they're going to murderbone, the incompetent engineers either kill themselves or fuck off, and the competent engineers will either try to learn new things from people, fuck off most of the time or try to help.

Also this looks like the size of a sonic jackhammer, how would you be able to fit this in your backpack?

**Pull request merged**
