### PR TITLE
TODAY IS A GREAT DAY (cult nerfs)

### PR DESCRIPTION
**Pull request by FluffySurvivor**
A wise fluffymando once said....
_If you can't remove 'em, NERF 'EM_

So yeah, I am nerfing the auto-win mechanics of cult so you actually need to make an effort to win the round.

Required number of players for cult: 20-->35

Roundstart number of cultists increase (to 9) at 30 pop removed. 6 is the static number of cultists spawned regardless of round pop.

Escape obj requirement: 10-->15 cultists
-Because it was stupidly easy to win in mid-pop with the high number of roundstart cultists.

Cult robes armor values reduced.

Chance to get escape+sac objs instead of narsie+sac : 50-->65
-Escape is a healthier objective to play against than narsie.

Stunpaper: the mute duration is now much shorter.

**Null Rod**
If cultists try to pick it up, they become dizzy, will take damage and get knocked out if they try to attack with it.
The null rod now deals 25 brute against cultists and the user is notified their target is a cultist.
-This will clearly make the null rod a hard counter versus cultists, as it should be. Disposing of the rod as a cult is critical to their survival.

**_AND NOW IT'S TIME TO GET HYPED**_
On examination arcane tomes, blood runes and cult papers appear as blatant cult items.

:cl: FluffySurvivor
tweak: Cult has received several nerfs aimed at reducing the oppressiveness of certain risk-free mechanics. 
tweak: Minimum number of players required for cult gamemode: 20-->35
tweak: Number of cultists required for escape objective: 10-->15
tweak: 6 cultists are spawned roundstart regardless of number of players.
tweak: The escape objective is now more likely to be picked instead of the Narsie objective.
tweak: The stun talisman's mute duration has been significantly reduced.
rscdel: Cult talismans, blood runes and arcane tomes are now recognizable as blatant Cult of Nar'Sie magic upon examination.
rscadd: If cultists try to pick up a Null Rod, they become dizzy. If they try to attack with it they will take damage and get knocked out.
rscadd: The Null Rod now deals 25 brute damage against cultists, also displaying a message for the user in case his target is a cultist.
/:cl:

### CODE REVIEW

**Comment by ToGWtF** [comment]
> The null rod now deals 25 brute against cultists and the **user is notified their target is a cultist.**

bad. very bad

**Comment by FluffySurvivor** [comment]
> bad. very bad

they will just stick with medscanners to test the damage done otherwise

**Comment by ToGWtF** [comment]
> they will just stick with medscanners to test the damage done otherwise

Thats fine. But having HoS steal the null rod at first hint and having him run down a hall and spamming it on people is no bueno. And you know exactly who would do it too.

**Comment by Time-Green** [comment]
I don't think cult neccesarily needs a nerf.
It just needs an overall redo.

This will make starting of as a cultist impossible.
One guy has a tome, someone breaks into chapel and grabs nullrod.
Completely invulnerable to cult magic and deals a solid 25 damage and tells their antag status.

It needs change, but I don't think this is THE change it needs.

**Comment by FluffySurvivor** [comment]
this is a much needed nerf on the cancer and instawin aspects of cult UNTIL someone bothers to rework cult
the ultra-powerful runes are still there, so cultists are encouraged to use them rather than stunpaper 2 victory
and btw I am removing the null rod from the map and making the chaplain spawn with it
I don't see how giving cult reliable counterplay is bad tbh.

**Comment by Time-Green** [comment]
You can nerf it. But it really just needs a rework.
And the nullrod spawning in chaps bag is a great idea. No idea why that was not done before.

**Comment by ghost** [comment]
Keep descriptions and armor values as is.

Antag hunt melee weapons is bad and instantly notifying you is stupid, and hitting someone then medscanning them is metagame.

Null rod needs to stay in chaplain's office so the cult can fucking dispose of it.

This is a bad PR and almost everything in it is bad except for the objective number, req pop and starting cultists changes.

I'll be making an issue report of reccomended changes.

**Comment by FluffySurvivor** [comment]
@AdamElTablawy 
1. Metashields have no place on our server. You just want people banned if you support metashielded cult.
2. Notifying is in place so you don't have to hit+medscan
3. If the cult is retarded and can't pick off the chaplain early THEN IT IT THEIR FAULT AND DESERVE TO LOSE. Not to mention you could just stunprod/taser/use non cult weaponry on the null rod holder/chaplain. Nothing overpowered, just something that helps stop the cult slightly better.
4. Once they start distributing armor and swords, there is literally no hope for crew to pull of a resistance due to DS tier armor. Murderbone cult should not be encouraged.

**Comment by ToGWtF** [comment]
cult robes should have far less armor than cult armor (which is spawned from wearing a hardsuit). as code goes now its literally 10 brute resistance less than the cult hardsuit and the exact same laser resistance

so i agree with that part at least

**Comment by ghost** [comment]
1. Metashields have a place because they're in the rules and there's nothing you can do to change it without the council changing it. You must revert the description changes-there is no discussion for this.
2. Notifying is bad. And hit-medscanning would get you banned for metagaming.
3. Chaplain can't be killed by the cult now because he's immune to their magic, does 25 damage on hit, instantly knows the guy is a cultist, and immediately starts screaming after the first self defense hit because someone is disarming him and now the entire station knows there's a cult. Unless the cult manages to get a tazer or stunprod on him early on all it takes is one hit for him to scream CULT CONFIRMED. It's hard enough to kill the fucker normally.
4. Crew can easily stop armor/sword cult because their armor is suprisingly weak because armor is shit and their swords do shit damage and don't block anything. One security officer can kill about three robed cultists with no issue.

**Comment by FluffySurvivor** [comment]
1. Council changes rules. Coders change code. It's a normal balance change that gets interpreted according to the rules. I see no issue with modifying the desc. 
2. Cult is the ONLY conversion gamemode where implants are nothing. In gang or rev sec stun-implants everyone and wins. There literally is no way of calling someone a cultist: tome metashielded, implant does nothing. There must be a way to to identity cultists, and concentrating all that power into one guy makes things interesting, opposed to an implant-centered gamemode. It's much easier for the cult to kill one guy with a stunprod and space his rod than for revs/gang to space the implants in the ARMORY,  HOS' OFFICE (which often hos keeps them on himself when rev/gang is called) AND disable cargo. Centering power on a person, rather than objects. It will make things different and interesting and will change the cult meta. And even then, it's just a glorified fireaxe with only a part of an implant's functionality. 
3. If you don't kill him and just disarm him, again, it's your fault for being bad and getting called out. No gamemode spoonfeeds its antags, excepting current cult. 
4. Go on a rampage with taser+sword while shrugging off damage with your DS armor and tell me how it feels. 

I could've just nerfed the cult by adjusting vars. I chose instead to bring a new interesting skill-based counterplay mechanic rather than "you're weaker regardless". Basically a race for the chaplain, like the race for cargo in gang or rev. Isn't that cool?

**Comment by ShadowDeath6** [comment]
I'd like to see cult winrate. I've very rarely seen them completely stomp crew and it's only when multiple people are competent.

> escape req increased 10 to 15 

Has it ever been 10?

> rscdel: removed metashield

Yeah, no. Metashield is a rule, not a code problem. What even makes you consider coders can influence what admins can or can't ban over?

And wow, surprise, antags are SUPPOSED to be stronger than crew, be it numbers, equipment, or any combination of the two. 

> I could have just nerfed cult by adjusting vars

That's literally exactly what you did.

**Comment by EMT321** [comment]
The only part I fervently agree with is the metashield removal. No other group antag has a metashield for trademark items.

How would I go about requesting a removal of the metashield on tomes? I already made a forum post, but it was ignored.

**Comment by Cruix** [comment]
We could make the tomes look like actual normal book to non-cultist non-chaplains. There would still be some level of meta, but it would be possible to make a fake cult by just printing out lots of blank books, so sec would not just be able to call it 100% after searching a cultist. I know exactly how to code this.

**Comment by FluffySurvivor** [comment]
Why the fuck do we need to spoonfeed cultists so badly? If you're a rev head or a gang boss, if you get caught with incriminating items you get implanted and executed as an enemy of nanotrasen. Compared to cult, revs and gangs take a huge hit when their bosses go down.

**Comment by ShadowDeath6** [comment]
Rev and gangs can spread really fast because one person can convert a ton of people. Cult needs three people and isn't instant, so they're at a massive loss when they lose members.

**Comment by FluffySurvivor** [comment]
That's why you get good and l2p. Don't get caught and stop relying on metashields to save your sorry ass.

**Comment by ShadowDeath6** [comment]
The problem doesn't lie in one person, it's that 80% of the cult is almost always completely retarded and can't stand next to a circle.

**Comment by FluffySurvivor** [comment]
That's why you carry the cult. That's what I did when I was still playing cult, solokilling security and leaving the teammates to do their cult shit.

**Comment by FluffySurvivor** [comment]
daily reminder that cult always wins and is still absolutely unfun to play against, with the supposed hard counters being meaningless

**Comment by ShadowDeath6** [comment]
daily reminder that unless cult is full of experienced players they will never win because nobody takes initiative

**Comment by FluffySurvivor** [comment]
just had a cult round where narsie was summoned 10 mins, NOBODY knew it was cult
cultists start with their objectives complete what the fuck is this

please merge

**Comment by oisin100** [comment]
> The null rod now deals 25 brute against cultists and the user is notified their target is a cultist.

I really dont think this is a good idea, As people said before, as soon as  the crew realizes its cult it would be completely valid to run up and down hallways whacking people with null rods.

**Comment by FluffySurvivor** [comment]
> as soon as the crew realizes its cult it would be completely valid to run up and down hallways whacking people with null rods.

That's exactly what happens with implants in gang/rev. 

The cult is supposed to get rid of the rod, which is much easier than it is for gang/rev to get rid of implants.

**Comment by oisin100** [comment]
> That's exactly what happens with implants in gang/rev.

There's limited implants though, whereas you can just spam the null rod.

I don't think any gamemode should revolve around the location of a single item(Apart from nukeops)

**Comment by FluffySurvivor** [comment]
And yet, it's nothing of spectacular power.
It's a singular, irreplaceable (unlike implants that can be simply spammed at cargo) strong-ish damage weapon with no block chance or such.
Cultists can still stunprod the chaplain (supposed counter) and he's done.
The purpose of the change is to make cult counterable by at least _something_

It is needed, as deconversion in cult is very unreliable and slow, identifying cultists is difficult (due to metashields and implants having no effect).

**Comment by ghost** [comment]
Unfortunately, coders cannot contradict the rules with what they code. The metashield removal conflicts with the rules, and as such unless the council approves the change the PR will be closed automatically.

Reduce roundstart cult spawns to 4, remove the escape objective and keep only nar'sie, remove null rod validhunt and instead add the null rod to religious supply crates and make it do more damage to cultists in armed gear and robes, and make the holy water deconversion take 10 seconds instead of multiple minutes.

And you have to remove the metashield changes. As much as I agree with not shielding cult, you /must/ remove the changes or the PR will be autodenied barring the council changing the metashield.

Spoiler alert, we held a vote and the metashield won't be changed.

**Comment by ghost** [comment]
Also, cult has a 22% winrate.

**Comment by FluffySurvivor** [comment]
> Also, cult has a 22% winrate.

don't use /tg/ stats they run a completely different cult lol

> we held a vote

what vote ???

> The metashield removal conflicts with the rules

I removed nuffin' , I just changed the desc.

> make it do more damage to cultists in armed gear and robes

that's useless and bad

> remove the escape objective and keep only nar'sie

narsie is uncounterable, whereas (very rarely, but still possible) on escape a non antag can just bomb the shuttle full of cultist/ someone pulling off an amazing 1v10 play, so no guaranteed narsie

**Comment by ghost** [comment]
Even with the desc change, the rule will be enforced exactly as normal. So it won't change anything. Sorry, but that's how it works.

Also, nonantags should not be maxcapping the escape shuttle and we want to move away from that sort of powergaming validhunting suicide bombing shit. So no.

**Comment by ghost** [comment]
If you don't remove the desc changes the PR gets autodenied.

**Comment by FluffySurvivor** [comment]
Back to just hating on cult, I guess.

**Comment by ShadowDeath6** [comment]
Just remove the nullrod changes and the blatant code rule breach of removing metashield and it's fine

**Pull request closed without merging**
