### PR TITLE
Adding Cortical Borers to Xenoscience

### PR DESCRIPTION
**Pull request by MacHac**
### Intent of Pull Request
- Cortical Borers can now be spawned in xenoscience with golden slimes

Borers can be spawned in xenobiology by injecting golden slimes with plasma or blood.  Borers fall into a bit of a grey area with the gold slime code as it currently stands, as they are neither hostile nor benevolent (Unlike some other monsters that players control, like aliens).  For the moment, they are grouped in with the hostile mobs, but have no attack code and thus will act like passive animals.  To add them to the nice mobs list, uncomment line 73 in Chemistry-Recipes.dm.  As 'hostile' mobs, their spawn rate is 1/43 or 2.3%;  As nice mobs, they are significantly more common and may be as high as 1/15 or 6.7%.

### CODE REVIEW

**Comment by ghost** [comment]
Are you even in coder chat right now? If not, add me on skype and i'll toss you in.

**Comment by MacHac** [comment]
My microphone hasn't been working recently, and I can't get a new one until wednesdayish.  I've just been listening to OOC and trying to figure out what people want.

**Comment by ghost** [comment]
We don't use voice or facechat for skype. It's all text, and it helps co-ordinate design.

Albiet what you're doing is great and i'm going to yell at coders to do what you're doing.

**Comment by ShadowDeath6** [comment]
So they're hostile-spawned only currently? Sounds fine, and gives xenobio some more cool things to make.

:+1: x :100:

**Comment by Time-Green** [comment]
Please no

Borers should be rare. I dont want to see them every round

**Comment by ShadowDeath6** [comment]
They're currently very rare, and they're literally xenobiological organisms. It's a super low spawn rate in  gold slime extracts, so it's not like it'll happen every round.

**Comment by ghost** [comment]
Okay.

So let's see.

How common is it for someone to do xenobiology? I'll call it, assuming the server is on highpop between 2-8 PM, that's 3 hours of 80 people and so a fully stocked job slot in science.

So 6/24 already. So 1/4.

So 1/4 of the day, there is a 1/6 chance a scientist will be doing xenobiology.

Then, out of the 21 slime types there are that you can get, 10 of them have a x2 chance to appear. So let's go with it being 41 possibilities, assuming each slime splits perfectly every time you spray it, and doesn't just make more of the same type.

The two slimes you would need for this are light pink slime, and gold slime. Assuming it is 5 minutes per each slime division as is usual with no impedements.

So 1/4 of the day, there is a 1/6 chance a scientist will be doing xenobiology, and have a 3/41 chance of getting the necessary slimes within fourty minutes. The remaining part of the 3/41 can be totaled up into an additional 10 minutes to account for exponential slime growth and the chances of not getting the exact slimes you want.

Then, let's count how many gamemodes last above 30 minutes.

Blob usually does not. Wizard usually does not. Malfunction usually ranges from 20-40 minutes. Nukeops does not go above 30 unless ops are terrible. Rev ranges from 10 minutes to 2 fucking hours. Shadowling usually ends at around the 30-40 minute mark.

So the remaining roundtypes that can go above 30 minutes are Traitor, Traitorchan, Cult, Gang, and possibly rev.

So that's 4/10 gamemodes where the round will last over 30 minutes, meaning it's even possible to get that far.

And then let's account for how often it is that the scientist doing xeno will get bored, be stupid, ect, and not be competent enough to get the necessary slimes.
I'll call it a 1/10 chance the guy doing it will be good.

And finally, they have a 1/43 chance of appearing from a gold slime.

So,  1/4 of the day there is a 1/6 chance a scientist will be doing xenobiology, and a 1/10 chance the guy will be competent. And there is a 3/41 chance of getting all the slimes you want within 40 minutes on your first go. And then to top that off there is a 4/10 chance the round will even last long enough for you to get that far, and a 1/43 chance of appearing from a gold slime on your first try.

The chance at this point is literally in scientific notation. I'll eat my own ass if it's every round because borerstorm from xenobiology is probably going to happen maybe once a fucking month.

**Comment by AsV9** [comment]
Yeah Adam is his typical self. Chances can be buffed later.

**Comment by Time-Green** [comment]
Adam u suck at calculating

**Comment by ghost** [comment]
> typical self

@AsV9  you what

i'm just telling tim it won't happen every round

**Comment by Time-Green** [comment]
Good enough

**Comment by ShadowDeath6** [comment]
> Be me
> Do Xenobio
> Spam gold slime extracts infinitely until I get infinite borers
> :^)

**Comment by MacHac** [comment]
Do not merge this yet, balance changes are still being discussed.  The changes should be committed soon.

**Comment by DavidEdwards** [comment]
I like this a lot. ++

**Comment by MacHac** [comment]
# **Do NOT Merge tag can be removed, the balance changes are as follows:**

Gold slimes now have a fourth type of reaction, achieved by injecting 5 units of Strange Reagent into the extract.  At the moment, the reaction will either create an unactivated swarmer or a cortical borer.  The reaction will then look for a player to occupy the newly created mob.  This rebalance means that less xenoscience (and less luck) is needed to create a borer or swarmer, but flooding them isn't easy and takes time since Strange Reagent is in such short supply.

**The exact way to make the borers is not in the changelog.  This is intentional.**
In an effort to combat the (almost inevitable) borer/swarmer spam when this gets merged, the strange reagent reaction should remain reasonably secret for at least a while.  While the open source nature of yogstation makes it difficult to keep these secrets indefinitely, **the recipe for borers and swarmers will spread very slowly outside of the github readers as long as most people don't tell anyone else.**

Enjoy responsibly.

### NOTE:

Spiderlings and facehuggers would fit the theme, but were omitted from the spawn list because they are (in the vast majority of cases) an instant shuttle call, and that might unbalance xenobiology.  They can be added very easily if/when they are rebalanced.

**Comment by ShadowDeath6** [comment]
Merge when

**Comment by ghost** [comment]
eh

instead of GUARANTEED result of two powerful antags, knowing that at some point this WILL be leaked

i'd say increase chances of borer/swarmer significantly, perhaps 1/8 or 1/10th, when injected with strange reagent

**Comment by ShadowDeath6** [comment]
How would that work, adam?

**Comment by MacHac** [comment]
That would be slightly difficult given the current state of the code.  Even then, a one in ten chance is not much at all given how long it takes for slimes to reproduce and how difficult it is to make strange reagent.  I'll think about it.

**Comment by MacHac** [comment]
Spawning mechanics have now been rebalanced.  Gold slime extracts only require 2u of Strange Reagent to react (down from 5u), but the reaction now has an 85% chance to fail.  This necessitates extensive gold slime breeding to get what you want.  The end result of this is that the reaction remains an obtainable goal while not necessarily being possible every round, depending on the whims of the RNG.

**Comment by DavidEdwards** [comment]
Great, with the RNG change I think this can merge in.

**Pull request merged**
