### PR TITLE
Nerfs the dual energy sword's block chance from 50% -> 0%

### PR DESCRIPTION
**Pull request by Super3222**
### Intent of your Pull Request

Nerf the dual energy sword ... again.

Because once again there's no counters to it, and there should almost always be counters. Stunbatons should ALWAYS counter a traitor with a double energy sword, but as of now they don't.
#### Super3222

:cl:
tweak: Dual Eswords block chance is now 0. However, it'll still reflect energy projectiles. Not so much for ballistic or melee.
tweak: Eswords have a block chance has been lowered to 0.
/:cl:

### CODE REVIEW

**Comment by FluffySurvivor** [comment]
OP against who/what? 
We have the murderbone rule u kno.

**Comment by Super3222** [comment]
@FluffySurvivor 

OP against everything.
A weapon that literally has a 50% chance to completely negate any type of attack / projectile.

Anyway, stunbatons should always be a hardcounter against dual eswords or eshields. It's always been like that, so why change it now? This has been a long time coming.

I expected it to be fixed after #1040 and #1050. When I say fix I mean 100% going to 0%. Instead the dual energy sword's block chance was taken down from 100% to 50%. After testing it on my server, it's still running into the same problem we had last time with everything. RNG. Random.

I thought we were getting rid of combat in RNG. Besides, they were fine before we buffed them.

**Comment by FluffySurvivor** [comment]
M E R G E

**Comment by Super3222** [comment]
In conclusion. Dual energy swords will only have a 70% block chance against unarmed attacks, and that's it. Energy swords will NOT block attacks.

**Comment by ParagonPrime** [comment]
Energy swords should have a 100% chance to block disarms. Because batting a fucking dual plasma blade out of somebody's hands with your _bare hands_ is fucking retarded, and disarm-spam is overpowered as it is.

**Comment by FluffySurvivor** [comment]
50%----> 100% chance to block disarms
50%---->0% chance to block other various melee

Good trade-off. 70% is shitty middle-way rng so no.

**Comment by ParagonPrime** [comment]
agreed with fluff

**Pull request closed without merging**
