### PR TITLE
Shadowling Tweaks

### PR DESCRIPTION
**Pull request by TehFlaminTaco**
Removed Toggles for Dark Vision and Shadow Walk
Made Shadowlings, Ascendants, and Statues always shadow-walk.
Made it so Shadowlings (And observers and such) can tell the difference
between light tiles and pure black tiles.
Fixed things not rotating when pulled around in darkness with
shadowwalk.

### CODE REVIEW

**Comment by X-TheDark** [comment]
Oh damn, Shadowwalking statues, that's a pretty nice buff for Xenobio statues.

**Comment by TehFlaminTaco** [comment]
Image of new Vision

**Comment by ghost** [comment]
oh good

shadowwalking statues

not only are they completely immortal and move at the speed of eat a dick, they can now move through walls, barricades, out of locked or closed areas that they get trapped in including walling them off

and hit for 45 damage

congratulations, you've made statues so ungodly overpowered all a xenobio traitor has to do is make one statue setinent and tell it to murderbone

You can't wall it in because it'll shadowwalk out.

You can't space it because they can't be pushed.

You can't kill it because it has 10,000 health.

**Comment by ghost** [comment]
And can you give thralls the same nightvision as slings for the love of god, they need a buff because thralls are weak as shit and basically useless now

**Comment by X-TheDark** [comment]
Statues can be spaced. Although you cannot move them, you can move a locker over them and close it, trapping the statue inside. Still, I think a spaced statue can easily return to the station anyway (Unless shadowwalk respects inertia effects)?

**Comment by Groudonmaster** [comment]
Statues can easily break out of lockers because they can attack in then shattering the locker

**Comment by TehFlaminTaco** [comment]
The thing is, is that the Xenobiologist needs to keep them locked down long enough to sentient them. Otherwise...

**Pull request merged**
