### PR TITLE
Borer fixes

### PR DESCRIPTION
**Pull request by oisin100**
Not sure how i managed to close and delete my last PR...

### CODE REVIEW

**Comment by oisin100** [comment]
Ill fix the conflicts tomorrow.

**Comment by ShadowDeath6** [comment]
> tomorrow

:'^)

**Comment by DavidEdwards** [comment]
He has computer problems smart ass :P

**Comment by DavidEdwards** [comment]
Since Oisin is having computer issues, and I've been looking at borers myself, I'll make this conflict merge.

**Pull request merged**
