### PR TITLE
Rezadonut box for xenobiology.

### PR DESCRIPTION
**Pull request by B1gb3ast**
So lazy scientists won't have to go to medbay, woo!
Convenience!
Easy mode!
Screw cryo!

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
:+1:

**Comment by ghost** [comment]
these kill people

these legit kill people because there's too much rezadone in them and if they eat 3 donuts they are fucking dead

also

why are you removing department interdependance

if you're going this way just add cyro to each department, because god forbid people actually leave their areas to interact with people or depend on other departments for assistance

bad.

**Comment by ShadowDeath6** [comment]
If you die to rezadone you suck

These are for lower damage problems, like being latched by a slime for a second or two. This will in no way replace cryo.

**Comment by B1gb3ast** [comment]
Can't wait for some tresspassing clown to munch down on all the donuts.

Should I add a "mildly toxic" to item description?

There's only 15 units of rezadone in each donut, and from what I have heard it's 1 damage per unit.

**Comment by ShadowDeath6** [comment]
Maybe have the box say something like "Note- Eating multiple Rezadonuts is highly discouraged by our experts and may result in disfiguration of facial tissue. "

**Comment by Time-Green** [comment]
Just add it. Only for the idea of giving it to the clown

**Comment by DavidEdwards** [comment]
I am against removing inter-department cooperation mostly. That's one reason we "broke" the grinder.

Unless there is an uproar demanding such a thing, I'll close this PR for now.

**Pull request closed without merging**
