### PR TITLE
Smuggler's body bag

### PR DESCRIPTION
**Pull request by Time-Green**
A 3 tc syndicate body bag that can be hidden under floor tiles and holds 1 person. Has a slightly darker and greener sprite.

:cl:Time-Green
rscadd: Smuggler's body bag. A 2 tc body bag that can be hidden under floor tiles and can store 1 person.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
This can be closed as quickly as it was created, so if ya guys don't like it, no problem.

**Comment by Cruix** [comment]
Make it so that if it has a floor tile in it when it closes, it places the floor tile over itself. Then you can hide inside it and pop out to surprise your target if there is not a convenient disposal.

**Comment by Time-Green** [comment]
Cool idea, I'll probably try doing that tomorrow

**Comment by Super3222** [comment]
> Add: Smuggler's body bag.

It's rscadd:

**Comment by ghost** [comment]
> 2 tc item that lets you hide bodies to be completely undetectable in plain sight

**Comment by FluffySurvivor** [comment]
@AdamElTablawy 
It's a good trade-off tho. You could buy 2 carps or a door charge or 2 c4s
It's an utility item

**Comment by ghost** [comment]
2 tc to permanently hide a body for the rest of the round is not a good trade off compared to an obvious breaching item that is hard to kill people with without finagling or harmless carp

there's a reason why pizzabombs cost so much and that's cause they gib

**Comment by Time-Green** [comment]
Then i'll just increase the price
@AdamElTablawy any suggestions?

**Comment by Time-Green** [comment]
Alright, increased tc, and while bashing my head on my keyboard trying to do what cruix said, I thought: Wait this is supposed to hide bodies not yourself
Might have been a thought of lazyness

**Comment by FluffySurvivor** [comment]
Congrats nobody will ever buy the item

**Comment by ghost** [comment]
close the PR it's overpowered and a bad idea

**Pull request closed without merging**
