### PR TITLE
Adds Medihover borg icons

### PR DESCRIPTION
**Pull request by utahclock**
Adds Icon for mediborg. Coders please add to borg selection menu.

### CODE REVIEW

**Comment by Notamaniac** [comment]
Sprites plox

**Comment by utahclock** [comment]
sprites are there Notamaniac

**Comment by Notamaniac** [comment]
I mean put them in the PR so we can see that at a glance. Just drag the png file and drop it into the comment box

Edit:
Right, found the sprite in the dmi. The rocking looks a little weird on the borg, probably because A : most sprites in SS13 don't change their perspective B : It needs to rock randomly rather than in the same direction. Just change it to bob like the other mediborg.

Also you've used pure black for the outline. Never use pure black on a SS13 sprite, it stands out harshly. Use either a dark blue or a dark shade of gray

And forgive me if I've been blind I can't see the borg eye sprites or the borg headlamp sprite in the DMI, those are pretty important for seeing if the borg is dead or not.

**Comment by Notamaniac** [comment]
Right, found the sprite in the dmi. The rocking looks a little weird on the borg, probably because A : most sprites in SS13 don't change their perspective B : It needs to rock randomly rather than in the same direction. Just change it to bob like the other mediborg.

Also you've used pure black for the outline. Never use pure black on a SS13 sprite, it stands out harshly. Use either a dark blue or a dark shade of gray

And forgive me if I've been blind I can't see the borg eye sprites or the borg headlamp sprite in the DMI, those are pretty important for seeing if the borg is dead or not.

**Comment by DavidEdwards** [comment]
I quite like the rocking. I think we need more input on this one.

Good points with the black and the eyes. Both important.

Edit: Additionally, remember to add a changelog file for your changes. There is an example in /html/changelog/. Copy the example.yml file, edit it in notepad.

**Comment by utahclock** [comment]
Closing this pull reuploading sprite with eyes shown and blue outline

**Pull request closed without merging**
