### PR TITLE
You can now recycle cable restraints

### PR DESCRIPTION
**Pull request by Super3222**
#255.

Cable restraints can be recycled back into coils by untying them in your hand.

Furthermore, the other request will probably be in another PR. It was where if you're cuffed and click on a wirecutter, you can free yourself under a little over 10 seconds.

### CODE REVIEW

**Comment by DavidEdwards** [comment]
Looks good. Have you considered the implications of getting 15 coils back from a single restraint?

**Comment by DavidEdwards** [comment]
Please also make sure that you add a changelog .yml file indicating your changes. There is an example here: /html/changelogs/example.yml.

**Comment by AsV9** [comment]
@DavidEdwards Don't cable coils require 15 lengths of cable to make?

**Comment by Super3222** [comment]
Cable restraints require 15 lengths of cable to make. I made it so the new cable coil amount that you get equals 15.

> Please also make sure that you add a changelog .yml file indicating your changes. There is an example here: /html/changelogs/example.yml.

Thank you, I'll start doing that for the rest of my PRs. The example was helpful.

**Pull request merged**
