### PR TITLE
Tesla now follows singularity beacon.

### PR DESCRIPTION
**Pull request by AsV9**
Because I thought it would be fun.

### CODE REVIEW

**Comment by ghost** [comment]
madman

**Comment by Wardog390** [comment]
Better than following ghosts

**Comment by FluffySurvivor** [comment]
woooo :+1:

**Comment by ShadowDeath6** [comment]
Do we really need to clutter up tags with things that are hardly ever going to be used? I can't imagine tesla changes being so popular that it needs a whole tag dedicated to it, but whatever floats your boat, I guess.

**Comment by DavidEdwards** [comment]
This could actually be legitimately used by the crew to avert disaster from tesla escaping. I like this.

**Comment by AsV9** [comment]
@ShadowDeath6 
Go look at the tags on tgstation/-tg-station and tell me what you found.

**Comment by ShadowDeath6** [comment]
They consistently have 200 quintillion PRs it, though, and they've had it for way longer, meaning most of the bugs are fixed by now.

**Comment by AsV9** [comment]
Labels, not issues or pulls.

**Pull request merged**
