### PR TITLE
Cybermen Updates v2

### PR DESCRIPTION
**Pull request by Cruix**
*Moved cybermen hack and objective processing to SSobj.processing, so Cybermen can now hack in any gamemode.
*Added "Make Cyberman" option in create antagonists panel.
*Removed references to BE_CYBERMAN flag in prefs due to issues with the bitwise operators.
*Fixed some small bugs.
*No, you still cannot hack microwaves, Xantam. Sorry.

### CODE REVIEW

**Comment by Cruix** [comment]
Oh god how did all these commits get in there?

EDIT: It's because I pulled from the master branch instead of the dev branch to update my repository. Why is the dev branch so far behind the master branch?

**Comment by george99g** [comment]
> EDIT: It's because I pulled from the master branch instead of the dev branch to update my repository. Why is the dev branch so far behind the master branch?

We did a switch on the main branche and not everyone has started using dev instead of master yet.

**Comment by Cruix** [comment]
Are you willing to take all these commits into the dev branch through my PR or do you want me to remove them? I am terrible at rebasing branches so I will probably try to figure it out for three days and then give up, make a new pull request, and close this one.

**Comment by Cruix** [comment]
Closing this so I can reopen it with fewer commits.

**Pull request closed without merging**
