### PR TITLE
Dynamic User Interface

### PR DESCRIPTION
**Pull request by Cruix**
Requires testing
Response to issue #43

Adds:
-Support for custom Cyborg and AI UIs
-Support for donator-only UIs
-The ability to change your UI in-game through the "Select UI Style" verb in preferences
-Two new donator-only UIs, one for Cyborgs (Beepsky) and one for AIs (Matrix_OS)
-Three new saved preferences for UI style (one for each of AI, Cyborg, and Carbon)

Removes:
-the old method of selecting UIs in the pre-game lobby
-the old saved preference for UI style

Issues:
-UI always redraws when you change your carbon UI, even if you are currently using a different UI.
-When the UI redraws, there is a short period in which screen effects like blindness and flash are removed, and certain UI icons show incorrect values (such as the health doll)

### CODE REVIEW

**Comment by AsV9** [comment]
ayy lmao

**Comment by Xantam-13** [comment]
Seems there are conflicts on this? 

Have you got a screenshot of this in use?

**Comment by Cruix** [comment]
I'll fix the conflicts soon.
Screenshots:
Popup window:
ui 1

New AI ui:(The 1s and 0s scroll down)
ui 2

New Cyborg UI:(I just badly drew a picture of Beepsky on some of the icons, it was more as a test than to make a serious UI)
ui 3

**Comment by Cruix** [comment]
Oh man do I hate conflicts. I will fix after the weekend.

Please add "needs testing" and "do not merge"

**Comment by Cruix** [comment]
Closing this because 43 commits is crazy. Reopened in #258.

**Pull request closed without merging**
