### PR TITLE
Ei nath is no longer round ruining

### PR DESCRIPTION
**Pull request by ShadowDeath6**
Refer to issue #1139 .
### Intent of your Pull Request

Ei nath no longer explodes your body and ruins your round if wiz picks up your brain

AND BEFORE YOU SAY "OH SHADOW WIZ IS SUPPOSED TO BE OP"

literally every other spell allows the victim to be recovered

also the cooldown is 50 instead of 60 because direct nerfs are baddu
#### Changelog

:cl:
tweak: The Wizard's Disintegrate spell, also known as Ei Nath, no longer gibs, just kills.
tweak: The cooldown for Disintegrate has been decreased to compensate for its decrease in lethality.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
I need to sleep, please comment on how I'm retarded and that my ideas are dumb so I may respond when I awaken

**Comment by ghost** [comment]
> instant defib

make it do shitloads of brute to all damage to prevent defibbing and make it eject the brain from the body so that the wiz can still scoop it up

**Comment by FluffySurvivor** [comment]
>round ruining antags

**Comment by ToGWtF** [comment]
:-1:

**Comment by FluffySurvivor** [comment]
> round ruining antags

**Comment by ShadowDeath6** [comment]
I'll make it do damage, but ejecting the brain will just put it in the exact same place it's in now.

**Comment by FluffySurvivor** [comment]
> ruins your round
> aka you can't validhunt the wizard for the round

**Comment by ShadowDeath6** [comment]
> wizard repulses you for instant stun
> hits you once with a melee attack which deletes your body and all your items
> spaces your brain in a backpack along with 7 other brains
> wizard kills science so there's no chances for ghosts to get back into the game
> server population drops

Literally any round with an ei nath + any stun wizard that murderbones

**Comment by ShadowDeath6** [comment]
I fixed the coherent arguments with this, can it be reviewed by an HC?

**Comment by oisin100** [comment]
OH SHADOW WIZ IS SUPPOSED TO BE OP

But really, Ei-Nath has a super long cooldown and it isnt ranged, i think Ei Nath is balanced as it is.

**Comment by ShadowDeath6** [comment]
I lowered cooldown to compensate for making it less retardedly annoying to deal with. Considering how many stun spell a wizard has in its arsenal, it might as well be ranged anyway. This just makes it less of a 'gg your round is over if wiz gets in a 3x3 range of you'.

**Comment by FluffySurvivor** [comment]
So what if your round is over? 
You lost, deal with it. 

Dodge the stuns or keep getting gibbed.

**Comment by ShadowDeath6** [comment]
Dodge the instant, uncounterable stun and then dodge the second, longer stun while you're down. 
This isn't nerfing wizard's capability at all, this is just changing a stupid, unfun game mechanic and making it so a wizard can't depopulate the entire station with no hope of anyone they killed getting back in the game outside of midrounds or ERT.

**Comment by FluffySurvivor** [comment]
Then nerf repulse's instant stun and make it counterable you chucklefuck xD

**Comment by oisin100** [comment]
> Then nerf repulse's instant stun and make it counterable you chucklefuck xD

Ay.

Another reason i dont want Ei' Nath to be nerfed like this is because `Ei' Nath` is such a iconic spell.

That came out much worse then what i was thinking in my head... Oh well.

**Comment by ghost** [comment]
@oisin100 

Just because something is 'iconic' does not mean it should not be changed if it's obnoxious as fuck. Lube and ebows were also iconic-they got changed for the better because they were uncounterable cheese.

The justification that 'nerf a far less deadly spell to make it effectively useless instead of nerfing a cheese instant kill spell' is retarded.

It is a spell that leaves you UNCLONEABLE on click. That's the issue.

This does not change Ei nath's lethality. It still kills you instantly and it leaves you undefibbable-the only thing it does is mean it doesn't debrain you, so that cloning is still a possiblity, like EVERY OTHER ANTAGONIST ABILITY IN THE GAME.

Even for an intentionally overpowered antagonist, a spell that instantly leaves you unclonable and out of the round is a bit stupid. Every other antagonist ability that leaves you uncloneable has SOME sort of backlash or counter-pizzabombs and such cost tc, soulstones leave obvious evidence and still let the person back into the round, so does necrostone, absorbing takes a fuckton of time.

Ei nath is one click , gibbed, and if you think 'get good dodge the stuns' works for an antagonist that is INTENTIONALLY overpowered, well, no. All it's stuns are hard to dodge except for magic missle, it's also probably lasering and tazering you, chances are it's hiding in a locker with ei nath out.

It's stupid and annoying, and this fix means that at the LEAST you can be cloned-NOT defibbed, so you're still out of the round for a while, it's still countered by the wiz deconstructing cloning which takes two seconds and is no issue, and means that you aren't FORCED to play a borg or permanently out of the round because some dickbag picked you up.

There is no reason to not merge this.

**Comment by FluffySurvivor** [comment]
Adam, wizard has big problems gameplay and balance wise, it's basically "pick some generic OP spells and go murderbone" while the crew has to just validhunt a constantly porting antag. It's no fun. It's not cult-tier unplayable, but it's still pretty bad. The gamemode needs a wide rework. 
Making einath not gib won't fix wizard.

**Comment by ghost** [comment]
but it'll make it less shit

**Comment by ShadowDeath6** [comment]
That's how you fix dumb unfun things, you change it by bit until it's bearable.

**Comment by FluffySurvivor** [comment]
did i mention it would feel like shit

currently you have that badass burning hand and a very special sound for your badass gibbings

with no gibbing it feels like you just disarmed someone

**Comment by ShadowDeath6** [comment]
It still plays the sound and makes sparks, and personally I think it still looks nice. 

Also, aesthetic does NOT take priority over game enjoyabilty.

**Comment by ShadowDeath6** [comment]
can this be reviewed please

**Comment by X-TheDark** [comment]
As far as the code goes, it's fine. I am for merging this at least for a little bit to see how it goes. Allowing cloning after wizwoz Ei Nath's you is, in my opinion, too big of a change to make it possible to "theorycraft" how it'll affect the game.

**Comment by ShadowDeath6** [comment]
Is this the longest lasting PR yet or does cruix's changeling organ thing still hold the record

also merge pls

**Comment by oisin100** [comment]
http://prntscr.com/bjjk39

I wont be merging this, If @DavidEdwards wants to merge this then go ahead.
Your gonna have to port this to the new repo anyway @ShadowDeath6

**Comment by ShadowDeath6** [comment]
> 26 people on when the vote was made
> 14 didn't vote

probably should have made a vote when more people were on, not sure lowpop is the best indicator of our server's opinion

probably will remake the PR after the rebase shit is done to save headaches

**Pull request closed without merging**
