### PR TITLE
Fixes Critical Oversight

### PR DESCRIPTION
**Pull request by Cruix**
### Intent of your Pull Request

Bike horns and their subtypes are now assembly pieces. Finally the clown can remotely honk the station to insanity. Requested by Adam.

Also makes horns work from inside lockers.

### CODE REVIEW

**Comment by ToGWtF** [comment]
mad genius

**Comment by MacHac** [comment]
> getting travis failed by a map that we don't even use

**Comment by Cruix** [comment]
I HAVE DEFEATED THE MYTHICAL BEAST KNOWN AS TRAVIS

**Comment by Super3222** [comment]
Honk.

**Comment by TehFlaminTaco** [comment]
RIDICULOUS FOLLY.
INEXCUSABLE.

**Comment by ShadowDeath6** [comment]
what a madman

**Comment by DavidEdwards** [comment]
Not sure what the purpose of this is. Why make them assembly parts?

**Comment by X-TheDark** [comment]
I'd wager that it's to add things like signalers, proximity sensors, etc to it.

**Comment by oisin100** [comment]
Countless fun to be had with this.

**Comment by DavidEdwards** [comment]
May god forgive me...

**Comment by Kmc2000** [comment]
This is the first idea adam's has n a long long time that i 101% support. 

Now to rig all the doors with bikehorns and watch chaos ensue

**Pull request merged**
