### PR TITLE
Shadowling Changes

### PR DESCRIPTION
**Pull request by TehFlaminTaco**
As usual...
Veil range decreased by two tiles.
Icy Veins now has a 30% chance to fail at extinguishing a torch/flare
Shadowlings now move at about half speed in light.
Shadowlings move at meth speed in darkness, but movement delay kicks in
if they try to step into light. So they wont accidently sprint into
space or anything.

### CODE REVIEW

**Comment by ghost** [comment]
> Buffing shadowlings

No, they're strong enough.

60% chance to fail at extinguishing a torch/flare and remove the speed boost in darkness.

Lower glare stun time too.

**Comment by TehFlaminTaco** [comment]
The only way they're buffed is they go faster in their natural habitat.
Which was just the result of a different nerf.

**Comment by ghost** [comment]
They're strong enough and need to stay at their normal speed in their natural habitat.

**Comment by TehFlaminTaco** [comment]
Why though, a flare can prevent them from getting in there solidly.

**Comment by ghost** [comment]
a flare that shadowlings can extinguish

also it makes chasing them down impossible

no more buffs to shadowling, period.

no buffs in this PR at ALL.

**Comment by ShadowDeath6** [comment]
I like meth speed, it's cool.

**Comment by ghost** [comment]
no buffs

**Comment by TehFlaminTaco** [comment]
Adam is salty about a +1 speed increase. Honk.

**Comment by oisin100** [comment]
I agree with Adam. No buffs.

**Comment by FluffySurvivor** [comment]
I agree with movespeed buff in darkness.

I really like this pr, amplifying the strengths and weaknesses of slings.

**Comment by ghost** [comment]
Two more things.

Make braindeads unable to be enthralled and make dethralling surgery use the same steps as organ manip, so mediborgs can dethrall.

**Comment by Cruix** [comment]
It seems that shadowlings already can't enthrall braindeads.

**Comment by TehFlaminTaco** [comment]
Yeppers. Shadowlings can't enthrall braindeads.
I'll probably work on changing its surgery though.

**Comment by ShadowDeath6** [comment]
It's a bug in it, it displays a message but doesn't return(correctly?), so they can still enthrall.

**Comment by TehFlaminTaco** [comment]
Fixed

**Comment by TehFlaminTaco** [comment]
Merge when?

**Comment by DavidEdwards** [comment]
Any additional comments on this?

**Comment by ghost** [comment]
everything in the github has been up for over a week merge it all

**Pull request merged**
