### PR TITLE
Revert "Flying over tables with jetpack"

### PR DESCRIPTION
**Pull request by DavidEdwards**
Reverts yogstation13/yogstation#266

### CODE REVIEW

**Comment by FluffySurvivor** [comment]
Why? 
:-1:

**Comment by oisin100** [comment]
Because you can walk through any windoor,table or glass airlock with your jetpack on...

**Comment by Alek2ander** [comment]
Because it's utterly broken

**Comment by FluffySurvivor** [comment]
Oh, alright then.

**Pull request merged**
